// Generated by gspot 0.1.0 from gspot.toml. Do not edit.
// Change policy: gspot set / allow / ignore, or edit gspot.toml, then run: gspot apply
module.exports = {
    rules: {
    "type-enum": [
        2,
        "always",
        [
            "feat",
            "fix",
            "refactor",
            "perf",
            "docs",
            "test",
            "build",
            "ci",
            "chore"
        ]
    ],
    "type-case": [
        2,
        "always",
        "lower-case"
    ],
    "type-empty": [
        2,
        "never"
    ],
    "scope-case": [
        2,
        "always",
        "kebab-case"
    ],
    "subject-empty": [
        2,
        "never"
    ],
    "subject-full-stop": [
        2,
        "never",
        "."
    ],
    "subject-case": [
        2,
        "never",
        [
            "start-case",
            "pascal-case",
            "upper-case"
        ]
    ],
    "header-max-length": [
        2,
        "always",
        72
    ],
    "body-leading-blank": [
        2,
        "always"
    ],
    "body-max-line-length": [
        2,
        "always",
        72
    ],
    "footer-leading-blank": [
        2,
        "always"
    ],
    "scope-enum": [
        2,
        "always",
        [
            "cli",
            "eslint-plugin",
            "root",
            "hooks",
            "deps"
        ]
    ],
    "scope-empty": [
        2,
        "never"
    ]
},
};
