// Generated by gspot 0.1.0 from gspot.toml. Do not edit.
// Change policy: gspot set / allow / ignore, or edit gspot.toml, then run: gspot apply
import { fileURLToPath } from 'node:url';

import eslint from '@eslint/js';
import gspot from '@gspot/eslint-plugin';
import eslintComments from '@eslint-community/eslint-plugin-eslint-comments';
import boundaries from 'eslint-plugin-boundaries';
import importX from 'eslint-plugin-import-x';
import jsdoc from 'eslint-plugin-jsdoc';
import nodePlugin from 'eslint-plugin-n';
import packageJson from 'eslint-plugin-package-json';
import regexp from 'eslint-plugin-regexp';
import security from 'eslint-plugin-security';
import sonarjs from 'eslint-plugin-sonarjs';
import unicorn from 'eslint-plugin-unicorn';
import prettierConfig from 'eslint-config-prettier';
import globals from 'globals';
import tseslint from 'typescript-eslint';


const root = fileURLToPath(new URL('..', import.meta.url));

const CODE = ['**/*.{js,mjs,cjs,jsx,ts,tsx,mts,cts}'];
const TYPESCRIPT = ['**/*.{ts,tsx,mts,cts}'];
const JAVASCRIPT = ['**/*.{js,mjs,cjs,jsx}'];
const TESTS = [
    "**/*.{test,spec}.{ts,tsx,js,mjs,cjs}",
    "**/tests/**",
    "**/__tests__/**"
];
const SCRIPTS = [
    "scripts/**",
    "**/*.config.{js,mjs,cjs,ts}",
    ".mise/tasks/**",
    "packages/npm/**",
    "packages/cli/build.ts",
    "packages/cli/publish.ts",
    "packages/cli/schemas.ts",
    "packages/cli/rules-lint/command.ts",
    "packages/eslint-plugin/build.ts",
    "docs/reference-pages.ts"
];
const ALIASES = {
    "#cli/": "packages/cli/src/",
    "#config/": "packages/cli/config/",
    "#types/": "packages/cli/types/",
    "#plugin/": "packages/eslint-plugin/src/",
    "#plugin-types/": "packages/eslint-plugin/types/",
    "#plugin-tests/": "packages/eslint-plugin/tests/",
    "#tests/": "tests/"
};

const limits = {
    fileLines: 300,
    functionLines: 60,
    parameters: 5,
    cyclomatic: 8,
    cognitive: 8,
    classesPerFile: 1,
    depth: 3,
    statements: 30,
    nestedCallbacks: 3,
    identicalFunctions: 3,
    barrelReexports: 20,
    prefixCollisions: 2,
    trivialStatements: 2,
};

const sizeRules = {
    'max-lines': ['error', { max: limits.fileLines, skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': ['error', { max: limits.functionLines, skipBlankLines: true, skipComments: true, IIFEs: true }],
    'max-params': ['error', limits.parameters],
    'max-depth': ['error', limits.depth],
    'max-statements': ['error', limits.statements],
    'max-classes-per-file': ['error', limits.classesPerFile],
    'max-nested-callbacks': ['error', limits.nestedCallbacks],
    complexity: ['error', limits.cyclomatic],
};

// One rule holds every selector, because a later block that sets the rule replaces the earlier one. The library
// selectors join the base ones here, and each block below lists all that apply to its files.
const BASE_SELECTORS = [
        { selector: 'TSEnumDeclaration', message: 'Use a literal union or an as-const object instead of an enum.' },
        { selector: 'TSAsExpression[expression.type="TSAsExpression"]', message: 'Do not assert twice. Narrow the value, improve the type, or add a typed boundary.' },
        { selector: 'TSTypeAssertion[expression.type="TSTypeAssertion"]', message: 'Do not assert twice. Narrow the value, improve the type, or add a typed boundary.' },
        { selector: 'TSAsExpression > TSAnyKeyword', message: 'Do not assert to any. Add a typed boundary or runtime narrowing instead.' },
        { selector: 'TSTypeAssertion > TSAnyKeyword', message: 'Do not assert to any. Add a typed boundary or runtime narrowing instead.' },
        { selector: 'TSAsExpression > TSNeverKeyword', message: 'Do not assert to never to silence the type system.' },
        { selector: 'TSTypeAssertion > TSNeverKeyword', message: 'Do not assert to never to silence the type system.' },
        { selector: 'LogicalExpression[operator="||"][right.type="ObjectExpression"][right.properties.length=0]', message: 'An empty-object fallback hides a missing value. Handle the missing case.' },
        { selector: 'NewExpression[callee.name=/Error$/] > Literal.arguments:first-child[value=/^[a-z]/]', message: 'Start an error message with a capital letter.' },
        { selector: 'NewExpression[callee.name=/Error$/] > TemplateLiteral.arguments:first-child[quasis.0.value.raw=/^[a-z]/]', message: 'Start an error message with a capital letter.' },
        { selector: 'CallExpression[callee.property.name=/^(json|send)$/] ObjectExpression > Property[key.name=/^(message|error)$/] > TemplateLiteral.value[expressions.length>0]', message: 'A message a client reads names no identifier; put the value in its own field.' },
        { selector: 'CallExpression[callee.object.name=/^(logger|log|console)$/][callee.property.name=/^(debug|info|warn|error|fatal|trace)$/] > TemplateLiteral.arguments:first-child[expressions.length>0]', message: 'Log a stable message and pass the values as fields.' },
];
const LIBRARY_SELECTORS = [
];
const RAW_SQL_SELECTORS = [
];
const PROCEDURE_SELECTORS = [
];
const RAW_SQL_ALLOWED = [];
const ROUTER_FILES = ['**/routers/**/*.ts', '**/*router*.ts', '**/trpc/**/*.ts'];
const librarySelectorBlocks = LIBRARY_SELECTORS.length + RAW_SQL_SELECTORS.length + PROCEDURE_SELECTORS.length === 0 ? [] : [
    { files: CODE, rules: { 'no-restricted-syntax': ['error', ...BASE_SELECTORS, ...LIBRARY_SELECTORS, ...RAW_SQL_SELECTORS] } },
    ...(RAW_SQL_ALLOWED.length === 0 ? [] : [{ files: RAW_SQL_ALLOWED, rules: { 'no-restricted-syntax': ['error', ...BASE_SELECTORS, ...LIBRARY_SELECTORS] } }]),
    ...(PROCEDURE_SELECTORS.length === 0 ? [] : [{ files: ROUTER_FILES, rules: { 'no-restricted-syntax': ['error', ...BASE_SELECTORS, ...LIBRARY_SELECTORS, ...RAW_SQL_SELECTORS, ...PROCEDURE_SELECTORS] } }]),
];

const coreRules = {
    'no-useless-constructor': 'error',
    'no-useless-return': 'error',
    'no-useless-call': 'error',
    'no-useless-rename': 'error',
    'no-duplicate-imports': 'off',
    eqeqeq: ['error', 'always'],
    'no-param-reassign': 'error',
    'prefer-const': 'error',
    'padding-line-between-statements': ['error', { blankLine: 'always', prev: ['function', 'class'], next: ['function', 'class'] }],
    'lines-between-class-members': ['error', 'always'],
    'no-empty': ['error', { allowEmptyCatch: false }],
    'no-restricted-syntax': ['error', ...BASE_SELECTORS],
};

const gspotRules = {
    'gspot/no-trivial-functions': ['error', { maxStatements: limits.trivialStatements }],
    'gspot/no-call-through': ['error', { allow: [] }],
    'gspot/no-trivial-files': 'error',
    'gspot/no-export-only-files': 'error',
    'gspot/no-exported-alias-constants': 'error',
    'gspot/no-index-imports': 'error',
    'gspot/no-single-file-folders': ['error', { allow: [
    "packages/npm/gspot"
] }],
    'gspot/no-prefix-collisions': ['error', { threshold: limits.prefixCollisions, allow: [
    "packages/eslint-plugin/src/rules/**",
    "packages/eslint-plugin/tests/rules/**",
    "docs/src"
] }],
    'gspot/header-comments-before-imports': 'error',
    'gspot/import-layout': 'error',
    'gspot/no-cross-folder-imports': ['error', { aliases: ALIASES }],
    'gspot/no-cross-project-imports': ['error', { scopes: [
    "packages/cli",
    "packages/eslint-plugin",
    "docs"
] }],
    'gspot/tests-directory-contents': ['error', { harnessDirectory: "tests/support" }],
    'gspot/registry-instance-only': 'error',
    'gspot/private-before-public': 'error',
    'gspot/types-placement': ['error', { typesDirectory: "types" }],
    'gspot/import-direction': ['error', { roles: {
    "types": [
        "types/**",
        "**/types/**"
    ],
    "tests": [
        "tests/**",
        "**/*.test.*",
        "**/*.spec.*",
        "**/__tests__/**"
    ],
    "harness": [
        "tests/support/**"
    ],
    "config": [
        "config/**"
    ],
    "env": [
        "packages/cli/src/platform/environment.ts"
    ],
    "runtime": [
        "src/**"
    ]
}, aliases: ALIASES }],
    'gspot/env-access-owner': ['error', { owners: [
    "packages/cli/src/platform/environment.ts"
] }],
    'gspot/no-reexports': 'error',
};

// sonarjs recommended is the base. no-empty-test-file is off because a test that registers its cases through a
// helper (ESLint's RuleTester) looks empty to it; vitest/expect-expect covers the same ground.
const sonarRules = {
    'sonarjs/no-empty-test-file': 'off',
    'sonarjs/cognitive-complexity': ['error', limits.cognitive],
    'sonarjs/no-identical-functions': ['error', limits.identicalFunctions],
    'sonarjs/no-all-duplicated-branches': 'error',
    'sonarjs/no-duplicated-branches': 'error',
    'sonarjs/no-identical-conditions': 'error',
    'sonarjs/no-identical-expressions': 'error',
    'sonarjs/no-element-overwrite': 'error',
    'sonarjs/no-empty-collection': 'error',
    'sonarjs/no-extra-arguments': 'error',
    'sonarjs/no-use-of-empty-return-value': 'error',
    'sonarjs/non-existent-operator': 'error',
    'sonarjs/no-gratuitous-expressions': 'error',
    'sonarjs/no-invariant-returns': 'error',
    'sonarjs/for-loop-increment-sign': 'error',
    'sonarjs/no-useless-increment': 'error',
    'sonarjs/no-unthrown-error': 'error',
    'sonarjs/no-collapsible-if': 'error',
    'sonarjs/no-nested-switch': 'error',
    'sonarjs/no-nested-template-literals': 'error',
    'sonarjs/no-redundant-boolean': 'error',
    'sonarjs/no-redundant-jump': 'error',
    'sonarjs/no-same-line-conditional': 'error',
    'sonarjs/no-small-switch': 'error',
    'sonarjs/no-unused-collection': 'error',
    'sonarjs/no-useless-catch': 'error',
    'sonarjs/prefer-single-boolean-return': 'error',
    'sonarjs/prefer-while': 'error',
    'sonarjs/prefer-object-literal': 'error',
    'sonarjs/no-nested-conditional': 'error',
    'sonarjs/no-inverted-boolean-check': 'error',
    'sonarjs/no-nested-functions': 'error',
    'sonarjs/no-parameter-reassignment': 'error',
    'sonarjs/no-commented-code': 'error',
    'sonarjs/no-dead-store': 'error',
    'sonarjs/prefer-immediate-return': 'error',
    'sonarjs/updated-loop-counter': 'error',
    'sonarjs/no-equals-in-for-termination': 'error',
    'sonarjs/no-redundant-assignments': 'error',
};

// unicorn recommended is the base. prevent-abbreviations, name-replacements and filename-case are the naming
// engine's job; no-null is off because null is what the platform APIs return; single-line-block-comment-style is
// off because a one-line JSDoc is the documented form; consistent-conditional-object-spread is off because its
// rewrite spreads a boolean, which TypeScript refuses; no-useless-undefined is off because noImplicitReturns needs
// the explicit return; import-style is off because the shape of an import is not a slop signal; prefer-ternary
// stays single-line only.
const unicornRules = {
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/name-replacements': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/no-null': 'off',
    'unicorn/single-line-block-comment-style': 'off',
    'unicorn/consistent-conditional-object-spread': 'off',
    'unicorn/no-useless-undefined': 'off',
    'unicorn/import-style': 'off',
    'unicorn/prefer-ternary': ['error', 'only-single-line'],
    'unicorn/expiring-todo-comments': ['error', { allowWarningComments: false }],
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-for-each': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/no-lonely-if': 'error',
};

const securityRules = {
    'security/detect-buffer-noassert': 'error',
    'security/detect-child-process': 'error',
    'security/detect-disable-mustache-escape': 'error',
    'security/detect-eval-with-expression': 'error',
    'security/detect-new-buffer': 'error',
    'security/detect-no-csrf-before-method-override': 'error',
    // detect-non-literal-regexp is off: it flags the constructor, not the input (D-67).
    'security/detect-non-literal-regexp': 'off',
    'security/detect-non-literal-require': 'error',
    'security/detect-possible-timing-attacks': 'error',
    'security/detect-pseudoRandomBytes': 'error',
    'security/detect-unsafe-regex': 'error',
    'security/detect-object-injection': 'off',
    'security/detect-non-literal-fs-filename': 'off',
};

const nodeRules = {
    'n/no-deprecated-api': 'error',
    'n/no-process-exit': 'error',
    'n/no-unsupported-features/node-builtins': ['error', { version: ">=22.0.0", allowExperimental: true }],
    'n/no-unsupported-features/es-builtins': ['error', { version: ">=22.0.0" }],
    'n/no-unsupported-features/es-syntax': 'off',
    'n/prefer-global/buffer': ['error', 'always'],
    'n/prefer-global/console': ['error', 'always'],
    'n/prefer-global/process': ['error', 'always'],
    'n/prefer-global/url': ['error', 'always'],
    'n/prefer-global/url-search-params': ['error', 'always'],
    'n/prefer-promises/dns': 'error',
    'n/prefer-promises/fs': 'error',
    'n/no-sync': 'off',
    'n/no-callback-literal': 'error',
    'n/no-new-require': 'error',
    'n/no-path-concat': 'error',
    'n/no-missing-import': 'off',
    'n/no-missing-require': 'off',
    'n/no-unpublished-import': 'off',
    'n/no-unpublished-require': 'off',
    'n/no-extraneous-import': 'off',
    'n/no-extraneous-require': 'off',
};

const jsdocRules = {
    'jsdoc/require-jsdoc': ['error', { publicOnly: true, require: { FunctionDeclaration: true, ArrowFunctionExpression: true, FunctionExpression: true, MethodDefinition: true } }],
    'jsdoc/require-description': 'error',
    'jsdoc/require-param': 'error',
    'jsdoc/require-param-description': 'error',
    'jsdoc/require-param-name': 'error',
    'jsdoc/require-param-type': 'off',
    'jsdoc/require-returns': 'error',
    'jsdoc/require-returns-description': 'error',
    'jsdoc/require-returns-type': 'off',
    'jsdoc/check-param-names': 'error',
    'jsdoc/check-tag-names': 'error',
    'jsdoc/check-types': 'off',
    'jsdoc/no-undefined-types': 'off',
    'jsdoc/valid-types': 'off',
    'jsdoc/no-types': 'error',
};

const regexpRules = {
    'regexp/no-super-linear-backtracking': 'error',
    'regexp/no-empty-alternative': 'error',
    'regexp/no-empty-capturing-group': 'error',
    'regexp/no-empty-character-class': 'error',
    'regexp/no-empty-group': 'error',
    'regexp/no-empty-lookarounds-assertion': 'error',
    'regexp/no-useless-assertions': 'error',
    'regexp/no-useless-backreference': 'error',
    'regexp/no-useless-character-class': 'error',
    'regexp/no-useless-dollar-replacements': 'error',
    'regexp/no-useless-lazy': 'error',
    'regexp/no-useless-quantifier': 'error',
    'regexp/no-useless-range': 'error',
    'regexp/no-lazy-ends': 'error',
    'regexp/no-optional-assertion': 'error',
    'regexp/no-invalid-regexp': 'error',
    'regexp/no-misleading-capturing-group': 'error',
    'regexp/no-contradiction-with-assertion': 'error',
    'regexp/strict': 'error',
};

const importRules = {
    'import-x/first': 'error',
    'import-x/newline-after-import': ['error', { count: 1 }],
    'import-x/no-cycle': ['error', { maxDepth: Infinity, ignoreExternal: true }],
    'import-x/no-self-import': 'error',
    'import-x/no-useless-path-segments': ['error', { noUselessIndex: false }],
    'import-x/no-empty-named-blocks': 'error',
    'import-x/no-duplicates': 'error',
    'import-x/exports-last': 'error',
};

const commentRules = {
    '@eslint-community/eslint-comments/require-description': 'error',
    '@eslint-community/eslint-comments/no-unused-disable': 'error',
};

// A pair of patterns in one list means both hold, so a pattern as wide as **/* still reaches code files only.
const importStyleOverrides = [
    {
        "files": [
            [
                "**/*",
                "**/*.{js,mjs,cjs,jsx,ts,tsx,mts,cts}"
            ]
        ],
        "rules": {
            "gspot/import-path-style": [
                "error",
                {
                    "style": "ts",
                    "internalPrefixes": [
                        "./",
                        "../",
                        "#cli/",
                        "#config/",
                        "#types/",
                        "#plugin/",
                        "#plugin-types/",
                        "#plugin-tests/",
                        "#tests/"
                    ]
                }
            ]
        }
    }
];

const runtimeOverrides = [
    { files: ["packages/npm/**"], languageOptions: { sourceType: 'commonjs', globals: { ...globals.node, ...globals.commonjs } }, rules: { 'unicorn/prefer-module': 'off', '@typescript-eslint/no-require-imports': 'off', 'unicorn/import-style': 'off' } },
];

const boundaryConfigs = [
];

const scopeAliasOverrides = [
    {
        "files": [
            "packages/cli/**/*.{js,mjs,cjs,jsx,ts,tsx,mts,cts}"
        ],
        "rules": {
            "gspot/no-cross-folder-imports": [
                "error",
                {
                    "aliases": {
                        "#cli/": "packages/cli/src/",
                        "#config/": "packages/cli/config/",
                        "#types/": "packages/cli/types/",
                        "#package": "packages/cli/package.json",
                        "#rules-lint/": "packages/cli/rules-lint/"
                    }
                }
            ],
            "gspot/import-direction": [
                "error",
                {
                    "roles": {
                        "types": [
                            "types/**",
                            "**/types/**"
                        ],
                        "tests": [
                            "tests/**",
                            "**/*.test.*",
                            "**/*.spec.*",
                            "**/__tests__/**"
                        ],
                        "harness": [
                            "tests/support/**"
                        ],
                        "config": [
                            "config/**"
                        ],
                        "env": [
                            "packages/cli/src/platform/environment.ts"
                        ],
                        "runtime": [
                            "src/**"
                        ]
                    },
                    "aliases": {
                        "#cli/": "packages/cli/src/",
                        "#config/": "packages/cli/config/",
                        "#types/": "packages/cli/types/",
                        "#package": "packages/cli/package.json",
                        "#rules-lint/": "packages/cli/rules-lint/"
                    },
                    "scope": "packages/cli"
                }
            ]
        }
    },
    {
        "files": [
            "packages/eslint-plugin/**/*.{js,mjs,cjs,jsx,ts,tsx,mts,cts}"
        ],
        "rules": {
            "gspot/no-cross-folder-imports": [
                "error",
                {
                    "aliases": {
                        "#plugin/": "packages/eslint-plugin/src/",
                        "#plugin-types/": "packages/eslint-plugin/types/",
                        "#plugin-tests/": "packages/eslint-plugin/tests/",
                        "#plugin-package": "packages/eslint-plugin/package.json"
                    }
                }
            ],
            "gspot/import-direction": [
                "error",
                {
                    "roles": {
                        "types": [
                            "types/**",
                            "**/types/**"
                        ],
                        "tests": [
                            "tests/**",
                            "**/*.test.*",
                            "**/*.spec.*",
                            "**/__tests__/**"
                        ],
                        "harness": [
                            "tests/support/**"
                        ],
                        "config": [
                            "config/**"
                        ],
                        "env": [
                            "packages/cli/src/platform/environment.ts"
                        ],
                        "runtime": [
                            "src/**"
                        ]
                    },
                    "aliases": {
                        "#plugin/": "packages/eslint-plugin/src/",
                        "#plugin-types/": "packages/eslint-plugin/types/",
                        "#plugin-tests/": "packages/eslint-plugin/tests/",
                        "#plugin-package": "packages/eslint-plugin/package.json"
                    },
                    "scope": "packages/eslint-plugin"
                }
            ]
        }
    }
];

export default [
    { ignores: [
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/coverage/**",
    ".gspot/**",
    "packages/cli/grammars/swift.wasm",
    "schema/**",
    "docs/public/schema/**"
] },
    { files: CODE, ...eslint.configs.recommended },
    { files: CODE, ...sonarjs.configs.recommended },
    { files: CODE, ...unicorn.configs.recommended },
    {
        files: CODE,
        plugins: { gspot, 'import-x': importX, jsdoc, n: nodePlugin, regexp, security, boundaries, '@eslint-community/eslint-comments': eslintComments },
        linterOptions: { reportUnusedDisableDirectives: 'error' },
        languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: { ...globals.node, ...globals.es2024 } },
        settings: { node: { version: ">=22.0.0" }, gspot: { root } },
        rules: { ...sizeRules, ...coreRules, ...gspotRules, ...sonarRules, ...unicornRules, ...securityRules, ...nodeRules, ...jsdocRules, ...regexpRules, ...importRules, ...commentRules },
    },
    { files: JAVASCRIPT, rules: { 'no-unused-vars': ['error', { args: 'none', argsIgnorePattern: '^_', varsIgnorePattern: '^_', destructuredArrayIgnorePattern: '^_' }] } },
    ...importStyleOverrides,
    ...scopeAliasOverrides,
    ...runtimeOverrides,
    ...boundaryConfigs,
    ...tseslint.configs.strictTypeChecked.map((entry) => ({ ...entry, files: TYPESCRIPT })),
    {
        files: TYPESCRIPT,
        languageOptions: { parserOptions: { projectService: true, tsconfigRootDir: root } },
        rules: {
            '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
            '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports', fixStyle: 'separate-type-imports' }],
            '@typescript-eslint/consistent-type-exports': ['error', { fixMixedExportsWithInlineTypeSpecifier: true }],
            '@typescript-eslint/switch-exhaustiveness-check': ['error', { considerDefaultExhaustiveForUnions: true }],
            '@typescript-eslint/prefer-readonly': 'error',
            '@typescript-eslint/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/no-non-null-assertion': 'error',
            '@typescript-eslint/no-floating-promises': ['error', { ignoreVoid: false }],
            '@typescript-eslint/no-unused-vars': ['error', { args: 'none', argsIgnorePattern: '^_', varsIgnorePattern: '^_', destructuredArrayIgnorePattern: '^_' }],
            '@typescript-eslint/no-require-imports': 'off',
            '@typescript-eslint/strict-boolean-expressions': 'error',
            '@typescript-eslint/explicit-module-boundary-types': 'error',
            '@typescript-eslint/no-unnecessary-condition': 'error',
            '@typescript-eslint/no-unnecessary-type-assertion': 'error',
            '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error',
            '@typescript-eslint/only-throw-error': 'error',
            '@typescript-eslint/prefer-optional-chain': 'error',
            '@typescript-eslint/no-magic-numbers': ['error', { ignoreEnums: true, ignoreArrayIndexes: true, ignoreDefaultValues: true, ignoreReadonlyClassProperties: true, ignoreTypeIndexes: true, ignore: [-1, 0, 1, 2] }],
            '@typescript-eslint/ban-ts-comment': ['error', { 'ts-expect-error': 'allow-with-description', 'ts-ignore': true, 'ts-nocheck': true, minimumDescriptionLength: 10 }],
            'sonarjs/no-duplicate-in-composite': 'error',
            'sonarjs/redundant-type-aliases': 'error',
            'no-unused-vars': 'off',
        },
    },
    ...tseslint.configs.disableTypeChecked.files ? [{ ...tseslint.configs.disableTypeChecked, files: JAVASCRIPT }] : [],
    { files: TESTS, rules: { '@typescript-eslint/no-non-null-assertion': 'off', '@typescript-eslint/no-magic-numbers': 'off', '@typescript-eslint/explicit-module-boundary-types': 'off', '@typescript-eslint/no-unsafe-assignment': 'off' } },

    ...librarySelectorBlocks,
    { files: CODE, ignores: [...TESTS, ...SCRIPTS], rules: { 'no-console': 'error' } },
    {
        files: SCRIPTS,
        rules: { 'n/no-process-exit': 'off', 'no-unused-vars': ['error', { args: 'all', argsIgnorePattern: '^_', varsIgnorePattern: '^_' }], 'gspot/no-single-file-folders': 'off' },
    },
    {
        files: TESTS,
        rules: {
            'jsdoc/require-jsdoc': 'off',
            'jsdoc/require-param': 'off',
            'jsdoc/require-returns': 'off',
            'jsdoc/require-description': 'off',
            'jsdoc/require-param-description': 'off',
            'jsdoc/require-returns-description': 'off',
            'gspot/no-trivial-files': 'off',
            'max-lines-per-function': 'off',
            'max-lines': 'off',
            'max-statements': 'off',
            'max-nested-callbacks': ['error', limits.nestedCallbacks + 2],
            'gspot/no-harness-barrel-imports': ['error', { barrels: [
    "#plugin-tests",
    "#tests"
] }],
        },
    },
    { files: ['**/package.json'], ...packageJson.configs.recommended },
    { files: CODE, ...prettierConfig },
];
