export const GENERATED_HEADERS = [
    '# Generated by gspot 1.2.3 from gspot.toml.\n',
    '// Generated by gspot 2.0.0 from gspot.toml.\n',
    '-- Generated by gspot 1.2.3 from gspot.toml.\n',
    '<!-- Generated by gspot 1.2.3 from gspot.toml. -->\n',
    '<!--\n  Generated by gspot 1.2.3 from gspot.toml.\n-->\n',
    '#!/bin/sh\r\n# Generated by gspot 1.2.3 from gspot.toml.\r\n',
    '#!/bin/sh\n\n# Generated by gspot 1.2.3 from gspot.toml.\n',
    ' \n { "_gspot" : "Generated by gspot 1.2.3" }',
];

export const AUTHORED_HEADERS = [
    '',
    'export const text = "Generated by gspot 1.2.3";\n',
    '{"setting":true,"_gspot":"Generated by gspot 1.2.3"}',
    '# Authored comment\nline\nline\n# Generated by gspot 1.2.3\n',
    '// Generated by another tool 1.2.3\n',
];
