// The literal values generation reads: names, patterns, limits, and tables.
import type { HookName } from '#cli/types/generation.ts';

export const TRAILING_STAR = /\*$/u;
export const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);
export const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);
export const HTML_EXTENSIONS = new Set(['.md', '.html']);
export const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;
export const GENERATED_HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;
export const HEADER_LINES_CHECKED = 3;
export const GENERATED_HEADER_LINES = ['Generated by gspot {{version}} from gspot.toml. Regenerate: gspot apply.'];
export const CHECKOUT = 'actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5';
export const MISE = 'jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566';
export const SARIF = 'github/codeql-action/upload-sarif@df5a14dc28094dc936e103b37d749c6628682b60';
export const UPLOAD = 'actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02';
export const DOWNLOAD = 'actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093';
export const CACHE = 'actions/cache@5a3ec84eff668545956fd18022155c47e93e2684';
export const RELEASES = 'https://github.com/stefanionescu/gspot/releases/download';
export const RUNNERS: Record<string, string> = { ubuntu: 'ubuntu-24.04', macos: 'macos-15', windows: 'windows-2025' };
/** The days a release must be public before Bun installs it when the policy names no age. */
export const DEFAULT_RELEASE_AGE_DAYS = 7;
/** The seconds in one day, for the age Bun reads. */
export const SECONDS_PER_DAY = 86_400;
export const PACKAGE_JSON_INDENT = 4;
export const LEADING_NEWLINES = /^\n+/u;
export const BARE_KEY = /^[\w-]+$/u;
export const STYLE_ASSETS = 'packages/cli/configurations/policy/prose/styles/gspot/';
export const MAX_LINE = /^max: \d+$/mu;
export const LONGER_THAN = /longer than \d+/u;
// Line breaks and extglob groups, which EditorConfig sections cannot express.
export const UNREPRESENTABLE_SELECTOR = /[\r\n]|[!+?*@]\(/u;
export const LEADING_GLOBSTARS = /^(?:\*\*\/)+/u;
export const GLOB_GROUPING = /[{}()]/u;
export const PATH = '.pre-commit-config.yaml';
export const GENERATED_JSON_KEY = '_gspot';
export const TARGET_PLACEHOLDER = /\{target(?:_json)?\}/gu;
export const HOOK_HEADER = '# Written by gspot. Run `gspot uninstall` to remove.';
export const HOOK_ARGS: Record<HookName, string> = {
    'pre-commit': 'check --staged',
    'pre-push': 'check --push -- "$@"',
    'commit-msg': 'check --stage message --message-file "$1"',
};
export const RUNNER_EXEC: Record<string, string> = {
    mise: 'mise exec -- gspot',
    bun: 'bun run --no-install gspot',
    npm: 'npm exec --no -- gspot',
    pnpm: 'pnpm exec gspot',
    yarn: 'yarn exec gspot',
};
