// gspot declare
import type { Command } from 'commander';
import { printCommand } from '#cli/commands/print-result.ts';
import { declareCommand } from '#cli/policy/declare-command.ts';
import { directoryOf, textEntry } from '#cli/commands/flags.ts';

/**
 * Registers declare.
 * @param program the commander program
 */
export function registerDeclare(program: Command): void {
    program
        .command('declare <glob...>')
        .description('Say what a path is: generated by a command, or vendored')
        .option('--produced-by <command>', 'The command that regenerates the files')
        .option('--vendored', 'Upstream source kept in the tree')
        .option('--reason <text>', 'Why; required for vendored paths')
        .option('--remove', 'Delete the matching entry instead')
        .option('--dry-run', 'Print what would be written and write nothing')
        .action(async (paths: string[], flags: Record<string, unknown>, command: Command) => {
            const global = command.optsWithGlobals();
            await printCommand(
                () =>
                    declareCommand({
                        cwd: directoryOf(global),
                        paths,
                        vendored: flags['vendored'] === true,
                        remove: flags['remove'] === true,
                        isDryRun: flags['dryRun'] === true,
                        ...textEntry(flags, 'producedBy', 'producedBy'),
                        ...textEntry(flags, 'reason', 'reason'),
                    }),
                global,
            );
        });
}
