// gspot declare
import type { Command } from 'commander';

import { emit } from '#cli/commands/emit.ts';
import { declareCommand } from '#cli/policy/commands.ts';

/** Registers declare. */
export function registerDeclare(program: Command): void {
    program
        .command('declare <glob...>')
        .description('Say what a path is: generated by a command, or vendored')
        .option('--produced-by <command>', 'The command that regenerates the files')
        .option('--vendored', 'Upstream source kept in the tree')
        .option('--reason <text>', 'Why; required for vendored paths')
        .option('--remove', 'Delete the matching entry instead')
        .option('--dry-run', 'Print what would be written and write nothing')
        .action(async (paths: string[], flags: Record<string, unknown>, command: Command) => {
            const global = command.optsWithGlobals() as Record<string, unknown>;
            await emit(
                () =>
                    declareCommand({
                        cwd: String(global['directory'] ?? process.cwd()),
                        paths,
                        vendored: Boolean(flags['vendored']),
                        remove: Boolean(flags['remove']),
                        dryRun: Boolean(flags['dryRun']),
                        ...(flags['producedBy'] ? { producedBy: String(flags['producedBy']) } : {}),
                        ...(flags['reason'] !== undefined ? { reason: String(flags['reason']) } : {}),
                    }),
                global,
            );
        });
}
