// These tools exercise package-manager and native adapters; manifests own the consumer-tool pins.
export const TEST_TOOLS = {
    pnpm: '9.9.0',
    yarn: '1.22.22',
    bats: '1.14.0',
    supabase: '2.72.7',
    'pipx:pytest': { version: '9.1.1', depends: ['uv'], uvx_args: '--with pytest-cov==7.1.0' },
};

export const PYTHON_TEST_TOOLS = ['ruff', 'sqlfluff'];

export const TEST_TOOLS_PATH = 'mise.test.toml';

export const TEST_TOOLS_HEADER =
    '# Generated by mise run pin:test-tools. Edit the manifests or scripts/config/test-tools.ts and regenerate.\n\n';
