// The built-in Cloudflare checks on a planted site, run in-process: each fires on its defect and accepts the correction.
import { join } from 'node:path';
import { chmodSync } from 'node:fs';
import { plantedCases } from '#tests/harness/planted/cases.ts';

const WRANGLER =
    '{\n    // The worker of the planted site.\n    "name": "planted",\n    "compatibility_date": "2026-01-15"\n}\n';

const TYPES = '// Generated by wrangler.\ninterface Env {}\n';
// A wrangler that answers its version and writes one fixed types file; the real one needs a Cloudflare account.
const FAKE_WRANGLER = `#!${process.execPath}\nif (process.argv.includes('--version')) console.log('4.0.0');\nelse await Bun.write(process.argv.at(-1), ${JSON.stringify(TYPES)});\n`;

plantedCases(
    'the cloudflare configuration',
    {
        kits: ['cloudflare'],
        modules: false,
        installs: false,
        files: {
            'package.json':
                '{\n    "name": "planted",\n    "private": true,\n    "devDependencies": { "wrangler": "4.0.0" }\n}\n',
            'node_modules/.bin/wrangler': FAKE_WRANGLER,
            'node_modules/wrangler/package.json': '{\n    "name": "wrangler",\n    "version": "4.0.0"\n}\n',
            'wrangler.jsonc': WRANGLER,
            _headers: '/*\n    X-Frame-Options: DENY\n',
            _redirects: '# Old addresses.\n/old /new 301\n/docs/* https://docs.planted.test/:splat 302!\n',
            'functions/hello.js':
                '// Says hello.\n\n/**\n * Answers every request.\n * @returns {Response} the greeting\n */\nexport function onRequest() {\n    return new Response("hello");\n}\n',
        },
        before: (root) => {
            chmodSync(join(root, 'node_modules/.bin/wrangler'), 0o755);
        },
    },
    [
        {
            check: 'cloudflare/wrangler-config',
            files: { 'wrangler.jsonc': '{\n    "name": "planted"\n}\n' },
            expected: { file: 'wrangler.jsonc', rule: 'compatibility-date', line: 1 },
        },
        {
            check: 'cloudflare/headers-syntax',
            files: { _headers: '    X-Frame-Options: DENY\n/*\n    Referrer-Policy no-referrer\n' },
            expected: { file: '_headers', rule: 'headers-syntax', line: 1 },
        },
        {
            check: 'cloudflare/redirects-syntax',
            files: { _redirects: '/old /new 999\n' },
            expected: { file: '_redirects', rule: 'redirects-syntax', line: 1 },
        },
        // A tracked types file that differs from what wrangler writes is stale. The planted wrangler is a shebang script.
        {
            check: 'cloudflare/env-types-fresh',
            files: { 'cloudflare-env.d.ts': '// Written by hand.\ninterface Env {}\n' },
            expected: { file: 'cloudflare-env.d.ts', rule: 'stale-types', line: 1 },
            platforms: ['darwin', 'linux'],
            corrected: { files: { 'cloudflare-env.d.ts': TYPES } },
        },
    ],
);
