export type Files = Readonly<Record<string, string>>

export const SHELL_SCRIPT = '#!/usr/bin/env bash\nset -euo pipefail\nprintf ok\n'

export function settingsFor(presets: readonly string[], tables = ''): string {
  return [
    'version = 1',
    'runner  = "mise"',
    '',
    'presets = [',
    ...presets.map((id) => `  ${JSON.stringify(id)},`),
    ']',
    '',
    tables,
  ].join('\n')
}

export const SYMBOL_EXCEPTION = `
[[exception]]
check  = "structure/trivial-function"
symbol = "forwards"
reason = "The public name is the stable one; the call it wraps is internal."
`

export const CONSUMER_CHECK = `
[[check]]
id       = "ops/migration-header"
paths    = ["sql/**/*.sql"]
command  = ["true"]
inspects = ["schema"]
stage    = "pre-commit"
fails_on = "exit-code"
`

export const HIDDEN_SQL: Files = {
  'gspot.toml': settingsFor(['language:sql', 'language:bash']),
  '.sqlfluffignore':
    '# Generated output only, or so the author believed.\n' +
    'build/\nreports/\ntmp/\nvendor/\nnode_modules/\ncoverage/\ndist/\nsql/\n',
  'sql/schema.sql': 'select 1;\n',
  'tests/suites/sql/rls/versioning.test.sql': 'select 2;\n',
  'ops/run.sh': SHELL_SCRIPT,
}

export const UNTOUCHED: Files = {
  'wherever/schema.sql': 'SELECT 1;\n',
  deploy: SHELL_SCRIPT,
  '.prettierrc.json': '{}\n',
  'CLAUDE.md': '# House rules\n\nAlways write tests first.\n',
}

const NULL_BYTE = String.fromCharCode(0)

export const MIXED_NATURES: Files = {
  'src/module.ts': 'export const value = 1\n',
  'src/logo.png': `PNG${NULL_BYTE}`,
  'src/types.ts': '// @generated by the codegen\nexport type A = 1\n',
}

export const TRACKED_SHAPES: Files = {
  'src/module.ts': 'export const value = 1\n',
  'notes.md': '# Notes\n',
  '.gitignore': 'ignored.txt\n',
  'ignored.txt': 'not part of the repository yet\n',
}
