import { join } from 'node:path';
import { parse as parseToml } from 'smol-toml';
import { describe, expect, test } from 'bun:test';
import { createFileTree, testdir } from 'testdirs';
import { cliSource } from '#tests/support/cli/sources.ts';
import { existsSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { publishInstalledFiles } from '#cli/tools/installed-files.ts';
import { openLifecycleOwner, readOwnership } from '#cli/lifecycle/ownership.ts';

const implementation = cliSource('lifecycle/ownership.ts');

test.each([false, true])(
    'TOML task ownership restores originals while retaining unrelated edits (%s)',
    async (edited) => {
        await using directory = await testdir();
        const original =
            '# Authored tasks\n[tasks]\nlint = "authored lint"\n[tasks.format]\n# Keep this description\ndescription = "Format the app"\nrun = ["authored format", "authored verify"]\n';
        await createFileTree(directory.path, { 'mise.toml': original });
        const owner = openLifecycleOwner(directory.path);
        try {
            const changes = [
                { path: ['tasks', 'lint'], value: 'gspot check' },
                { path: ['tasks', 'format', 'run'], value: 'gspot check --fix' },
            ];
            expect(owner.applyProposal(owner.proposeConfiguration('mise.toml', 'toml', changes, true))).toBe('changed');
            const installed = readFileSync(join(directory.path, 'mise.toml'), 'utf8');
            expect(installed).toContain('# Authored tasks');
            expect(installed).toContain('# Keep this description');
            expect(parseToml(installed)).toMatchObject({
                tasks: { lint: 'gspot check', format: { description: 'Format the app', run: 'gspot check --fix' } },
            });
            expect(owner.applyProposal(owner.proposeConfiguration('mise.toml', 'toml', changes))).toBe('unchanged');
            if (edited)
                writeFileSync(join(directory.path, 'mise.toml'), installed + '\n[env]\nAPP_MODE = "authored"\n');
            expect(owner.restore('mise.toml')).toBe('changed');
            const restored = readFileSync(join(directory.path, 'mise.toml'), 'utf8');
            expect(parseToml(restored)['tasks']).toStrictEqual(parseToml(original)['tasks']);
            // An authored edit survives the restore; without one the file is byte for byte the original.
            expect(parseToml(restored)['env']).toStrictEqual(edited ? { APP_MODE: 'authored' } : undefined);
            expect(restored === original).toBe(!edited);
        } finally {
            owner.close();
        }
    },
);

test('Windows permission projection supports repeated journal writes, idempotent replacement, and restoration', async () => {
    await using directory = await testdir();
    await createFileTree(directory.path, { 'config.txt': 'authored bytes' });
    const program = `
Object.defineProperty(process, 'platform', {value: 'win32'});
const {openLifecycleOwner} = await import(${JSON.stringify(implementation)});
let owner = openLifecycleOwner(process.cwd());
try {
    const first = owner.replace('config.txt', {bytes: Buffer.from('installed bytes'), mode: 0o755}, 'config', true);
    const repeated = owner.replace('config.txt', {bytes: Buffer.from('installed bytes'), mode: 0o755}, 'config');
    owner.close();
    owner = openLifecycleOwner(process.cwd());
    const restored = owner.restore('config.txt');
    console.log(JSON.stringify({first, repeated, restored, text: owner.read('config.txt').bytes.toString()}));
} finally {owner.close();}
`;
    const child = Bun.spawnSync([process.execPath, '-e', program], {
        cwd: directory.path,
        stdout: 'pipe',
        stderr: 'pipe',
    });
    expect(child.exitCode, child.stderr.toString()).toBe(0);
    expect(JSON.parse(child.stdout.toString())).toStrictEqual({
        first: 'changed',
        repeated: 'unchanged',
        restored: 'changed',
        text: 'authored bytes',
    });
    expect(readFileSync(join(directory.path, 'config.txt'), 'utf8')).toBe('authored bytes');
});

test('Python installation preserves runtime bytecode caches without publishing or pruning them', async () => {
    await using directory = await testdir();
    await using staged = await testdir();
    const cache = '.gspot/.venv/lib/__pycache__';
    await createFileTree(directory.path, { [`${cache}/unowned.pyc`]: 'runtime bytes' });
    await createFileTree(staged.path, {
        'lib/package.py': 'value = 2\n',
        'lib/package.pyc': 'packaged legacy bytecode',
        'lib/__pycache__/unowned.pyc': 'temporary generated bytecode',
        'lib/__pycache__/new.pyc': 'temporary new bytecode',
    });
    const owner = openLifecycleOwner(directory.path);
    try {
        owner.replace(
            `${cache}/recorded.pyc`,
            { bytes: Buffer.from('previous generated cache'), mode: 0o644 },
            'dependency',
        );
        writeFileSync(join(directory.path, `${cache}/recorded.pyc`), 'runtime changed cache');
        publishInstalledFiles(owner, staged.path, 'python');
        expect(owner.read('.gspot/.venv/lib/package.py')?.bytes.toString()).toBe('value = 2\n');
        expect(owner.read('.gspot/.venv/lib/package.pyc')?.bytes.toString()).toBe('packaged legacy bytecode');
        expect(owner.read(`${cache}/unowned.pyc`)?.bytes.toString()).toBe('runtime bytes');
        expect(owner.read(`${cache}/recorded.pyc`)?.bytes.toString()).toBe('runtime changed cache');
        expect(owner.read(`${cache}/new.pyc`)).toBeUndefined();
        publishInstalledFiles(owner, staged.path, 'python');
        expect(readOwnership(directory.path).installations).toBeUndefined();
    } finally {
        owner.close();
    }
});
if (process.platform !== 'win32')
    describe('lifecycle ownership', () => {
        test.each(['link', 'pruning'] as const)(
            'installation preserves every destination when %s conflicts, then installs corrected inputs',
            async (conflict) => {
                await using directory = await testdir();
                await using staged = await testdir();
                await createFileTree(staged.path, { 'package/bin/tool': 'new executable', '.bin/.keep': '' });
                symlinkSync('../package/bin/tool', join(staged.path, '.bin/tool'));
                const owner = openLifecycleOwner(directory.path);
                const target = '.gspot/node_modules/package/bin/tool';
                const obstructed =
                    conflict === 'link' ? '.gspot/node_modules/.bin/tool' : '.gspot/node_modules/obsolete';
                try {
                    owner.replace(target, { bytes: Buffer.from('installed executable'), mode: 0o644 }, 'dependency');
                    owner.replace(obstructed, { bytes: Buffer.from('installed file'), mode: 0o644 }, 'dependency');
                    writeFileSync(join(directory.path, obstructed), 'authored edit');
                    expect(() => {
                        publishInstalledFiles(owner, staged.path, 'npm');
                    }).toThrow('Preserved edited or unowned');
                    expect(owner.read(target)?.bytes.toString()).toBe('installed executable');
                    expect(owner.read(obstructed)?.bytes.toString()).toBe('authored edit');
                    writeFileSync(join(directory.path, obstructed), 'installed file');
                    publishInstalledFiles(owner, staged.path, 'npm');
                    expect(owner.read(target)?.bytes.toString()).toBe('new executable');
                    expect(readFileSync(join(directory.path, '.gspot/node_modules/.bin/tool'), 'utf8')).toBe(
                        'new executable',
                    );
                    publishInstalledFiles(owner, staged.path, 'npm');
                    // An obsolete owned file is pruned once its bytes are back; the linked tool stays in place.
                    expect(existsSync(join(directory.path, obstructed))).toBe(conflict === 'link');
                } finally {
                    owner.close();
                }
            },
        );
    });
