// The literal values repository reads: names, patterns, limits, and tables.
import type { ExistingTooling } from '#cli/types/repository/repository.ts';

export const NATURE_HEAD_BYTES = 2048;
export const FOREIGN_HOOK_DIRECTORIES = ['.githooks', '.husky', '.git-hooks'];
export const EXECUTABLE_BITS = 0o111;
export const NOT_REPOSITORY_CODE = 128;
export const DIRECTORY_FLAG = 0x80_00_00_00;
export const OFFSET_MASK = 0x7f_ff_ff_ff;
// Offsets and sizes from the PE/COFF specification, in bytes.
export const DOS_HEADER_SIZE = 64;
export const PE_OFFSET_FIELD = 60;
export const PE_SIGNATURE_SIZE = 4;
export const COFF_HEADER_SIZE = 20;
export const SECTION_COUNT_FIELD = 2;
export const OPTIONAL_HEADER_SIZE_FIELD = 16;
export const PE32_MAGIC = 0x1_0b;
export const PE32_PLUS_MAGIC = 0x2_0b;
export const PE32_DATA_DIRECTORIES = 96;
export const PE32_PLUS_DATA_DIRECTORIES = 112;
export const SIZE_OF_CODE_FIELD = 8;
export const SECTION_ALIGNMENT_FIELD = 32;
export const FILE_ALIGNMENT_FIELD = 36;
export const SIZE_OF_IMAGE_FIELD = 56;
export const SIZE_OF_HEADERS_FIELD = 60;
export const CHECKSUM_FIELD = 64;
export const DIRECTORY_ENTRY_SIZE = 8;
export const RESOURCE_DIRECTORY = 2;
export const CERTIFICATE_DIRECTORY = 4;
export const SECTION_SIZE = 40;
export const SECTION_VIRTUAL_SIZE_FIELD = 8;
export const SECTION_VIRTUAL_ADDRESS_FIELD = 12;
export const SECTION_RAW_SIZE_FIELD = 16;
export const SECTION_RAW_POINTER_FIELD = 20;
export const SECTION_CHARACTERISTICS_FIELD = 36;
export const READABLE_INITIALIZED_DATA = 0x40_00_00_40;
export const RESOURCE_TABLE_HEADER_SIZE = 16;
export const RESOURCE_NAMED_COUNT_FIELD = 12;
export const RESOURCE_ID_COUNT_FIELD = 14;
export const RESOURCE_ENTRY_SIZE = 8;
export const RESOURCE_ENTRY_TARGET_FIELD = 4;
export const RESOURCE_DATA_SIZE_FIELD = 4;
export const RCDATA_TYPE = 10;
export const WORD_SIZE = 4;
export const BYTE_ORDER_MARK = '\uFEFF';
export const KEY_QUOTES = ['"', '`'];
export const VALUE_QUOTES = ['"""', '`'];
export const LOCKFILE_V2 = 2;
export const LOCKFILE_V3 = 3;
export const LOCKFILE_VERSIONS = [LOCKFILE_V2, LOCKFILE_V3];
export const LOCKFILES: Record<string, string> = {
    'bun.lock': 'bun',
    'bun.lockb': 'bun',
    'package-lock.json': 'npm',
    'pnpm-lock.yaml': 'pnpm',
    'yarn.lock': 'yarn',
};
export const ENV_SUFFIX = '/env';
export const BANNER_BYTES = 1024;
export const GENERATED_ATTRIBUTES = new Set(['linguist-generated', 'linguist-generated=true']);
export const VENDORED_ATTRIBUTES = new Set(['linguist-vendored', 'linguist-vendored=true']);
export const BINARY_ATTRIBUTES = new Set(['-text', 'binary']);
export const DEPENDENCY_FOLDERS = [
    'node_modules',
    'bower_components',
    '.venv',
    'venv',
    'Pods',
    'DerivedData',
    '.build',
];
export const DIRECTIVE = /^([a-zA-Z-]+)=/u;
export const RULE_NAME = /^[a-zA-Z-]+$/u;
export const RULE_CODE = /^(?:SC)?\d+$/u;
// The words in a CI job name that say it lints.
export const LINT_WORDS = new Set(['lint', 'quality', 'gspot']);
// Two-word lint commands, and the package managers whose lint or gspot:check task counts.
export const LINT_PAIRS = new Set(['gspot check', 'biome check', 'ruff check']);
export const TASK_RUNNERS = new Set(['npm', 'pnpm', 'yarn', 'bun', 'mise']);
export const OTHER_CI_FILES = new Set([
    'Jenkinsfile',
    'bitbucket-pipelines.yml',
    '.circleci/config.yml',
    'azure-pipelines.yml',
    '.buildkite/pipeline.yml',
]);
export const MISE_FILES = ['mise.toml', '.mise.toml', '.mise/config.toml', '.tool-versions', 'mise.local.toml'];
export const RUNNER_LOCKS: { file: string; runner: ExistingTooling['runner'] }[] = [
    { file: 'bun.lock', runner: 'bun' },
    { file: 'bun.lockb', runner: 'bun' },
    { file: 'pnpm-lock.yaml', runner: 'pnpm' },
    { file: 'yarn.lock', runner: 'yarn' },
    { file: 'package-lock.json', runner: 'npm' },
    { file: 'package.json', runner: 'npm' },
    { file: 'uv.lock', runner: 'none' },
    { file: 'pyproject.toml', runner: 'none' },
];
export const REQUIREMENT_NAME_END = /[\s<>=!~;[@]/u;
export const SWIFT_PACKAGE_URL = /url:\s*"([^"]+)"/gu;

export const HOOK_FILES = ['pre-commit', 'pre-push', 'commit-msg'] as const;
export const LEFTHOOK_MIN_VERSION = '2.0.13';
export const NATIVE_HOOK_MARKERS: Record<string, string> = {
    lefthook: 'call_lefthook run ',
    husky: '. "$(dirname "$0")/h"',
    'simple-git-hooks': 'if [ "$SKIP_SIMPLE_GIT_HOOKS" = "1" ]; then',
    'pre-commit': '# File generated by pre-commit: https://pre-commit.com',
};
export const SIMPLE_GIT_HOOKS_DIRECTORY = '.gspot/integrations/simple-git-hooks';
export const EMPTY_FILES = 18_002;
export const NO_INPUTS = 18_003;
export const FILE_PREFIX_BYTES = 4096;
export const ENV_FILE_PATTERNS = ['.env', '.env.*', '.dev.vars', '.dev.vars.*'];
export const ENV_TEMPLATE_NAMES = ['.env.example', '.env.template', '.env.sample', '.dev.vars.example'];
/** How code reads an environment variable, by language; the first group is the key. */
export const ENV_READ_PATTERNS = [
    /process\.env\.([A-Z][A-Z0-9_]*)/gu,
    /process\.env\[['"]([A-Z][A-Z0-9_]*)['"]\]/gu,
    /os\.environ\[['"]([A-Z][A-Z0-9_]*)['"]\]/gu,
    /os\.environ\.get\(\s*['"]([A-Z][A-Z0-9_]*)['"]/gu,
    /os\.getenv\(\s*['"]([A-Z][A-Z0-9_]*)['"]/gu,
];
/** The files the environment reads are searched in. */
export const ENV_READ_EXTENSIONS = ['.ts', '.tsx', '.mts', '.cts', '.js', '.mjs', '.cjs', '.jsx', '.py'];
/** A key line in an environment file, trimmed: the key before the equals sign. */
export const ENV_KEY_LINE = /^(?:export )?([A-Z][A-Z0-9_]*)=/u;
export const EXTENSION_TAGS: Record<string, string[]> = {
    '.sh': ['shell', 'bash', 'text'],
    '.bash': ['shell', 'bash', 'text'],
    '.zsh': ['shell', 'zsh', 'text'],
    '.bats': ['shell', 'bats', 'text'],
    '.py': ['python', 'text'],
    '.pyi': ['python', 'pyi', 'text'],
    '.js': ['javascript', 'text'],
    '.mjs': ['javascript', 'text'],
    '.cjs': ['javascript', 'text'],
    '.jsx': ['javascript', 'jsx', 'text'],
    '.ts': ['typescript', 'text'],
    '.mts': ['typescript', 'text'],
    '.cts': ['typescript', 'text'],
    '.tsx': ['typescript', 'tsx', 'text'],
    '.vue': ['vue', 'source', 'text'],
    '.svelte': ['svelte', 'source', 'text'],
    '.swift': ['swift', 'text'],
    '.sql': ['sql', 'text'],
    '.pgsql': ['sql', 'text'],
    '.psql': ['sql', 'text'],
    '.md': ['markdown', 'text'],
    '.mdx': ['markdown', 'text'],
    '.json': ['json', 'text'],
    '.jsonc': ['json', 'jsonc', 'text'],
    '.json5': ['json', 'text'],
    '.yml': ['yaml', 'text'],
    '.yaml': ['yaml', 'text'],
    '.toml': ['toml', 'text'],
    '.ini': ['ini', 'text'],
    '.cfg': ['ini', 'text'],
    '.css': ['css', 'text'],
    '.scss': ['scss', 'text'],
    '.html': ['html', 'text'],
    '.htm': ['html', 'text'],
    '.xml': ['xml', 'text'],
    '.plist': ['plist', 'xml', 'text'],
    '.entitlements': ['plist', 'xml', 'text'],
    '.xcconfig': ['xcconfig', 'text'],
    '.xcstrings': ['json', 'xcstrings', 'text'],
    '.storyboard': ['xml', 'text'],
    '.xib': ['xml', 'text'],
    '.svg': ['svg', 'xml', 'text'],
    '.txt': ['text'],
    '.env': ['dotenv', 'text'],
    '.conf': ['text'],
    '.webmanifest': ['json', 'text'],
};
export const FILENAME_TAGS: Record<string, string[]> = {
    Dockerfile: ['dockerfile', 'text'],
    Makefile: ['makefile', 'text'],
    '.gitignore': ['text'],
    '.gitattributes': ['text'],
    '.editorconfig': ['ini', 'text'],
    '.nvmrc': ['text'],
    '.node-version': ['text'],
    '.python-version': ['text'],
    _headers: ['text'],
    _redirects: ['text'],
    LICENSE: ['text'],
    'LICENSE.md': ['markdown', 'text'],
    CODEOWNERS: ['text'],
};
export const SHEBANG_TAGS: Record<string, string[]> = {
    shell: ['shell', 'executable', 'text'],
    python: ['python', 'executable', 'text'],
    node: ['javascript', 'node', 'executable', 'text'],
};
