import { GENERATED_JSON_KEY, jsonText, type JsonFormat } from '#cli/generation/json-format.ts';
import { extensionOf } from '#cli/platform/paths.ts';
const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);
const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);

const HTML_EXTENSIONS = new Set(['.md', '.html']);

const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;

const HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;

const HEADER_LINES_CHECKED = 3;

const GENERATED_HEADER_LINES = ['Generated by gspot {{version}} from gspot.toml. Regenerate: gspot apply.'];

function commented(lines: string[], mark: string): string {
    const marked = lines.map((line) => `${mark} ${line}`).join('\n');
    return `${marked}\n`;
}

/**
 * The header lines for a version.
 * @param version the gspot version
 * @returns the two lines
 */
export function headerLines(version: string): string[] {
    return GENERATED_HEADER_LINES.map((line) => line.replaceAll('{{version}}', () => version));
}

/**
 * The header as a comment for a target path, or '' for JSON, which carries it as a key.
 * @param path the target path
 * @param version the gspot version
 * @returns the comment block ending in a newline, or ''
 */
export function headerFor(path: string, version: string): string {
    const extension = extensionOf(path);
    if (JSON_EXTENSIONS.has(extension)) return '';
    const lines = headerLines(version);
    if (SLASH_COMMENT_EXTENSIONS.has(extension)) return commented(lines, '//');
    if (HTML_EXTENSIONS.has(extension)) {
        const indented = lines.map((line) => `  ${line}`).join('\n');
        return `<!--\n${indented}\n-->\n`;
    }
    if (extension === '.sql') return commented(lines, '--');
    return commented(lines, '#');
}

/**
 * True when a text opens with the generated header (any version): in its first three lines, or as the first JSON key.
 * @param text a file's text
 * @returns whether gspot wrote it
 */
export function hasHeader(text: string): boolean {
    const lines = text.split('\n', HEADER_LINES_CHECKED + 1).slice(0, HEADER_LINES_CHECKED);
    if (lines.some((line) => HEADER_LINE.test(line))) return true;
    return JSON_HEADER.test(text) && text.includes(`"${GENERATED_JSON_KEY}"`);
}

/**
 * Puts the header into rendered JSON as the first key, formatted the way the repository's Prettier settings format it.
 * @param rendered the rendered JSON text
 * @param version the gspot version
 * @param format the print width and indent width
 * @returns the JSON text with the header key first
 */
export function jsonHeaderAdded(rendered: string, version: string, format: JsonFormat): string {
    const parsed = JSON.parse(rendered) as Record<string, unknown>;
    const ordered: Record<string, unknown> = { [GENERATED_JSON_KEY]: headerLines(version).join(' ') };
    for (const [key, value] of Object.entries(parsed)) if (key !== GENERATED_JSON_KEY) ordered[key] = value;
    return jsonText(ordered, format);
}
