import { BLOCK_IGNORES, TOKEN_IGNORES } from '#cli/configurations/vale.ts';
import { ALL_COMPILER_OPTIONS, RECOMMENDED_COMPILER_OPTIONS } from '#cli/checks/typescript/compiler-options.ts';
import type { EslintRuleBlock } from '#cli/generation/eslint.ts';
import { eslintRuleBlocks } from '#cli/generation/eslint.ts';
import type { EditorconfigOverride } from '#cli/generation/format.ts';
import { editorconfigOverrides, prettierConfig } from '#cli/generation/format.ts';
import { scopeIgnorePatterns } from '#cli/generation/ignore-patterns.ts';
import type { JsonFormat } from '#cli/generation/json-format.ts';
import { GENERATED_JSON_KEY, jsonText } from '#cli/generation/json-format.ts';
import { markdownlintRules } from '#cli/generation/markdownlint.ts';
import { styleNames } from '#cli/generation/vale-styles.ts';
import { readAsset } from '#cli/platform/assets.ts';
import { openConfinedRoot } from '#cli/platform/filesystem.ts';
import { extensionOf, toPosix } from '#cli/platform/paths.ts';
import type { MergedView } from '#cli/policy/merge.ts';
import type { Policy } from '#cli/policy/normalize.ts';
import type { ScopeSelection } from '#cli/policy/resolve.ts';
import { policyValue } from '#cli/policy/settings.ts';
import type { TrackedFile } from '#cli/repository/file-classification.ts';
import { readPackageManifest } from '#cli/repository/manifests.ts';
import { pathExpressions } from '#cli/repository/paths.ts';
import { getTsconfig } from '#cli/repository/tsconfig.ts';
import { Eta } from 'eta';
import { dirname, join, relative, resolve } from 'node:path';
import { TomlDate, stringify as stringifyToml } from 'smol-toml';
import { stringify as stringifyYaml } from 'yaml';

const GENERATED_HEADER_LINES = ['Generated by gspot {{version}} from gspot.toml. Regenerate: gspot apply.'];

const JSON_INDENT = 4;

const HEADER_LINES_CHECKED = 3;

const HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;

const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;

const LEADING_NEWLINES = /^\n+/u;

const TRAILING_STAR = /\*$/u;

const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);

const HTML_EXTENSIONS = new Set(['.md', '.html']);

export const eta = new Eta({ autoEscape: false, autoTrim: false, useWith: true, rmWhitespace: false, varName: 'it' });

const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);

function importTarget(target: unknown): string | undefined {
    if (typeof target === 'string') return target;
    if (typeof target !== 'object' || target === null) return undefined;
    return Object.values(target as Record<string, unknown>).find((value) => typeof value === 'string');
}

function packageAliases(root: string, prefix: string): Record<string, string> {
    const aliases: Record<string, string> = {};
    const files = openConfinedRoot(root);
    const path = `${prefix}package.json`;
    let imports: [string, unknown][];
    try {
        imports = files.stat(path) === undefined ? [] : Object.entries(readPackageManifest(root, path).imports ?? {});
    } finally {
        files.close();
    }
    for (const [pattern, target] of imports) {
        const found = importTarget(target);
        if (found === undefined) continue;
        if (!found.startsWith('./')) continue;
        const alias = found.slice(2).replace(TRAILING_STAR, '');
        aliases[pattern.replace(TRAILING_STAR, '')] = `${prefix}${alias}`;
    }
    return aliases;
}

function tsconfigAliases(root: string, prefix: string): Record<string, string> {
    const aliases: Record<string, string> = {};
    const path = join(root, prefix, 'tsconfig.json');
    const options = getTsconfig(root, path)?.options;
    if (options === undefined) return aliases;
    const paths = Object.entries(options.paths ?? {});
    const inheritedBase = options['pathsBasePath'];
    const base = options.baseUrl ?? (typeof inheritedBase === 'string' ? inheritedBase : dirname(path));
    for (const [pattern, targets] of paths) {
        const target = targets[0];
        if (target === undefined) continue;
        const alias = toPosix(relative(root, resolve(base, target))).replace(TRAILING_STAR, '');
        aliases[pattern.replace(TRAILING_STAR, '')] = alias;
    }
    return aliases;
}

function aliasesFor(root: string, scope: string): Record<string, string> {
    const prefix = scope === '' ? '' : `${scope}/`;
    return { ...packageAliases(root, prefix), ...tsconfigAliases(root, prefix) };
}

// Inherit authored resolution and file selection. A default input glob belongs to the repository,
// not the generated configuration directory.
function javascriptConfig(root: string, policy: Policy, target: string, scope: string): Record<string, unknown> {
    const config = getTsconfig(root, join(root, scope, 'jsconfig.json'));
    const prefix = toPosix(relative(dirname(target), scope || '.')) + '/';
    const defaults =
        config === undefined
            ? {
                  target: 'ES2022',
                  module: 'NodeNext',
                  moduleResolution: 'NodeNext',
                  skipLibCheck: true,
                  resolveJsonModule: true,
              }
            : {};
    return {
        ...(config === undefined ? {} : { extends: `${prefix}jsconfig.json` }),
        compilerOptions: { ...defaults, checkJs: true, allowJs: true, strict: true, noEmit: true },
        ...(config?.raw.files !== undefined || config?.raw.include !== undefined
            ? {}
            : {
                  include: ['js', 'mjs', 'cjs', 'jsx'].map((extension) => `${prefix}**/*.${extension}`),
              }),
        ...(config === undefined
            ? {
                  exclude: [
                      '**/node_modules/**',
                      '.gspot/**',
                      '**/eslint.config.mjs',
                      '**/eslint.config.js',
                      '**/eslint.config.cjs',
                      '**/dist/**',
                      '**/build/**',
                      '**/coverage/**',
                      '**/.build/**',
                      '**/DerivedData/**',
                      ...policy.declarations.flatMap((entry) => entry.paths),
                  ].map((path) => `${prefix}${path}`),
              }
            : {}),
    };
}

function commented(lines: string[], mark: string): string {
    const marked = lines.map((line) => `${mark} ${line}`).join('\n');
    return `${marked}\n`;
}

function toolNames(scopes: ScopeSelection[]): string[] {
    const names = scopes.flatMap((entry) =>
        entry.selected.flatMap((manifest) => manifest.tools.map((tool) => tool.name)),
    );
    return [...new Set(names)].toSorted((a, b) => a.localeCompare(b));
}

// The npm packages of the selected tools: a repository installs them to run them, and imports none of them.
function toolPackages(scopes: ScopeSelection[]): string[] {
    const names = scopes.flatMap((entry) =>
        entry.selected.flatMap((manifest) =>
            manifest.tools.flatMap((tool) => {
                const name = tool.installers['npm']?.name;
                return name === undefined ? [] : [name];
            }),
        ),
    );
    return [...new Set(names)].toSorted((a, b) => a.localeCompare(b));
}

function knipEntries(policy: Policy, scope: string): string[] {
    const layers = [
        { path: '', table: policy },
        ...Object.entries(policy.scopeTables)
            .filter(([path]) => path === scope || scope.startsWith(`${path}/`))
            .map(([path, table]) => ({ path, table })),
    ];
    return layers.flatMap(({ path, table }) => {
        const entries = (policyValue(table, 'tools.knip.entry')?.value ?? []) as string[];
        return entries.map((pattern) => {
            if (path === '') return pattern;
            return pattern.startsWith('!') ? `!${path}/${pattern.slice(1)}` : `${path}/${pattern}`;
        });
    });
}

function structuralRuleBlocks(scopes: ScopeSelection[]): EslintRuleBlock[] {
    const blocks: EslintRuleBlock[] = [];
    for (const selection of scopes.toSorted((a, b) => a.scope.path.length - b.scope.path.length)) {
        for (const [language, pattern] of [
            ['javascript', '**/*.{js,mjs,cjs,jsx}'],
            ['typescript', '**/*.{ts,tsx,mts,cts,vue,svelte}'],
        ] as const) {
            const maxStatements =
                selection.view.limit('trivial_statements', language) ?? selection.view.limit('trivial_statements');
            blocks.push({
                scope: selection.scope.path,
                ...pathExpressions([pattern]),
                rules: {
                    'gspot/no-trivial-files': ['error', { maxStatements }],
                    'gspot/no-trivial-functions': ['error', { maxStatements }],
                },
            });
        }
    }
    return blocks;
}

/**
 * The header lines for a version.
 * @param version the gspot version
 * @returns the two lines
 */
export function headerLines(version: string): string[] {
    return GENERATED_HEADER_LINES.map((line) => line.replaceAll('{{version}}', () => version));
}

/**
 * The header as a comment for a target path, or '' for JSON, which carries it as a key.
 * @param path the target path
 * @param version the gspot version
 * @returns the comment block ending in a newline, or ''
 */
export function headerFor(path: string, version: string): string {
    const extension = extensionOf(path);
    if (JSON_EXTENSIONS.has(extension)) return '';
    const lines = headerLines(version);
    if (SLASH_COMMENT_EXTENSIONS.has(extension)) return commented(lines, '//');
    if (HTML_EXTENSIONS.has(extension)) {
        const indented = lines.map((line) => `  ${line}`).join('\n');
        return `<!--\n${indented}\n-->\n`;
    }
    if (extension === '.sql') return commented(lines, '--');
    return commented(lines, '#');
}

/**
 * True when a text opens with the generated header (any version): in its first three lines, or as the first JSON key.
 * @param text a file's text
 * @returns whether gspot wrote it
 */
export function hasHeader(text: string): boolean {
    const lines = text.split('\n', HEADER_LINES_CHECKED + 1).slice(0, HEADER_LINES_CHECKED);
    if (lines.some((line) => HEADER_LINE.test(line))) return true;
    return JSON_HEADER.test(text) && text.includes(`"${GENERATED_JSON_KEY}"`);
}

/**
 * Puts the header into rendered JSON as the first key, formatted the way the repository's Prettier settings format it.
 * @param rendered the rendered JSON text
 * @param version the gspot version
 * @param format the print width and indent width
 * @returns the JSON text with the header key first
 */
export function jsonHeaderAdded(rendered: string, version: string, format: JsonFormat): string {
    const parsed = JSON.parse(rendered) as Record<string, unknown>;
    const ordered: Record<string, unknown> = { [GENERATED_JSON_KEY]: headerLines(version).join(' ') };
    for (const [key, value] of Object.entries(parsed)) if (key !== GENERATED_JSON_KEY) ordered[key] = value;
    return jsonText(ordered, format);
}

/**
 * The inputs every template sees.
 * @param root
 * @param policy
 * @param sourceFiles
 * @param scopes
 * @param version
 * @param selection the scope being rendered
 * @param fragments the fragment text other configurations contribute
 * @returns the template inputs
 */
export function templateInputs(
    root: string,
    policy: Policy,
    sourceFiles: TrackedFile[],
    scopes: ScopeSelection[],
    selection: ScopeSelection,
    version: string,
    fragments = '',
): TemplateInputs {
    const { view } = selection;
    const files = (extension: string): string[] =>
        sourceFiles
            .filter((file) => file.path.endsWith(extension) && file.nature === 'source')
            .map((file) => file.path);
    return {
        javascriptConfig: (targetPath) => javascriptConfig(root, policy, targetPath, selection.scope.path),
        prettierConfig: (targetPath) => prettierConfig(policy, targetPath, view.extra('prettier')),
        markdownlintRules: markdownlintRules(view),
        scopeIgnorePatterns,
        editorconfigOverrides: () => editorconfigOverrides(policy),
        eslintPolicy: [...structuralRuleBlocks(scopes), ...eslintRuleBlocks(policy)],
        isAll: policy.level === 'all',
        typescriptOptions: policy.level === 'all' ? ALL_COMPILER_OPTIONS : RECOMMENDED_COMPILER_OPTIONS,
        prose: {
            styles: styleNames(),
            blockIgnores: BLOCK_IGNORES,
            tokenIgnores: TOKEN_IGNORES,
        },
        version: version,
        scope: selection.scope.path,
        scopes: scopes
            .filter((entry) => entry.scope.path !== '')
            .map((entry) => ({
                path: entry.scope.path,
                configurations: entry.selected.map((manifest) => manifest.configuration.name),
            })),
        configurationScopes: (configuration) =>
            scopes
                .filter((entry) => entry.view.configurations.includes(configuration))
                .toSorted(
                    (left, right) =>
                        left.scope.path.split('/').length - right.scope.path.split('/').length ||
                        left.scope.path.localeCompare(right.scope.path),
                )
                .map((entry) => ({ path: entry.scope.path, settings: entry.view.settings })),
        configurations: view.configurations,
        policy: policy,
        view,
        format: view.format,
        settings: view.settings,
        fragments,
        tool: view.tool,
        entryFiles: (scope) => knipEntries(policy, scope),
        limit: view.limit,
        rulesOff: view.rulesOff,
        ignoresFor: view.ignoresFor,
        extra: view.extra,
        json: (value, indent = JSON_INDENT) =>
            JSON.stringify(value, null, indent)
                .replaceAll('\u{2028}', String.raw`\u2028`)
                .replaceAll('\u{2029}', String.raw`\u2029`),
        toml: stringifyToml,
        yaml: stringifyYaml,
        tomlDate: TomlDate,
        // Repository-wide output includes nested configurations. The configuration owner narrows per-scope output.
        has: (configuration) =>
            view.configurations.includes(configuration) ||
            (selection.scope.path === '' &&
                scopes.some((entry) =>
                    entry.selected.some((manifest) => manifest.configuration.name === configuration),
                )),
        importAliases: (scope) => aliasesFor(root, scope),
        tools: toolNames(scopes),
        toolPackages: toolPackages(scopes),
        files,
        header: headerFor('x.toml', version),
        headerLines: headerLines(version),
    };
}

/**
 * Renders a configuration template asset to the final text of a target, header included unless the target's reader refuses unknown keys.
 * @param templatePath the asset path of the template
 * @param targetPath the path the text is written to
 * @param inputs the template inputs
 * @param isHeaderWanted false for a reader that refuses the header key or comment
 * @returns the text to write
 */
export function emitTarget(
    templatePath: string,
    targetPath: string,
    inputs: TemplateInputs,
    isHeaderWanted = true,
): string {
    const rendered = eta.renderString(readAsset(templatePath), { ...inputs, targetPath });
    if (JSON_EXTENSIONS.has(extensionOf(targetPath))) {
        const format = { width: inputs.format.print_width, indent: inputs.format.indent_width };
        if (!isHeaderWanted) return jsonText(JSON.parse(rendered), format);
        return jsonHeaderAdded(rendered, inputs.version, format);
    }
    const body = rendered.replace(LEADING_NEWLINES, '').trimEnd() + '\n';
    if (!isHeaderWanted) return body;
    return `${headerFor(targetPath, inputs.version)}${body}`;
}

export type TemplateInputs = {
    markdownlintRules: Record<string, unknown>;
    targetPath?: string;
    scopeIgnorePatterns: (patterns: string[], scope: string) => string[];
    javascriptConfig: (targetPath: string) => Record<string, unknown>;
    prettierConfig: (targetPath: string) => Record<string, unknown>;
    editorconfigOverrides: () => EditorconfigOverride[];
    eslintPolicy: EslintRuleBlock[];
    isAll: boolean;
    typescriptOptions: Record<string, boolean>;
    prose: { blockIgnores: string[]; tokenIgnores: string[]; styles: string[] };
    version: string;
    scope: string;
    scopes: { path: string; configurations: string[] }[];
    configurationScopes: (configuration: string) => { path: string; settings: Record<string, unknown> }[];
    configurations: string[];
    policy: Policy;
    view: MergedView;
    format: MergedView['format'];
    settings: Record<string, unknown>;
    fragments: string;
    tool: (name: string) => Record<string, unknown>;
    entryFiles: (scope: string) => string[];
    limit: (key: string, language?: string) => number | undefined;
    rulesOff: (check: string) => string[];
    ignoresFor: MergedView['ignoresFor'];
    extra: (name: string) => Record<string, unknown> | undefined;
    json: (value: unknown, indent?: number) => string;
    toml: (value: Record<string, unknown>) => string;
    yaml: (value: Record<string, unknown>) => string;
    tomlDate: new (value: string) => Date;
    has: (configuration: string) => boolean;
    files: (extension: string) => string[];
    importAliases: (scope: string) => Record<string, string>;
    tools: string[];
    /** The npm package of every selected tool that has one. */
    toolPackages: string[];
    header: string;
    headerLines: string[];
};
