import { createRuleTester } from '#tests/harness/rule-tester.ts';
import { noTrivialFiles } from '#plugin/rules/no-trivial-files.ts';

createRuleTester().run('no-trivial-files', noTrivialFiles, {
    valid: [
        {
            code: 'export * from "./owner";',
            filename: '/repo/src/index.ts',
            options: [{ allowIndex: true }],
        },
        {
            code: 'export { value } from "./owner";',
            filename: '/repo/src/nested/index.ts',
            options: [{ allowIndex: true }],
        },
        {
            code: 'export * as owner from "./owner";',
            filename: '/repo/src/nested/index.js',
            options: [{ allowIndex: true }],
        },
        'export class Settings { constructor(public enabled: boolean) {} }',
        'export class Settings { constructor(enabled: boolean) { this.enabled = enabled; } }',
        {
            code: 'export function schema(enabled) { if (enabled) return { enabled }; return owner; }',
            options: [{ maxStatements: 5 }],
        },
        'export function schema(properties) { return { type: "object", properties }; }',
        'export function schema(properties) { return configure({ type: "object", properties }); }',
        'export function select(items) { return items.map(item => ({ id: item.id })); }',
        'export const formats = entries.flatMap(entry => entry.format === undefined ? [] : [[entry.extension, entry.format]]);',
        'export function argumentsFor(names) { return ["run", ...names]; }',
        'export function heading(title) { return `# ${title}`; }',
        'export function work() { first(); second(); third(); }',
        'export function work(items) { return items.map(item => { first(item); second(item); return item; }); }',
        'export function isText(value: unknown): value is string { return typeof value === "string"; }',
        'export function assertText(value: unknown): asserts value is string { if (typeof value !== "string") throw new Error(); }',
        'export const schema = z.object({ name: z.string() });',
        'export interface Settings { name: string; }',
        'export const settings = { enabled: true };',
        'export default ({ enabled: true } satisfies Settings);',
        'export default ({ enabled: true } as Settings)!;',
        'class Settings { enabled = true; }',
        'class Worker { run() { first(); second(); third(); } }',
        'export type Settings = { enabled: boolean };',
        'import type { z } from "zod"; import type { schema } from "./schema"; export type Settings = z.infer<typeof schema>;',
        'await configure({ enabled: true });',
        'configure({ enabled: true }).start();',
        'new Configuration({ enabled: true });',
        'defineProps<{ name: string }>();',
        'export const schema = define<{ enabled: boolean; paths: string[] }>();',
    ],
    invalid: [
        'export function schema() { return owner.schema; }',
        'export function schema(properties) { return configure(properties); }',
        'export function heading() { return `constant`; }',
        'export { value } from "./owner";',
        'import { run } from "./owner"; run();',
        'import { run } from "./owner"; export const alias = run;',
        'export function run() { return owner(); }',
        'export const callback = () => 1;',
        'export function work(items) { return items.map(item => owner(item)); }',
        'class A { method() { return 1; } }',
        'class Settings { constructor(enabled) {} }',
        'defineProps<ExistingProps>();',
        'defineProps<{}>();',
        'export default (owner as Owner)!;',
        'export default (owner satisfies Owner);',
        'export type Alias = Owner;',
        'export type Alias<T> = Owner<T>;',
        'interface Empty {}',
        'class Empty { value = owner; }',
        'await run();',
        'configure().start();',
        'new Owner(...args);',
        'declare function run(): void;',
        'export * from "./owner";',
        ';',
    ].map((code) => ({ code, errors: [{ messageId: 'trivial' as const }] })),
});
