import { join } from 'node:path';
import { rejects } from 'node:assert/strict';
import { gitOutput } from '#tests/harness/git.ts';
import { test, expect, describe } from 'bun:test';
import { testdir, createFileTree } from 'testdirs';
import { readRepository } from '#cli/repository/read.ts';
import { headerFor, addJsonHeader } from '#cli/generation/headers.ts';
import { rmSync, mkdirSync, unlinkSync, symlinkSync, readFileSync, writeFileSync } from 'node:fs';

import {
    GENERATED_HEADER_PATHS,
    ATTRIBUTE_CLEARED_KINDS,
    ATTRIBUTE_PRECEDENCE_FILES,
    ATTRIBUTE_PRECEDENCE_KINDS,
} from '#tests/config/cli/repository/kinds.ts';

describe('kinds', () => {
    test('declarations win, then .gitattributes, then banners, then vendored directories, then the sniff', async () => {
        await using sandbox = await testdir();
        await createFileTree(sandbox.path, {
            '.gitattributes': 'generated/* linguist-generated\nassets/** -text\n',
            'types.ts': '// This file was automatically generated\nexport type A = 1;\n',
            'generated/x.ts': 'export const x = 1;\n',
            'vendor/lib.js': 'x',
            'assets/a.bin': 'x',
            'src/a.ts': 'export const a = 1;\n',
        });
        const declarations = [{ paths: ['src/a.ts'], generator: 'gen', kind: 'generated' as const }];
        const declared = await readRepository(sandbox.path, declarations, [], []);
        expect(declared.files.find((file) => file.path === 'src/a.ts')).toMatchObject({
            kind: 'generated',
            kindSource: 'generated',
            producedBy: 'gen',
        });
        const repository = await readRepository(sandbox.path, [], [], []);
        const files = new Map(repository.files.map((file) => [file.path, file]));
        expect(files.get('generated/x.ts')?.kindSource).toBe('.gitattributes');
        expect(files.get('types.ts')?.kind).toBe('generated');
        expect(files.get('vendor/lib.js')?.kind).toBe('vendored');
        expect(files.get('assets/a.bin')?.kind).toBe('binary');
        expect(files.get('src/a.ts')?.kind).toBe('source');
    });

    test('readRepository lists files without git through the gitignore walk', async () => {
        await using sandbox = await testdir();
        await createFileTree(sandbox.path, {
            '.gitignore': 'ignored/\n',
            'ignored/x.txt': 'x',
            'kept.txt': 'x',
        });
        const repo = await readRepository(sandbox.path, [], [], []);
        expect(repo.hasGit).toBe(false);
        expect(repo.files.map((file) => file.path)).toStrictEqual(['.gitignore', 'kept.txt']);
        expect(repo.scopes[0]?.path).toBe('');
    });
});

test('an @generated marker in a comment line makes a file generated, and the bare word does not', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, {
        'marked.ts': '/**\n * @generated by the schema compiler\n */\nexport const a = 1;\n',
        'marked.py': '# @generated\nA = 1\n',
        'named.ts': 'export const MARKERS = [/@generated\\b/u];\n',
    });
    const repository = await readRepository(sandbox.path, [], [], []);
    const kinds = Object.fromEntries(repository.files.map((file) => [file.path, file.kind]));
    expect(kinds).toStrictEqual({ 'marked.py': 'generated', 'marked.ts': 'generated', 'named.ts': 'source' });
});

test('a license text is vendored, and a source file named like one stays source', async () => {
    await using sandbox = await testdir();
    const licenses = ['LICENSE', 'LICENSE.md', 'LICENSE-MIT', 'COPYING.txt', 'LICENCE.rst', 'NOTICE', 'NOTICE.txt'];
    const sources = ['license-locks.test.ts', 'license.ts', 'licenses.json', 'notice.py'];
    await createFileTree(sandbox.path, Object.fromEntries([...licenses, ...sources].map((path) => [path, 'x\n'])));
    const repository = await readRepository(sandbox.path, [], [], []);
    const kinds = Object.fromEntries(repository.files.map((file) => [file.path, file.kind]));
    expect(kinds).toStrictEqual({
        ...Object.fromEntries(licenses.map((path) => [path, 'vendored'])),
        ...Object.fromEntries(sources.map((path) => [path, 'source'])),
    });
});

test('each repository read reads current attributes', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, { 'source.ts': 'export {};\n' });
    const before = await readRepository(sandbox.path, [], [], []);
    expect(before.files[0]!.kind).toBe('source');
    writeFileSync(join(sandbox.path, '.gitattributes'), '*.ts linguist-generated\n');
    const after = await readRepository(sandbox.path, [], [], []);
    expect(after.files.find((file) => file.path === 'source.ts')!.kind).toBe('generated');
    expect(before.files[0]!.kind).toBe('source');
});

test('an unreadable attributes file cannot become an empty rule set', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, { 'source.ts': 'export {};\n' });
    mkdirSync(join(sandbox.path, '.gitattributes'));
    await rejects(readRepository(sandbox.path, [], [], []), {
        code: 'EISDIR',
    });
    rmSync(join(sandbox.path, '.gitattributes'), { recursive: true });
    writeFileSync(join(sandbox.path, '.gitattributes'), '*.ts linguist-generated\n');
    const repository = await readRepository(sandbox.path, [], [], []);
    expect(repository.files.find((file) => file.path === 'source.ts')).toMatchObject({
        kind: 'generated',
        kindSource: '.gitattributes',
    });
});

test('repository inventory recognizes every generated header format outside the private directory', async () => {
    await using sandbox = await testdir();
    const version = '1.2.3';
    const files = Object.fromEntries(
        GENERATED_HEADER_PATHS.map((path) => [
            path,
            path.endsWith('.json')
                ? addJsonHeader('{"setting":true}', version, { width: 100, indent: 2 })
                : `${headerFor(path, version)}content\n`,
        ]),
    );
    await createFileTree(sandbox.path, files);
    const repository = await readRepository(sandbox.path, [], [], []);
    expect(repository.files.map(({ path, kind, kindSource }) => ({ path, kind, kindSource }))).toStrictEqual(
        GENERATED_HEADER_PATHS.toSorted((left, right) => left.localeCompare(right)).map((path) => ({
            path,
            kind: 'generated',
            kindSource: 'banner',
        })),
    );
});

test('linked authored attributes classify files inside the root and reject an external target', async () => {
    await using sandbox = await testdir();
    await using outside = await testdir();
    const attributes = 'generated/** linguist-generated\n';
    await createFileTree(sandbox.path, {
        'settings/attributes': attributes,
        'generated/source.ts': 'export {};\n',
    });
    await createFileTree(outside.path, { attributes });
    symlinkSync('settings/attributes', join(sandbox.path, '.gitattributes'));
    const repository = await readRepository(sandbox.path, [], [], []);
    expect(repository.files.find((file) => file.path === 'generated/source.ts')).toMatchObject({
        kind: 'generated',
        kindSource: '.gitattributes',
    });
    rmSync(join(sandbox.path, '.gitattributes'));
    symlinkSync(join(outside.path, 'attributes'), join(sandbox.path, '.gitattributes'));
    await rejects(readRepository(sandbox.path, [], [], []), /Source link leaves the repository/u);
    expect(await Bun.file(join(outside.path, 'attributes')).text()).toBe(attributes);
});

test.each(['folder', 'Git'])(
    '%s attribute discovery honors later and nested overrides and keeps unrelated bytes',
    async (backend) => {
        await using sandbox = await testdir();
        await createFileTree(sandbox.path, ATTRIBUTE_PRECEDENCE_FILES);
        if (backend === 'Git') gitOutput(sandbox.path, ['init', '--quiet']);
        const repository = await readRepository(sandbox.path, [], [], []);
        expect(Object.fromEntries(repository.files.map(({ path, kind }) => [path, kind]))).toStrictEqual(
            ATTRIBUTE_PRECEDENCE_KINDS,
        );
        await createFileTree(sandbox.path, { '.gitattributes': '', 'nested/.gitattributes': '' });
        const corrected = await readRepository(sandbox.path, [], [], []);
        expect(Object.fromEntries(corrected.files.map(({ path, kind }) => [path, kind]))).toStrictEqual(
            ATTRIBUTE_CLEARED_KINDS,
        );
        for (const [path, bytes] of Object.entries(ATTRIBUTE_PRECEDENCE_FILES).filter(
            ([path]) => !path.endsWith('.gitattributes'),
        ))
            expect(readFileSync(join(sandbox.path, path), 'utf8')).toBe(bytes);
    },
);

test('Git info attributes override tracked declarations until removed', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, {
        '.gitattributes': '*.ts linguist-generated\n',
        'source.ts': 'export const source = 1;\n',
        'control.ts': 'export const control = 2;\n',
    });
    gitOutput(sandbox.path, ['init', '--quiet']);
    await createFileTree(sandbox.path, {
        '.git/info/attributes': '*.ts -linguist-generated\ncontrol.ts linguist-vendored\n',
    });
    const repository = await readRepository(sandbox.path, [], [], []);
    expect(Object.fromEntries(repository.files.map(({ path, kind }) => [path, kind]))).toStrictEqual({
        '.gitattributes': 'source',
        'source.ts': 'source',
        'control.ts': 'vendored',
    });
    unlinkSync(join(sandbox.path, '.git/info/attributes'));
    const corrected = await readRepository(sandbox.path, [], [], []);
    expect(Object.fromEntries(corrected.files.map(({ path, kind }) => [path, kind]))).toStrictEqual({
        '.gitattributes': 'source',
        'source.ts': 'generated',
        'control.ts': 'generated',
    });
    expect(readFileSync(join(sandbox.path, '.gitattributes'), 'utf8')).toBe('*.ts linguist-generated\n');
    expect(readFileSync(join(sandbox.path, 'source.ts'), 'utf8')).toBe('export const source = 1;\n');
    expect(readFileSync(join(sandbox.path, 'control.ts'), 'utf8')).toBe('export const control = 2;\n');
});
