import { describe, expect, test } from 'bun:test';

import { currentBlock, withBlock, withoutBlock } from '#cli/render/managed-blocks.ts';
import { carriesHeader, headerFor, withJsonHeader } from '#cli/render/templates.ts';
import { hookBody } from '#cli/render/hooks.ts';
import { relativeTarget } from '#cli/render/stubs.ts';

describe('generated-file headers', () => {
    test('use the comment style of the target', () => {
        expect(headerFor('.gspot/eslint.config.js', '0.1.0')).toStartWith(
            '// Generated by gspot 0.1.0 from gspot.toml. Do not edit.',
        );
        expect(headerFor('.gspot/typos.toml', '0.1.0')).toStartWith('# Generated by gspot 0.1.0');
        expect(headerFor('.gspot/prettier.json', '0.1.0')).toBe('');
        expect(withJsonHeader('{"a":1}', '0.1.0')).toStartWith('{\n    "_gspot": "Generated by gspot 0.1.0');
    });

    test('carriesHeader finds both forms', () => {
        expect(carriesHeader('# Generated by gspot 0.1.0 from gspot.toml.\n')).toBe(true);
        expect(carriesHeader('{\n  "_gspot": "x"\n}')).toBe(true);
        expect(carriesHeader('plain\n')).toBe(false);
    });
});

describe('managed blocks', () => {
    test('are appended once, replaced in place, and removed cleanly', () => {
        const once = withBlock('# Mine\n\ntext\n', 'block one', 'markdown');
        expect(once).toContain('# Mine');
        expect(currentBlock(once, 'markdown')).toBe('block one');
        const twice = withBlock(once, 'block two', 'markdown');
        expect(twice.match(/gspot managed >>>/g)).toHaveLength(1);
        expect(currentBlock(twice, 'markdown')).toBe('block two');
        expect(withoutBlock(twice, 'markdown')).toBe('# Mine\n\ntext\n');
        expect(withBlock(twice, 'block two', 'markdown')).toBe(twice);
    });
});

describe('hooks and stubs', () => {
    test('the hook resolves the binary through GSPOT_BIN or the runner', () => {
        const body = hookBody('pre-commit', 'mise');
        expect(body).toContain('${GSPOT_BIN:-mise exec -- gspot}');
        expect(body).toContain('check --staged "$@"');
        expect(hookBody('pre-push', 'none', '/opt/gspot')).toContain('git lfs pre-push');
        expect(hookBody('commit-msg', 'bun')).toContain('bunx gspot');
    });

    test('a stub imports its target by a relative path', () => {
        expect(relativeTarget('eslint.config.js', '.gspot/eslint.config.js')).toBe('./.gspot/eslint.config.js');
        expect(relativeTarget('api/tsconfig.json', '.gspot/tsconfig.base.json')).toBe('../.gspot/tsconfig.base.json');
    });
});
