// Marker strings and header templates gspot writes. Literals only.

export const MANAGED_BLOCK_START = '<!-- >>> gspot managed >>> -->';
export const MANAGED_BLOCK_END = '<!-- <<< gspot managed <<< -->';

export const HASH_BLOCK_START = '# >>> gspot managed >>>';
export const HASH_BLOCK_END = '# <<< gspot managed <<<';

export const GENERATED_HEADER_LINES = [
    'Generated by gspot {{version}} from gspot.toml. Do not edit.',
    'Change policy: gspot set / ignore, or edit gspot.toml, then run: gspot apply',
];

export const GENERATED_JSON_KEY = '_gspot';

export const VERSION_FILE_LINE = '{{version}}\n';

export const SCHEMA_LINE = '#:schema https://gspot.dev/schema/gspot.schema.json';

export const HOOK_HEADER = '# Written by gspot. Run `gspot uninstall` to remove.';

// The comment forms of an inline ignore. `marker` finds the comment and captures the check id; the
// reason is what follows `--` in the rest of the comment.
export const INLINE_IGNORE: Record<string, RegExp> = {
    slash: /\/\/ ?gspot-ignore +([a-z0-9/-]+)/u,
    hash: /# ?gspot-ignore +([a-z0-9/-]+)/u,
    dash: /-- ?gspot-ignore +([a-z0-9/-]+)/u,
    html: /<!-- ?gspot-ignore +([a-z0-9/-]+)/u,
};

export const REASON_INTRODUCER = '--';
export const HTML_COMMENT_CLOSE = '-->';

export const COMMENT_STYLE_BY_EXTENSION: Record<string, keyof typeof INLINE_IGNORE> = {
    '.ts': 'slash',
    '.tsx': 'slash',
    '.js': 'slash',
    '.mjs': 'slash',
    '.cjs': 'slash',
    '.jsx': 'slash',
    '.swift': 'slash',
    '.css': 'slash',
    '.scss': 'slash',
    '.py': 'hash',
    '.sh': 'hash',
    '.bash': 'hash',
    '.zsh': 'hash',
    '.toml': 'hash',
    '.yml': 'hash',
    '.yaml': 'hash',
    '.rb': 'hash',
    '.sql': 'dash',
    '.pgsql': 'dash',
    '.psql': 'dash',
    '.md': 'html',
    '.html': 'html',
    '.htm': 'html',
};

export const UNPARSED_LIMIT = 400;

export const COMMENT_OPENERS: Record<string, string[]> = {
    slash: ['//', '/*'],
    hash: ['#'],
    dash: ['--'],
    html: ['<!--'],
};
