// Render a preset template with the merged settings; prepend the generated-file header.
import { Eta } from 'eta';
import { join } from 'node:path';
import { existsSync, readFileSync } from 'node:fs';
import { parse as parseJsonc } from 'jsonc-parser';
import { jsonText } from '#cli/emit/json-format.ts';
import { readAsset } from '#cli/platform/assets.ts';
import { extensionOf } from '#cli/platform/paths.ts';
import type { ScopeSelection, Session } from '#types/run.ts';
import { GENERATED_HEADER_LINES, GENERATED_JSON_KEY } from '#config/markers.ts';
import type { JsonFormat, PackageImports, TemplateInputs, TsconfigPaths } from '#types/emit.ts';
import { BLOCK_IGNORES, DISABLED_UPSTREAM_RULES, TOKEN_IGNORES, VALE_PACKAGES } from '#config/prose.ts';

const JSON_INDENT = 4;

const JSON_WIDTH = 120;

const HEADER_LINES_CHECKED = 3;

const HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;

const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;

const LEADING_NEWLINES = /^\n+/u;

const TRAILING_STAR = /\*$/u;

const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);

const HTML_EXTENSIONS = new Set(['.md', '.html']);

const eta = new Eta({ autoEscape: false, autoTrim: false, useWith: true, rmWhitespace: false, varName: 'it' });

const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);

function readJsonFile(path: string, parse: (text: string) => unknown): unknown {
    if (!existsSync(path)) return undefined;
    try {
        return parse(readFileSync(path, 'utf8'));
    } catch {
        return undefined;
    }
}

function importTarget(target: unknown): string | undefined {
    if (typeof target === 'string') return target;
    if (typeof target !== 'object' || target === null) return undefined;
    return Object.values(target as Record<string, unknown>).find((value) => typeof value === 'string');
}

function packageAliases(root: string, prefix: string): Record<string, string> {
    const aliases: Record<string, string> = {};
    const manifest = readJsonFile(join(root, prefix, 'package.json'), (text) => JSON.parse(text)) as
        | PackageImports
        | undefined;
    const imports = Object.entries(manifest?.imports ?? {});
    for (const [pattern, target] of imports) {
        const found = importTarget(target);
        if (found === undefined) continue;
        if (!found.startsWith('./')) continue;
        const alias = found.slice(2).replace(TRAILING_STAR, '');
        aliases[pattern.replace(TRAILING_STAR, '')] = `${prefix}${alias}`;
    }
    return aliases;
}

function tsconfigAliases(root: string, prefix: string): Record<string, string> {
    const aliases: Record<string, string> = {};
    const tsconfig = readJsonFile(join(root, prefix, 'tsconfig.json'), (text) => parseJsonc(text)) as
        | TsconfigPaths
        | undefined;
    const paths = Object.entries(tsconfig?.compilerOptions?.paths ?? {});
    for (const [pattern, targets] of paths) {
        const target = targets[0];
        if (target === undefined) continue;
        const bare = target.startsWith('./') ? target.slice(2) : target;
        const alias = bare.replace(TRAILING_STAR, '');
        aliases[pattern.replace(TRAILING_STAR, '')] = `${prefix}${alias}`;
    }
    return aliases;
}

function aliasesFor(root: string, scope: string): Record<string, string> {
    const prefix = scope === '' ? '' : `${scope}/`;
    return { ...packageAliases(root, prefix), ...tsconfigAliases(root, prefix) };
}

function commented(lines: string[], mark: string): string {
    const marked = lines.map((line) => `${mark} ${line}`).join('\n');
    return `${marked}\n`;
}

function toolNames(session: Session): string[] {
    const names = session.scopes.flatMap((entry) =>
        entry.selected.flatMap((manifest) => manifest.tools.map((tool) => tool.name)),
    );
    return [...new Set(names)].toSorted((a, b) => a.localeCompare(b));
}

// The npm packages of the selected tools: a repository installs them to run them, and imports none of them.
function toolPackages(session: Session): string[] {
    const names = session.scopes.flatMap((entry) =>
        entry.selected.flatMap((manifest) =>
            manifest.tools.flatMap((tool) => {
                const name = tool.installers['npm'];
                return name === undefined ? [] : [name];
            }),
        ),
    );
    return [...new Set(names)].toSorted((a, b) => a.localeCompare(b));
}

/** The layout of generated JSON when no policy says otherwise. */
export const SHIPPED_JSON_FORMAT: JsonFormat = { width: JSON_WIDTH, indent: JSON_INDENT };

/**
 * The header lines for a version.
 * @param version the gspot version
 * @returns the two lines
 */
export function headerLines(version: string): string[] {
    return GENERATED_HEADER_LINES.map((line) => line.replaceAll('{{version}}', () => version));
}

/**
 * The header as a comment for a target path, or '' for JSON, which carries it as a key.
 * @param path the target path
 * @param version the gspot version
 * @returns the comment block ending in a newline, or ''
 */
export function headerFor(path: string, version: string): string {
    const extension = extensionOf(path);
    if (JSON_EXTENSIONS.has(extension)) return '';
    const lines = headerLines(version);
    if (SLASH_COMMENT_EXTENSIONS.has(extension)) return commented(lines, '//');
    if (HTML_EXTENSIONS.has(extension)) {
        const indented = lines.map((line) => `  ${line}`).join('\n');
        return `<!--\n${indented}\n-->\n`;
    }
    if (extension === '.sql') return commented(lines, '--');
    return commented(lines, '#');
}

/**
 * True when a text opens with the generated header (any version): in its first three lines, or as the first JSON key.
 * @param text a file's text
 * @returns whether gspot wrote it
 */
export function hasHeader(text: string): boolean {
    const lines = text.split('\n', HEADER_LINES_CHECKED + 1).slice(0, HEADER_LINES_CHECKED);
    if (lines.some((line) => HEADER_LINE.test(line))) return true;
    return JSON_HEADER.test(text) && text.includes(`"${GENERATED_JSON_KEY}"`);
}

/**
 * Puts the header into rendered JSON as the first key, formatted the way the repository's Prettier settings format it.
 * @param rendered the rendered JSON text
 * @param version the gspot version
 * @param format the print width and indent width
 * @returns the JSON text with the header key first
 */
export function jsonHeaderAdded(rendered: string, version: string, format: JsonFormat): string {
    const parsed = JSON.parse(rendered) as Record<string, unknown>;
    const ordered: Record<string, unknown> = { [GENERATED_JSON_KEY]: headerLines(version).join(' ') };
    for (const [key, value] of Object.entries(parsed)) if (key !== GENERATED_JSON_KEY) ordered[key] = value;
    return jsonText(ordered, format);
}

/**
 * The inputs every template sees.
 * @param session the session
 * @param selection the scope being rendered
 * @param fragments the fragment text other presets contribute
 * @returns the template inputs
 */
export function templateInputs(session: Session, selection: ScopeSelection, fragments = ''): TemplateInputs {
    const { view } = selection;
    const files = (extension: string): string[] =>
        session.repository.files
            .filter((file) => file.path.endsWith(extension) && file.nature === 'source')
            .map((file) => file.path);
    return {
        prose: {
            packages: VALE_PACKAGES,
            blockIgnores: BLOCK_IGNORES,
            tokenIgnores: TOKEN_IGNORES,
            disabledUpstream: DISABLED_UPSTREAM_RULES,
        },
        version: session.version,
        scope: selection.scope.path,
        scopes: session.scopes
            .filter((entry) => entry.scope.path !== '')
            .map((entry) => ({
                path: entry.scope.path,
                presets: entry.selected.map((manifest) => manifest.preset.name),
            })),
        presets: view.presets,
        policy: session.policyFiles.policy,
        view,
        format: view.format,
        settings: view.settings,
        fragments,
        tool: view.tool,
        toolEnabled: view.toolEnabled,
        limit: view.limit,
        rulesOff: view.rulesOff,
        ignoresFor: view.ignoresFor,
        extra: view.extra,
        json: (value, indent = JSON_INDENT) => JSON.stringify(value, null, indent),
        tomlString: (value) => JSON.stringify(value),
        // A target written once for the repository asks about every scope; a target written for one scope asks about that scope.
        has: (preset) =>
            view.presets.includes(preset) ||
            (selection.scope.path === '' &&
                session.scopes.some((entry) => entry.selected.some((manifest) => manifest.preset.name === preset))),
        importAliases: (scope) => aliasesFor(session.root, scope),
        tools: toolNames(session),
        toolPackages: toolPackages(session),
        files,
        header: headerFor('x.toml', session.version),
        headerLines: headerLines(session.version),
    };
}

/**
 * Renders template text with inputs.
 * @param template the template text
 * @param inputs the template inputs
 * @returns the rendered text
 */
export function templateText(template: string, inputs: TemplateInputs): string {
    return eta.renderString(template, inputs);
}

/**
 * Renders a preset template asset to the final text of a target, header included unless the target's reader refuses unknown keys.
 * @param templatePath the asset path of the template
 * @param targetPath the path the text is written to
 * @param inputs the template inputs
 * @param isHeaderWanted false for a reader that refuses the header key or comment
 * @returns the text to write
 */
export function emitTarget(
    templatePath: string,
    targetPath: string,
    inputs: TemplateInputs,
    isHeaderWanted = true,
): string {
    const rendered = templateText(readAsset(templatePath), inputs);
    if (JSON_EXTENSIONS.has(extensionOf(targetPath))) {
        const format = { width: inputs.format.print_width, indent: inputs.format.indent_width };
        if (!isHeaderWanted) return jsonText(JSON.parse(rendered), format);
        return jsonHeaderAdded(rendered, inputs.version, format);
    }
    const body = rendered.replace(LEADING_NEWLINES, '');
    if (!isHeaderWanted) return body;
    const ended = body.endsWith('\n') ? body : `${body}\n`;
    return `${headerFor(targetPath, inputs.version)}${ended}`;
}
