/** Generated text formats whose public pointers sit outside the private directory. */
export const GENERATED_HEADER_PATHS = ['tool.js', 'tool.py', 'tool.sql', 'tool.md', 'tool.html', 'tool.json'];

export const ATTRIBUTE_PRECEDENCE_FILES = {
    '.gitattributes': `*.pb.go linguist-generated
api/*.pb.go -linguist-generated
*.ts linguist-generated
api/*.false.ts linguist-generated=false
api/*.unspecified.ts !linguist-generated
*.vendor.js linguist-vendored
api/*.vendor.js -linguist-vendored
*.dat binary
notes.dat text
auto.dat text=auto
raw.txt binary
banner.js text
`,
    'nested/.gitattributes': '*.ts -linguist-generated\n',
    'generated.pb.go': 'package generated\n',
    'api/source.pb.go': 'package api\n',
    'api/source.false.ts': 'export {};\n',
    'api/source.unspecified.ts': 'export {};\n',
    'nested/source.ts': 'export {};\n',
    'shared.vendor.js': 'export {};\n',
    'api/source.vendor.js': 'export {};\n',
    'raw.dat': 'opaque bytes\n',
    'notes.dat': 'authored text\n',
    'auto.dat': 'opaque bytes\n',
    'raw.txt': 'opaque bytes\n',
    'banner.js': '// @generated by a compiler\nexport {};\n',
    'untouched.md': 'authored notes\n',
};

export const ATTRIBUTE_PRECEDENCE_KINDS = {
    '.gitattributes': 'source',
    'nested/.gitattributes': 'source',
    'generated.pb.go': 'generated',
    'api/source.pb.go': 'source',
    'api/source.false.ts': 'source',
    'api/source.unspecified.ts': 'source',
    'nested/source.ts': 'source',
    'shared.vendor.js': 'vendored',
    'api/source.vendor.js': 'source',
    'raw.dat': 'binary',
    'notes.dat': 'source',
    'auto.dat': 'binary',
    'raw.txt': 'binary',
    'banner.js': 'generated',
    'untouched.md': 'source',
} as const;

export const ATTRIBUTE_CLEARED_KINDS = {
    '.gitattributes': 'source',
    'nested/.gitattributes': 'source',
    'generated.pb.go': 'source',
    'api/source.pb.go': 'source',
    'api/source.false.ts': 'source',
    'api/source.unspecified.ts': 'source',
    'nested/source.ts': 'source',
    'shared.vendor.js': 'source',
    'api/source.vendor.js': 'source',
    'raw.dat': 'binary',
    'notes.dat': 'binary',
    'auto.dat': 'binary',
    'raw.txt': 'source',
    'banner.js': 'generated',
    'untouched.md': 'source',
} as const;
