// A file whose only runtime behavior is calling imported values; generated files exempt by banner.
import { createRule } from '#plugin/rule.ts';
import type { TSESTree } from '@typescript-eslint/utils';
import { AST_NODE_TYPES } from '@typescript-eslint/utils';
import { isIndexFile, lintedFile } from '#plugin/files.ts';

const GENERATED = /\b(?:auto-generated|automatically generated|do not edit|generated by)\b/iu;
const OWNED = new Set(['ArrowFunctionExpression', 'ClassExpression', 'FunctionExpression']);
const OWNING_STATEMENTS = new Set([
    'ClassDeclaration',
    'ExportDefaultDeclaration',
    'FunctionDeclaration',
    'TSEnumDeclaration',
    'VariableDeclaration',
]);
const TYPE_ONLY = new Set(['TSInterfaceDeclaration', 'TSModuleDeclaration', 'TSTypeAliasDeclaration']);
const ALWAYS_SKIPPED = new Set([
    'EmptyStatement',
    'ImportDeclaration',
    'TSImportEqualsDeclaration',
    'ExportAllDeclaration',
]);
const SKIPPED_KEYS = new Set(['comments', 'loc', 'parent', 'range', 'tokens']);
const WRAPPERS = new Set([
    'ChainExpression',
    'TSAsExpression',
    'TSInstantiationExpression',
    'TSNonNullExpression',
    'TSSatisfiesExpression',
    'TSTypeAssertion',
]);

function unwrap(node: TSESTree.Node | null | undefined): TSESTree.Node | null | undefined {
    let current = node;
    while (current && WRAPPERS.has(current.type)) current = (current as { expression: TSESTree.Node }).expression;
    return current;
}

function isRequireCall(node: TSESTree.Node | null | undefined): boolean {
    const current = unwrap(node);
    return (
        current?.type === AST_NODE_TYPES.CallExpression &&
        current.callee.type === AST_NODE_TYPES.Identifier &&
        current.callee.name === 'require' &&
        current.arguments.length === 1
    );
}

function isRequireInitializer(node: TSESTree.Node | null | undefined): boolean {
    const current = unwrap(node);
    if (isRequireCall(current)) return true;
    return current?.type === AST_NODE_TYPES.MemberExpression && isRequireCall(current.object);
}

function patternChildren(pattern: TSESTree.Node): (TSESTree.Node | null)[] {
    switch (pattern.type) {
        case AST_NODE_TYPES.RestElement: {
            return [pattern.argument];
        }
        case AST_NODE_TYPES.AssignmentPattern: {
            return [pattern.left];
        }
        case AST_NODE_TYPES.ArrayPattern: {
            return pattern.elements;
        }
        case AST_NODE_TYPES.ObjectPattern: {
            return pattern.properties.map((property) =>
                property.type === AST_NODE_TYPES.Property ? property.value : property.argument,
            );
        }
        default: {
            return [];
        }
    }
}

function patternNames(pattern: TSESTree.Node | null, names: Set<string>): void {
    if (!pattern) return;
    if (pattern.type === AST_NODE_TYPES.Identifier) {
        names.add(pattern.name);
        return;
    }
    for (const child of patternChildren(pattern)) patternNames(child, names);
}

function isRequireDeclaration(statement: TSESTree.Statement): statement is TSESTree.VariableDeclaration {
    return (
        statement.type === AST_NODE_TYPES.VariableDeclaration &&
        statement.declarations.length > 0 &&
        statement.declarations.every((declaration) => isRequireInitializer(declaration.init))
    );
}

function isValueImport(statement: TSESTree.ImportDeclaration, specifier: TSESTree.ImportClause): boolean {
    if (statement.importKind === 'type') return false;
    return specifier.type !== AST_NODE_TYPES.ImportSpecifier || specifier.importKind !== 'type';
}

function namesOfImport(statement: TSESTree.ImportDeclaration): string[] {
    return statement.specifiers
        .filter((specifier) => isValueImport(statement, specifier))
        .map((specifier) => specifier.local.name);
}

function namesOfStatement(statement: TSESTree.Statement): string[] {
    if (statement.type === AST_NODE_TYPES.ImportDeclaration) return namesOfImport(statement);
    if (!isRequireDeclaration(statement)) return [];
    const names = new Set<string>();
    for (const declaration of statement.declarations) patternNames(declaration.id, names);
    return [...names];
}

function importedNames(program: TSESTree.Program): Set<string> {
    return new Set(program.body.flatMap((statement) => namesOfStatement(statement)));
}

function isTypeOnly(statement: TSESTree.Node | null | undefined): boolean {
    return (
        (statement as { declare?: boolean } | null | undefined)?.declare === true ||
        TYPE_ONLY.has(statement?.type ?? '')
    );
}

function isSkipped(statement: TSESTree.Statement): boolean {
    if (ALWAYS_SKIPPED.has(statement.type) || isTypeOnly(statement) || isRequireDeclaration(statement)) return true;
    if (statement.type === AST_NODE_TYPES.ExpressionStatement) return isRequireCall(statement.expression);
    if (statement.type === AST_NODE_TYPES.ExportNamedDeclaration)
        return !statement.declaration || isTypeOnly(statement.declaration);
    return false;
}

function isOwned(statement: TSESTree.Statement): boolean {
    if (statement.type === AST_NODE_TYPES.ExportNamedDeclaration) return statement.declaration !== null;
    return OWNING_STATEMENTS.has(statement.type);
}

function hasOwnedChild(node: unknown): boolean {
    if (typeof node !== 'object' || node === null) return false;
    const record = node as Record<string, unknown> & { type?: string };
    if (record.type !== undefined && OWNED.has(record.type)) return true;
    return Object.entries(record).some(([key, value]) => {
        if (SKIPPED_KEYS.has(key)) return false;
        return Array.isArray(value) ? value.some((item) => hasOwnedChild(item)) : hasOwnedChild(value);
    });
}

function isImportedReference(node: TSESTree.Node | null | undefined, names: Set<string>): boolean {
    const current = unwrap(node);
    if (current?.type === AST_NODE_TYPES.Identifier) return names.has(current.name);
    if (isRequireCall(current)) return true;
    return current?.type === AST_NODE_TYPES.MemberExpression && isImportedReference(current.object, names);
}

function isCallLike(node: TSESTree.Node): node is TSESTree.CallExpression | TSESTree.NewExpression {
    return node.type === AST_NODE_TYPES.CallExpression || node.type === AST_NODE_TYPES.NewExpression;
}

function isImportedCall(node: TSESTree.Node | null | undefined, names: Set<string>): boolean {
    const current = unwrap(node);
    if (!current) return false;
    if (current.type === AST_NODE_TYPES.AwaitExpression) {
        const argument = unwrap(current.argument);
        return isImportedReference(argument, names) || isImportedCall(argument, names);
    }
    if (!isCallLike(current)) return false;
    if (isImportedReference(current.callee, names)) return true;
    return current.callee.type === AST_NODE_TYPES.MemberExpression && isImportedCall(current.callee.object, names);
}

function isGenerated(source: { ast: TSESTree.Program; getAllComments(): TSESTree.Comment[] }): boolean {
    const firstStatement = source.ast.body.find((statement) => statement.type !== AST_NODE_TYPES.ImportDeclaration);
    const start = firstStatement?.range[0] ?? Infinity;
    return source.getAllComments().some((comment) => comment.range[0] < start && GENERATED.test(comment.value));
}

function trivialCalls(program: TSESTree.Program, names: Set<string>): TSESTree.Statement[] {
    const reports: TSESTree.Statement[] = [];
    for (const statement of program.body) {
        if (isSkipped(statement)) continue;
        if (isOwned(statement) || hasOwnedChild(statement)) return [];
        if (statement.type !== AST_NODE_TYPES.ExpressionStatement || !isImportedCall(statement.expression, names))
            return [];
        reports.push(statement);
    }
    return reports;
}

export const noTrivialFiles = createRule<[], 'trivial'>({
    name: 'no-trivial-files',
    meta: {
        type: 'problem',
        docs: {
            summary: 'Finds a file whose only runtime behavior is calling values it imported.',
            why: 'A file that only calls other modules owns nothing; the calls belong where the values live.',
            fix: 'Move the calls into the module that owns the behavior, or give this file a declaration of its own.',
        },
        schema: [],
        messages: {
            trivial:
                'This file only calls imported values. Move the calls to the module that owns them, or give the file behavior of its own.',
        },
    },
    defaultOptions: [],
    create(context) {
        const file = lintedFile(context);
        if (file === undefined || isIndexFile(file) || isGenerated(context.sourceCode)) return {};
        return {
            Program(node) {
                const names = importedNames(node);
                if (names.size === 0) return;
                for (const statement of trivialCalls(node, names))
                    context.report({ node: statement, messageId: 'trivial' });
            },
        };
    },
});
