// A fresh Git clone has no ownership log: apply adopts the committed generated files as they are.
import { join } from 'node:path';
import { test, expect } from 'bun:test';
import { statSync, readFileSync } from 'node:fs';
import { testdir, createFileTree } from 'testdirs';
import { run } from '#tests/support/cli/command.ts';
import { commitAll } from '#tests/support/cli/git.ts';
import { initArgs } from '#tests/support/cli/init.ts';
import { run as spawn } from '#cli/platform/spawn.ts';
import { keptMode } from '#tests/support/cli/platforms.ts';

test('a fresh Git clone adopts exact generated bytes without changing checkout permissions', async () => {
    await using original = await testdir();
    await using clone = await testdir();
    await createFileTree(original.path, { 'entry.sh': 'echo example\n' });
    commitAll(original.path);
    const initialized = await run(original.path, initArgs(['bash']));
    expect(initialized.code, initialized.stdout + initialized.stderr).toBe(0);
    commitAll(original.path);
    const cloned = await spawn(['git', 'clone', '--quiet', '--no-local', original.path, clone.path], {
        cwd: original.path,
    });
    expect(cloned.code, cloned.stderr).toBe(0);
    const config = join(clone.path, '.gspot/config/shellcheckrc');
    const bytes = readFileSync(config);
    expect(statSync(config).mode & 0o777).toBe(keptMode(0o644));
    const applied = await run(clone.path, ['apply', '--json']);
    expect(applied.code, applied.stdout + applied.stderr).toBe(0);
    expect(
        (JSON.parse(applied.stdout) as { notes: string[] }).notes.filter((note) => note.includes('shellcheckrc')),
    ).toStrictEqual([]);
    expect(readFileSync(config)).toStrictEqual(bytes);
    expect(statSync(config).mode & 0o777).toBe(keptMode(0o644));
    const repeated = await run(clone.path, ['apply', '--json']);
    expect(repeated.code, repeated.stdout + repeated.stderr).toBe(0);
    expect((JSON.parse(repeated.stdout) as { written: string[] }).written).toStrictEqual([]);
    const unchanged = await spawn(['git', 'diff', '--exit-code'], { cwd: clone.path });
    expect(unchanged.code, unchanged.stdout + unchanged.stderr).toBe(0);
});
