import { arch, platform } from 'node:os'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { optionalString, readDocument, requiredString, type Table } from '@/settings/toml'
import { LOCK_PATH } from '@config/paths'
import { TOOL_LOCK_VERSION } from '@config/versions'
import type { Asset, Lock, LockedTool } from 'types/toolchain'
import { optional } from '@/settings/optional'

export function hostKey(): string {
  return `${platform()}-${arch()}`
}

export async function readLock(root: string): Promise<Lock | null> {
  try {
    return parseLock(await readFile(join(root, LOCK_PATH), 'utf8'), LOCK_PATH)
  } catch (reason) {
    if ((reason as NodeJS.ErrnoException).code === 'ENOENT') return null
    throw reason
  }
}

export function parseLock(text: string, source: string): Lock {
  const document = readDocument(text, source)
  const version = document['version']
  if (version !== TOOL_LOCK_VERSION) {
    throw new Error(`${source}: \`version\` is ${String(version)}, and this gspot reads ${TOOL_LOCK_VERSION}.`)
  }
  const tools = new Map<string, LockedTool>()
  for (const [id, value] of Object.entries(document)) {
    if (id === 'version') continue
    tools.set(id, readTool(id, value as Table, source))
  }
  return { version: TOOL_LOCK_VERSION, tools }
}

function readTool(id: string, table: Table, source: string): LockedTool {
  const where = `${source} [${id}]`
  const assets = new Map<string, Asset>()
  for (const [key, value] of Object.entries(table)) {
    if (!key.includes('-')) continue
    const asset = value as Table
    assets.set(key, {
      url: requiredString(asset, 'url', `${where}.${key}`),
      sha256: requiredString(asset, 'sha256', `${where}.${key}`),
    })
  }
  return {
    id,
    version: requiredString(table, 'version', where),
    provider: requiredString(table, 'provider', where),
    ...optional('package', optionalString(table, 'package', where)),
    assets,
  }
}

export async function writeLock(root: string, lock: Lock): Promise<void> {
  const target = join(root, LOCK_PATH)
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, renderLock(lock), 'utf8')
}

export function renderLock(lock: Lock): string {
  const lines = [
    '# Generated by gspot. Do not edit',
    '# Regenerate: gspot install, or gspot upgrade',
    '',
    `version = ${lock.version}`,
  ]
  for (const tool of [...lock.tools.values()].sort((left, right) => (left.id < right.id ? -1 : 1))) {
    lines.push('', `[${tool.id}]`, `version  = ${JSON.stringify(tool.version)}`)
    lines.push(`provider = ${JSON.stringify(tool.provider)}`)
    if (tool.package !== undefined) lines.push(`package  = ${JSON.stringify(tool.package)}`)
    for (const key of [...tool.assets.keys()].sort()) {
      const asset = tool.assets.get(key)
      if (asset === undefined) continue
      lines.push('', `[${tool.id}.${key}]`)
      lines.push(`url    = ${JSON.stringify(asset.url)}`)
      lines.push(`sha256 = ${JSON.stringify(asset.sha256)}`)
    }
  }
  return `${lines.join('\n')}\n`
}

export function assetUrl(template: string, version: string, key: string): string {
  const [os = '', machine = ''] = key.split('-')
  return template
    .replaceAll('{version}', version)
    .replaceAll('{os}', os)
    .replaceAll('{arch}', machine)
}
