// Generated by the policy schema compiler.
import { z } from 'zod';
import { settingNamespaceSchemas } from '#cli/policy/schema/namespaces.ts';

export const activeSettingNamespaceSchemas = {
    architecture: settingNamespaceSchemas['architecture'].required({ modules: true }),
    bash: settingNamespaceSchemas['bash'].required({ safety_owners: true }),
    cloudflare: settingNamespaceSchemas['cloudflare'].required({ types_file: true, types_interface: true }),
    coverage: settingNamespaceSchemas['coverage'].required({
        lines: true,
        branches: true,
        functions: true,
        statements: true,
        overrides: true,
    }),
    dependencies: settingNamespaceSchemas['dependencies'].required({
        min_release_age_days: true,
        scanner: true,
        registry_hosts: true,
    }),
    docs: settingNamespaceSchemas['docs'].required({ banned_headings: true, require_license: true }),
    drizzle: settingNamespaceSchemas['drizzle'].required({ client_names: true }),
    format: settingNamespaceSchemas['format'].required({
        indent_style: true,
        indent_width: true,
        print_width: true,
        line_ending: true,
        final_newline: true,
        quotes: true,
        trailing_commas: true,
        semicolons: true,
    }),
    html: settingNamespaceSchemas['html'].required({ templates: true }),
    i18n: settingNamespaceSchemas['i18n'].required({ base_locale: true }),
    licenses: settingNamespaceSchemas['licenses'].required({ allowed: true, exceptions: true }),
    limits: settingNamespaceSchemas['limits']
        .required({
            file_lines: true,
            function_lines: true,
            function_parameters: true,
            cognitive_complexity: true,
            cyclomatic_complexity: true,
            nesting: true,
            statements: true,
            callback_nesting: true,
            index_exports: true,
            prefix_collisions: true,
            min_function_statements: true,
        })
        .extend({
            docs: settingNamespaceSchemas['limits'].shape['docs'].unwrap().required({
                headings_before_contents: true,
                sentence_words: true,
                list_item_words: true,
                paragraph_sentences: true,
            }),
            duplication: settingNamespaceSchemas['limits'].shape['duplication']
                .unwrap()
                .required({ min_lines: true, min_tokens: true, percent: true }),
            python: settingNamespaceSchemas['limits'].shape['python']
                .unwrap()
                .required({ branches: true, returns: true }),
            bash: settingNamespaceSchemas['limits'].shape['bash']
                .unwrap()
                .required({ file_lines: true, function_lines: true, branches: true, nesting: true, assignments: true }),
            swift: settingNamespaceSchemas['limits'].shape['swift']
                .unwrap()
                .required({ type_lines: true, closure_lines: true }),
        }),
    links: settingNamespaceSchemas['links'].required({ allowed_urls: true }),
    naming: settingNamespaceSchemas['naming']
        .required({ banned: true, allowed: true, reserved: true, max_chars: true, max_words: true })
        .extend({
            swift: settingNamespaceSchemas['naming'].shape['swift']
                .unwrap()
                .required({ max_chars: true, max_words: true }),
            sql: settingNamespaceSchemas['naming'].shape['sql'].unwrap().required({ max_chars: true, max_words: true }),
        }),
    openapi: settingNamespaceSchemas['openapi'].required({ document: true, generate_command: true }),
    postgres: settingNamespaceSchemas['postgres'].required({
        frozen_through: true,
        migrations_folder: true,
        client_schemas: true,
        docs: true,
        doc_sections: true,
    }),
    secrets: settingNamespaceSchemas['secrets'].required({ env_examples: true, reader_functions: true }),
    site: settingNamespaceSchemas['site'].required({
        build_command: true,
        build_folder: true,
        max_kilobytes: true,
        sitemap_exclude: true,
    }),
    structure: settingNamespaceSchemas['structure'].required({ reexports: true }),
    supabase: settingNamespaceSchemas['supabase'].required({ schemas: true, types_file: true, functions_folder: true }),
    swift: settingNamespaceSchemas['swift'].required({
        xcode_project: true,
        xcode_scheme: true,
        xcode_destination: true,
    }),
    'tools.codeql': settingNamespaceSchemas['tools.codeql'].required({ languages: true, suite: true }),
    'tools.commitlint': settingNamespaceSchemas['tools.commitlint'].required({
        types: true,
        scopes: true,
        rules: true,
    }),
    'tools.eslint': settingNamespaceSchemas['tools.eslint'].required({
        rules: true,
        overrides: true,
        import_extensions: true,
        runtimes: true,
        restricted_imports: true,
    }),
    'tools.hadolint': settingNamespaceSchemas['tools.hadolint'].required({ trusted_registries: true }),
    'tools.knip': settingNamespaceSchemas['tools.knip'].required({ entry: true, ignore_dependencies: true }),
    'tools.markdownlint': settingNamespaceSchemas['tools.markdownlint'].required({ rules: true }),
    'tools.nginx': settingNamespaceSchemas['tools.nginx'].required({ image: true }),
    'tools.purgecss': settingNamespaceSchemas['tools.purgecss'].required({ safelist: true }),
    'tools.ruff': settingNamespaceSchemas['tools.ruff'],
    'tools.semgrep': settingNamespaceSchemas['tools.semgrep'].required({ rule_files: true, registry: true }),
    'tools.sqlfluff': settingNamespaceSchemas['tools.sqlfluff'].required({ dialect: true }),
    'tools.squawk': settingNamespaceSchemas['tools.squawk'].required({ assume_in_transaction: true }),
    'tools.stylelint': settingNamespaceSchemas['tools.stylelint'].required({ rules: true }),
    'tools.svgo': settingNamespaceSchemas['tools.svgo'].required({ min_saving_percent: true }),
    'tools.swiftlint': settingNamespaceSchemas['tools.swiftlint'].required({ keep_imports: true }),
    'tools.trivy': settingNamespaceSchemas['tools.trivy'].required({ severity: true }),
    'tools.typos': settingNamespaceSchemas['tools.typos'].required({ locale: true }),
    'tools.v8r': settingNamespaceSchemas['tools.v8r'].required({ schemas: true }),
    'tools.yamllint': settingNamespaceSchemas['tools.yamllint'].required({ rules: true }),
    xcode: settingNamespaceSchemas['xcode'].required({ entitlements_allowed: true }),
};
export const activeSettingNamespacesSchema = z.strictObject(activeSettingNamespaceSchemas).partial();
