import { join } from 'node:path';
import { test, expect } from 'bun:test';
import { readFile } from 'node:fs/promises';
import { planRun } from '#cli/planning/public.ts';
import { commitAll } from '#tests/harness/git.ts';
import { testdir, createFileTree } from 'testdirs';
import { openSession } from '#cli/commands/public.ts';
import { executeRun } from '#cli/execution/public.ts';
import { checkRun } from '#cli/execution/contracts.ts';
import { buildPolicy } from '#tests/harness/policy.ts';
import { BUILT_IN_CHECKS } from '#cli/checks/public.ts';
import { buildInitArguments } from '#tests/harness/init.ts';
import { levelSchema } from '#cli/parsers/schema/contracts.ts';
import type { RunReport } from '#cli/types/execution/check.ts';
import { spawnGspot, buildRunOptions } from '#tests/harness/gspot.ts';
import { sharePythonTools } from '#tests/harness/python-installation.ts';
import { buildToolsPath, initRepository } from '#tests/harness/install.ts';
import { containing, textContaining } from '#tests/harness/expectations.ts';

// Sandbox for the github-actions configuration: a workflow with an unknown expression context and one open to template injection.

test('the github-actions configuration: GitHub initialization writes a workflow accepted by actionlint', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, { 'README.md': '# Workflow test\n' });
    commitAll(sandbox.path);
    const environment = { PATH: buildToolsPath(['actionlint']) };
    await initRepository(sandbox.path, buildInitArguments(['github-actions'], { ci: 'github' }), environment);
    const selected = await spawnGspot(sandbox.path, ['set', 'level', 'all'], environment);
    expect(selected.code, selected.stdout + selected.stderr).toBe(0);
    const workflow = join(sandbox.path, '.github/workflows/gspot.yml');
    expect(await Bun.file(workflow).exists()).toBe(true);
    const emitted = await readFile(workflow);
    const headerEnd = emitted.indexOf('\n');
    expect(emitted.subarray(0, headerEnd).toString('utf8')).toMatch(/^# Generated by gspot /u);
    const payload = emitted.subarray(headerEnd + 1);
    await createFileTree(sandbox.path, { '.github/workflows/accepted.yml': payload.toString('utf8') });
    expect(await readFile(join(sandbox.path, '.github/workflows/accepted.yml'))).toEqual(payload);
    const session = await openSession(sandbox.path);
    expect(session.repository.files.find((file) => file.path === '.github/workflows/accepted.yml')).toMatchObject({
        kind: 'source',
    });
    const result = await spawnGspot(
        sandbox.path,
        ['check', '--only', 'github-actions/actionlint', '--json'],
        environment,
    );
    expect(result.code, result.stderr + result.stdout).toBe(0);
    expect(await readFile(workflow)).toEqual(emitted);
    expect((JSON.parse(result.stdout) as RunReport).checks).toMatchObject([
        { check: 'github-actions/actionlint', status: 'passed', findings: [] },
    ]);
});

// Runs the pinned Actionlint check over the repository's current authored workflows.
async function runActionlint(root: string) {
    const session = await openSession(root);
    const planned = planRun(session, { stage: 'commit', skips: [], only: ['github-actions/actionlint'] })[0]!;
    return checkRun(planned.check, BUILT_IN_CHECKS)(session, planned);
}

// GitHub self-repository references use $/. The pinned Actionlint needs their local spelling.
test('Actionlint validates required reusable inputs in self-repository workflows and preserves authored files', async () => {
    await using sandbox = await testdir();
    const workflow = `on: workflow_dispatch\njobs:\n  caller:\n    uses: $/.github/workflows/called.yml\n`;
    const called =
        'on:\n  workflow_call:\n    inputs:\n      greeting:\n        type: string\n        required: true\njobs:\n  greet:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo hello\n';
    await createFileTree(sandbox.path, {
        'gspot.toml': buildPolicy(['github-actions']),
        '.github/workflows/caller.yml': workflow,
        '.github/workflows/called.yml': called,
    });
    const failed = await runActionlint(sandbox.path);
    expect(failed.status, JSON.stringify(failed)).toBe('failed');
    expect(failed.findings).toContainEqual(
        containing({
            file: '.github/workflows/caller.yml',
            line: 4,
            column: 11,
            rule: 'workflow-call',
            message: textContaining('input "greeting" is required'),
        }),
    );
    expect(await Bun.file(join(sandbox.path, '.github/workflows/caller.yml')).text()).toBe(workflow);
    await Bun.write(
        join(sandbox.path, '.github/workflows/caller.yml'),
        `${workflow}    with:\n      greeting: Hello\n`,
    );
    const result = await runActionlint(sandbox.path);
    expect(result.status).toBe('passed');
    expect(await Bun.file(join(sandbox.path, '.github/workflows/called.yml')).text()).toBe(called);
});

test('Actionlint resolves a self-repository alias and reports a missing workflow before correction', async () => {
    await using sandbox = await testdir();
    const workflow =
        'on: workflow_dispatch\nenv:\n  WORKFLOW: &workflow $/.github/workflows/called.yml\njobs:\n  caller:\n    uses: *workflow\n';
    await createFileTree(sandbox.path, {
        'gspot.toml': buildPolicy(['github-actions']),
        '.github/workflows/caller.yml': workflow,
    });
    const failed = await runActionlint(sandbox.path);
    expect(failed.status, JSON.stringify(failed)).toBe('failed');
    expect(failed.findings).toContainEqual(
        containing({
            file: '.github/workflows/caller.yml',
            line: 3,
            column: 13,
            rule: 'workflow-call',
            message: textContaining('could not read reusable workflow file'),
        }),
    );
    await Bun.write(
        join(sandbox.path, '.github/workflows/called.yml'),
        'on: workflow_call\njobs:\n  greet:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo hello\n',
    );
    const result = await runActionlint(sandbox.path);
    expect(result.status).toBe('passed');
    expect(await Bun.file(join(sandbox.path, '.github/workflows/caller.yml')).text()).toBe(workflow);
});

test.each(levelSchema.options)(
    'Zizmor audits composite actions without duplicating pinact at level %s',
    async (level) => {
        await using sandbox = await testdir();
        const composite = `name: Greet
inputs:
    message:
        description: Message to print
        required: true
runs:
    using: composite
    steps:
        - shell: bash
          run: echo "\${{ inputs.message }}"
`;
        const workflow =
            'on: workflow_dispatch\npermissions: {}\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          persist-credentials: false\n';
        await createFileTree(sandbox.path, {
            'gspot.toml': buildPolicy(['github-actions'], {
                level,
                tables: 'runner = "mise"\n[scope.app]\nconfigurations = ["github-actions"]\n',
            }),
            '.github/workflows/build.yml': workflow,
            '.github/actions/greet/action.yml': composite,
            'app/.github/workflows/build.yml': workflow,
            'app/.github/actions/greet/action.yaml': composite,
        });
        await sharePythonTools(sandbox.path);
        const session = await openSession(sandbox.path);
        const actionlint = planRun(session, { stage: 'commit', skips: [], only: ['github-actions/actionlint'] });
        expect(actionlint.flatMap(({ files }) => files.map(({ path }) => path))).toStrictEqual([
            '.github/workflows/build.yml',
            'app/.github/workflows/build.yml',
        ]);
        const failed = await executeRun(session, buildRunOptions({ stage: 'commit', only: ['github-actions/zizmor'] }));
        expect(failed.report.exitCode, JSON.stringify(failed.report)).toBe(1);
        expect(
            failed.report.checks.flatMap(({ findings }) => findings).map(({ file, rule }) => ({ file, rule })),
        ).toStrictEqual([
            { file: '.github/actions/greet/action.yml', rule: 'template-injection' },
            { file: 'app/.github/actions/greet/action.yaml', rule: 'template-injection' },
        ]);
        for (const path of ['.github/actions/greet/action.yml', 'app/.github/actions/greet/action.yaml'])
            await Bun.write(
                join(sandbox.path, path),
                composite.replace(
                    '          run: echo "${{ inputs.message }}"',
                    '          env:\n              MESSAGE: ${{ inputs.message }}\n          run: echo "$MESSAGE"',
                ),
            );
        const corrected = await executeRun(
            await openSession(sandbox.path),
            buildRunOptions({ stage: 'commit', only: ['github-actions/zizmor'] }),
        );
        expect(corrected.report.exitCode, JSON.stringify(corrected.report)).toBe(0);
        expect(await Bun.file(join(sandbox.path, '.github/workflows/build.yml')).text()).toBe(workflow);
    },
);
