import { QUIET_INIT } from '#tests/config/harness/init.ts';
/** Bash commands copied between two source files. */
export const DUPLICATION_INIT = ['init', '--yes', '--configurations', 'bash', ...QUIET_INIT];

/** Copied metadata belongs to file validation rather than the selected Bash source scan. */
export const METADATA =
    '[\n    {\n        "name": "entry-0",\n        "value": 0\n    },\n    {\n        "name": "entry-1",\n        "value": 1\n    },\n    {\n        "name": "entry-2",\n        "value": 2\n    },\n    {\n        "name": "entry-3",\n        "value": 3\n    },\n    {\n        "name": "entry-4",\n        "value": 4\n    },\n    {\n        "name": "entry-5",\n        "value": 5\n    },\n    {\n        "name": "entry-6",\n        "value": 6\n    },\n    {\n        "name": "entry-7",\n        "value": 7\n    },\n    {\n        "name": "entry-8",\n        "value": 8\n    },\n    {\n        "name": "entry-9",\n        "value": 9\n    },\n    {\n        "name": "entry-10",\n        "value": 10\n    },\n    {\n        "name": "entry-11",\n        "value": 11\n    },\n    {\n        "name": "entry-12",\n        "value": 12\n    },\n    {\n        "name": "entry-13",\n        "value": 13\n    },\n    {\n        "name": "entry-14",\n        "value": 14\n    },\n    {\n        "name": "entry-15",\n        "value": 15\n    },\n    {\n        "name": "entry-16",\n        "value": 16\n    },\n    {\n        "name": "entry-17",\n        "value": 17\n    },\n    {\n        "name": "entry-18",\n        "value": 18\n    },\n    {\n        "name": "entry-19",\n        "value": 19\n    },\n    {\n        "name": "entry-20",\n        "value": 20\n    },\n    {\n        "name": "entry-21",\n        "value": 21\n    },\n    {\n        "name": "entry-22",\n        "value": 22\n    },\n    {\n        "name": "entry-23",\n        "value": 23\n    },\n    {\n        "name": "entry-24",\n        "value": 24\n    },\n    {\n        "name": "entry-25",\n        "value": 25\n    },\n    {\n        "name": "entry-26",\n        "value": 26\n    },\n    {\n        "name": "entry-27",\n        "value": 27\n    },\n    {\n        "name": "entry-28",\n        "value": 28\n    },\n    {\n        "name": "entry-29",\n        "value": 29\n    },\n    {\n        "name": "entry-30",\n        "value": 30\n    },\n    {\n        "name": "entry-31",\n        "value": 31\n    },\n    {\n        "name": "entry-32",\n        "value": 32\n    },\n    {\n        "name": "entry-33",\n        "value": 33\n    },\n    {\n        "name": "entry-34",\n        "value": 34\n    },\n    {\n        "name": "entry-35",\n        "value": 35\n    },\n    {\n        "name": "entry-36",\n        "value": 36\n    },\n    {\n        "name": "entry-37",\n        "value": 37\n    },\n    {\n        "name": "entry-38",\n        "value": 38\n    },\n    {\n        "name": "entry-39",\n        "value": 39\n    }\n]';

export const STEPS =
    '    printf \'step %s of %s\\n\' "0" "$total"\n    total=$((total + 0))\n    printf \'step %s of %s\\n\' "1" "$total"\n    total=$((total + 1))\n    printf \'step %s of %s\\n\' "2" "$total"\n    total=$((total + 2))\n    printf \'step %s of %s\\n\' "3" "$total"\n    total=$((total + 3))\n    printf \'step %s of %s\\n\' "4" "$total"\n    total=$((total + 4))\n    printf \'step %s of %s\\n\' "5" "$total"\n    total=$((total + 5))\n    printf \'step %s of %s\\n\' "6" "$total"\n    total=$((total + 6))\n    printf \'step %s of %s\\n\' "7" "$total"\n    total=$((total + 7))\n    printf \'step %s of %s\\n\' "8" "$total"\n    total=$((total + 8))\n    printf \'step %s of %s\\n\' "9" "$total"\n    total=$((total + 9))\n    printf \'step %s of %s\\n\' "10" "$total"\n    total=$((total + 10))\n    printf \'step %s of %s\\n\' "11" "$total"\n    total=$((total + 11))\n    printf \'step %s of %s\\n\' "12" "$total"\n    total=$((total + 12))\n    printf \'step %s of %s\\n\' "13" "$total"\n    total=$((total + 13))\n    printf \'step %s of %s\\n\' "14" "$total"\n    total=$((total + 14))\n    printf \'step %s of %s\\n\' "15" "$total"\n    total=$((total + 15))\n    printf \'step %s of %s\\n\' "16" "$total"\n    total=$((total + 16))\n    printf \'step %s of %s\\n\' "17" "$total"\n    total=$((total + 17))\n    printf \'step %s of %s\\n\' "18" "$total"\n    total=$((total + 18))\n    printf \'step %s of %s\\n\' "19" "$total"\n    total=$((total + 19))\n    printf \'step %s of %s\\n\' "20" "$total"\n    total=$((total + 20))\n    printf \'step %s of %s\\n\' "21" "$total"\n    total=$((total + 21))\n    printf \'step %s of %s\\n\' "22" "$total"\n    total=$((total + 22))\n    printf \'step %s of %s\\n\' "23" "$total"\n    total=$((total + 23))\n    printf \'step %s of %s\\n\' "24" "$total"\n    total=$((total + 24))\n    printf \'step %s of %s\\n\' "25" "$total"\n    total=$((total + 25))\n    printf \'step %s of %s\\n\' "26" "$total"\n    total=$((total + 26))\n    printf \'step %s of %s\\n\' "27" "$total"\n    total=$((total + 27))\n    printf \'step %s of %s\\n\' "28" "$total"\n    total=$((total + 28))\n    printf \'step %s of %s\\n\' "29" "$total"\n    total=$((total + 29))';
