import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, it } from 'bun:test'
import { HIDDEN_SQL } from '@config/tests/repositories'
import { runGenerate } from '@/commands/generate'
import { readPolicy } from '@/settings/policy'
import { removeRepository, plant, PRESETS } from '@tests/support/repository'

describe('runGenerate', () => {
  let root = ''
  const run = (check: boolean) =>
    runGenerate({ cwd: root, presetsRoot: PRESETS, version: '0.1.0', check })

  beforeEach(async () => {
    root = await plant('generate', HIDDEN_SQL)
  })

  afterEach(async () => {
    await removeRepository(root)
  })

  it('writes a configuration for every check that is pointed at one', async () => {
    const outcome = await run(false)
    const policy = await readPolicy(root, PRESETS)
    const pointed = policy.presets.flatMap((preset) =>
      preset.checks.filter((check) => check.configArg !== undefined).map((check) => check.id),
    )
    assert.ok(pointed.length > 0)
    for (const id of pointed) {
      assert.ok(outcome.files.some((file) => file.readers.includes(id)), `${id} has no config`)
    }
  })

  it('names the command that wrote each file', async () => {
    await run(false)
    const written = await readFile(join(root, '.gspot/generated/sqlfluff.cfg'), 'utf8')
    assert.match(written, /^# Generated by gspot 0\.1\.0 from gspot\.toml\. Do not edit/u)
  })

  it('derives two tool settings from one format block', async () => {
    await run(false)
    const written = await readFile(join(root, '.gspot/generated/sqlfluff.cfg'), 'utf8')
    assert.match(written, /max_line_length = 100/u)
    assert.match(written, /tab_space_size = 2/u)
  })

  it('moves a changed format setting through to the tool config', async () => {
    await writeFile(
      join(root, 'gspot.toml'),
      'version = 1\nrunner = "mise"\n\npresets = ["language:sql"]\n\n[format]\nset.print_width = 72\n',
      'utf8',
    )
    await run(false)
    const written = await readFile(join(root, '.gspot/generated/sqlfluff.cfg'), 'utf8')
    assert.match(written, /max_line_length = 72/u)
  })

  it('renders the same bytes twice', async () => {
    await run(false)
    const first = await readFile(join(root, '.gspot/generated/sqlfluff.cfg'), 'utf8')
    await run(false)
    assert.equal(await readFile(join(root, '.gspot/generated/sqlfluff.cfg'), 'utf8'), first)
  })
})
