import type { ConfigArtifact } from 'types/manifest'

import type { RenderInputs } from 'types/configuration'

const PLACEHOLDER = /\{\{\s*([A-Za-z0-9._-]+)\s*(\|\s*raw\s*)?\}\}/gu

export function render(inputs: RenderInputs): string {
  const body = substitute(inputs)
  return `${headerFor(inputs.target, inputs.version)}${body}`
}

function substitute(inputs: RenderInputs): string {
  return inputs.template.replace(PLACEHOLDER, (_, name: string, raw: string | undefined) => {
    const setting = inputs.settings.get(name)
    if (setting === undefined) {
      throw new Error(
        `${inputs.source}: the template asks for \`${name}\`, which no selected preset exposes.\n` +
          '  A template reads preset defaults, merged settings and declared product facts, and\n' +
          '  nothing else. Declare the setting in the preset, or take the placeholder out.',
      )
    }
    return raw === undefined ? JSON.stringify(setting.value) : String(setting.value)
  })
}

const HEADER_LINES = (version: string): readonly string[] => [
  `Generated by gspot ${version} from gspot.toml. Do not edit`,
  'Regenerate: gspot generate',
  'Change policy: edit gspot.toml, then run gspot generate',
]

export function headerFor(target: string, version: string): string {
  const lines = HEADER_LINES(version)
  switch (commentStyleOf(target)) {
    case 'hash':
      return `${lines.map((line) => `# ${line}`).join('\n')}\n\n`
    case 'slash':
      return `${lines.map((line) => `// ${line}`).join('\n')}\n\n`
    case 'block':
      return `/*\n${lines.map((line) => ` * ${line}`).join('\n')}\n */\n\n`
    case 'none':
      return ''
  }
}

type CommentStyle = 'hash' | 'slash' | 'block' | 'none'

function commentStyleOf(target: string): CommentStyle {
  const name = target.slice(target.lastIndexOf('/') + 1)
  const extension = name.slice(name.lastIndexOf('.') + 1)
  if (['js', 'mjs', 'cjs', 'ts', 'jsonc', 'json5'].includes(extension)) return 'slash'
  if (['css', 'scss'].includes(extension)) return 'block'
  if (extension === 'json') return 'none'

  return 'hash'
}

export function stubFor(artifact: ConfigArtifact, version: string): string | null {
  if (artifact.stub === undefined) return null
  const relative = `./${artifact.target}`
  switch (artifact.stubKind) {
    case 'reexport':
      return `${headerFor(artifact.stub, version)}export { default } from '${relative}';\n`
    case 'extends-json':
      return `${JSON.stringify({ _generated: `gspot ${version}`, extends: relative }, null, 2)}\n`
    case 'path':
      return `${JSON.stringify(relative)}\n`
    default:
      throw new Error(
        `${artifact.target}: stub_kind \`${artifact.stubKind ?? 'absent'}\` is not one of: ` +
          'reexport, extends-json, path.',
      )
  }
}
