import packageManifest from '../../packages/cli/package.json' with { type: 'json' };
import { rejects } from 'node:assert/strict';
import { join } from 'node:path';
import * as fs from 'node:fs';
import { describe, expect, spyOn, test } from 'bun:test';
import { createFileTree, testdir } from 'testdirs';
import * as programDefinition from '#cli/program.ts';
import * as manifestDefinitions from '#cli/presets/read-manifests.ts';
import { referencePages, writeReferencePages } from '../../docs/reference-pages.ts';

const PAGE =
    '---\ntitle: "Example"\ndescription: "Reference example."\n---\n\n<!-- Generated by bun docs/reference-pages.ts. -->\n\nOriginal content.\n';

describe('reference generation', () => {
    test('an unchanged page retains its bytes and modification time', async () => {
        await using directory = await testdir();
        const pages = new Map([['commands/check.md', PAGE]]);
        await writeReferencePages(directory.path, pages);
        const path = join(directory.path, 'commands/check.md');
        const before = fs.readFileSync(path);
        const modified = fs.statSync(path).mtimeMs;
        await writeReferencePages(directory.path, pages);
        expect(fs.readFileSync(path)).toEqual(before);
        expect(fs.statSync(path).mtimeMs).toBe(modified);
    });

    test('preserves authored content and removes only obsolete marked pages', async () => {
        await using directory = await testdir();
        await createFileTree(directory.path, {
            'authored.md': '# Keep this\n',
            'old.md': PAGE,
            'nested/notes.txt': 'notes',
        });
        await writeReferencePages(directory.path, new Map([['current.md', PAGE]]));
        expect(fs.readFileSync(join(directory.path, 'authored.md'), 'utf8')).toBe('# Keep this\n');
        expect(fs.readFileSync(join(directory.path, 'nested/notes.txt'), 'utf8')).toBe('notes');
        expect(fs.existsSync(join(directory.path, 'old.md'))).toBe(false);
        expect(fs.readFileSync(join(directory.path, 'current.md'), 'utf8')).toContain('Original content.');
    });

    test('does not claim authored pages that quote the generation marker', async () => {
        await using directory = await testdir();
        const authored = `---\ntitle: Authored\n---\n\nExample:\n\n${PAGE}`;
        await createFileTree(directory.path, { 'authored.md': authored });
        await writeReferencePages(directory.path, new Map([['current.md', PAGE]]));
        expect(fs.readFileSync(join(directory.path, 'authored.md'), 'utf8')).toBe(authored);
        await rejects(writeReferencePages(directory.path, new Map([['authored.md', PAGE]])), {
            message: /collides with authored content/u,
        });
        expect(fs.readFileSync(join(directory.path, 'authored.md'), 'utf8')).toBe(authored);
    });

    test('refuses an authored collision before changing any page', async () => {
        await using directory = await testdir();
        await createFileTree(directory.path, { 'first.md': PAGE, 'collision.md': '# Authored\n' });
        await rejects(
            writeReferencePages(
                directory.path,
                new Map([
                    ['first.md', PAGE.replace('Original content.', 'Replacement.')],
                    ['collision.md', PAGE],
                ]),
            ),
            { message: /collides with authored content/u },
        );
        expect(fs.readFileSync(join(directory.path, 'first.md'), 'utf8')).toBe(PAGE);
        expect(fs.readFileSync(join(directory.path, 'collision.md'), 'utf8')).toBe('# Authored\n');
    });

    test('a formatting failure leaves existing output intact', async () => {
        await using directory = await testdir();
        await createFileTree(directory.path, { 'first.md': PAGE });
        await rejects(
            writeReferencePages(
                directory.path,
                new Map([
                    ['first.md', PAGE.replace('Original content.', 'Replacement.')],
                    ['invalid.md', '---\ntitle: "unterminated\n---\n'],
                ]),
            ),
        );
        expect(fs.readFileSync(join(directory.path, 'first.md'), 'utf8')).toBe(PAGE);
        expect(fs.readdirSync(directory.path)).toEqual(['first.md']);
    });

    test('a staged write failure preserves old pages and removes temporary output', async () => {
        await using directory = await testdir();
        await createFileTree(directory.path, { 'first.md': PAGE });
        const write = fs.writeFileSync;
        const failure = spyOn(fs, 'writeFileSync').mockImplementation((path, data, options) => {
            if (String(path).endsWith('/1')) throw new Error('Disk full');
            write(path, data, options);
        });
        try {
            await rejects(
                writeReferencePages(
                    directory.path,
                    new Map([
                        ['first.md', PAGE.replace('Original content.', 'Replacement.')],
                        ['second.md', PAGE],
                    ]),
                ),
                { message: /Disk full/u },
            );
        } finally {
            failure.mockRestore();
        }
        expect(fs.readFileSync(join(directory.path, 'first.md'), 'utf8')).toBe(PAGE);
        expect(fs.readdirSync(directory.path)).toEqual(['first.md']);
    });

    test.each(['../outside.md', '/outside.md', 'C:outside.md', String.raw`nested\outside.md`, 'nested/../outside.md'])(
        'rejects unsafe output %s',
        async (path) => {
            await using directory = await testdir();
            await createFileTree(directory.path, { 'first.md': PAGE });
            await rejects(writeReferencePages(directory.path, new Map([[path, PAGE]])), {
                message: /Invalid reference output path/u,
            });
            expect(fs.readdirSync(directory.path)).toEqual(['first.md']);
            expect(fs.readFileSync(join(directory.path, 'first.md'), 'utf8')).toBe(PAGE);
        },
    );

    test('refuses linked output and linked ancestors without changing external content', async () => {
        await using directory = await testdir();
        await createFileTree(directory.path, { 'outside/keep.md': PAGE, 'reference/first.md': PAGE });
        fs.symlinkSync(join(directory.path, 'outside'), join(directory.path, 'reference/link'), 'dir');
        await rejects(writeReferencePages(join(directory.path, 'reference'), new Map([['first.md', PAGE]])), {
            message: /symbolic link/u,
        });
        await rejects(writeReferencePages(join(directory.path, 'reference/link/child'), new Map([['new.md', PAGE]])), {
            message: /symbolic links/u,
        });
        expect(fs.readFileSync(join(directory.path, 'outside/keep.md'), 'utf8')).toBe(PAGE);
        expect(fs.readdirSync(join(directory.path, 'outside'))).toEqual(['keep.md']);
        expect(fs.readFileSync(join(directory.path, 'reference/first.md'), 'utf8')).toBe(PAGE);
    });
});

test('command reference includes inherited options and nested usage while omitting hidden internals', () => {
    const program = programDefinition.buildProgram();
    const parent = program
        .command('account')
        .description('Inspect an account')
        .option('--region <name>', 'Select a region');
    parent.command('show <name>').description('Show an account');
    parent.command('internal', { hidden: true }).description('Private operation');
    const build = spyOn(programDefinition, 'buildProgram').mockReturnValue(program);
    try {
        const pages = referencePages();
        const nested = pages.get('commands/account/show.md')!;
        expect(nested).toContain('gspot account show [options] <name>');
        expect(nested).toContain('`--region <name>`');
        for (const flag of ['--json', '--quiet', '--verbose', '--no-color', '-C <dir>']) {
            expect(nested.split(`| \`${flag}\` |`)).toHaveLength(2);
        }
        expect(pages.has('commands/account/internal.md')).toBe(false);
        expect(pages.get('commands/check.md')).not.toContain('--message-file');
    } finally {
        build.mockRestore();
    }
});

test('identical setting definitions list every preset owner and global settings remain visible', () => {
    const settings = referencePages().get('settings.md')!;
    const shared = settings.split('\n').find((line) => line.includes('`tools.openapi.produced_by`'))!;
    expect(shared).toContain('/reference/presets/express/');
    expect(shared).toContain('/reference/presets/fastapi/');
    expect(settings).toContain('`require_reasons`');
});

test('conflicting setting definitions stop reference generation', () => {
    const manifests = new Map(manifestDefinitions.presetManifests());
    const fastapi = structuredClone(manifests.get('fastapi')!);
    const setting = fastapi.settings.find((entry) => entry.name === 'tools.openapi.produced_by')!;
    setting.default = 'a conflicting default';
    manifests.set('fastapi', fastapi);
    const definitions = spyOn(manifestDefinitions, 'presetManifests').mockReturnValue(manifests);
    try {
        expect(() => referencePages()).toThrow('Conflicting setting definition: tools.openapi.produced_by');
    } finally {
        definitions.mockRestore();
    }
});

test('generated source links resolve to their actual owner and display the current product version', () => {
    for (const page of referencePages().values()) {
        const owner =
            /^editUrl: "https:\/\/github.com\/stefanionescu\/gspot\/blob\/(?:main|[a-f0-9]{40})\/(.+)"$/mu.exec(
                page,
            )?.[1];
        expect(owner).toBeDefined();
        expect(fs.statSync(join(import.meta.dir, '../..', owner!)).isFile()).toBe(true);
        expect(page).toContain(`gspot ${packageManifest.version} · [Source definition]`);
    }
});
