// The literal values generation reads: names, patterns, limits, and tables.
import { z } from 'zod';
import { DOT_GSPOT } from '#cli/config/platform/locations.ts';
import type { HookName } from '#cli/types/generation/generation.ts';
import ruleLevels from '#cli/config/generation/eslint-levels.json' with { type: 'json' };

/** Compiler flags that add diagnostics without changing module resolution or emitted JavaScript. */
export const RECOMMENDED_OPTIONS = {
    strict: true,
    noUncheckedIndexedAccess: true,
    exactOptionalPropertyTypes: true,
    noImplicitOverride: true,
    noFallthroughCasesInSwitch: true,
};

/** Additional compiler diagnostics required at all. */
export const COMPILER_OPTIONS = {
    ...RECOMMENDED_OPTIONS,
    noFallthroughCasesInSwitch: true,
    noUncheckedIndexedAccess: true,
    noImplicitOverride: true,
    exactOptionalPropertyTypes: true,
};

/** Stable rule membership for generated defaults and required-rule validation. */
export const ESLINT_RULE_LEVELS = z.record(z.string(), z.enum(['recommended', 'all'])).parse(ruleLevels);

export const TRAILING_STAR = /\*$/u;
export const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);
export const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);
export const HTML_EXTENSIONS = new Set(['.md', '.html']);
export const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;
export const GENERATED_HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;
export const HEADER_LINES_CHECKED = 3;
export const GENERATED_HEADER_LINES = ['Generated by gspot {{version}} from gspot.toml. Regenerate: gspot apply.'];
export const CHECKOUT = 'actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5';
export const MISE = 'jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566';
export const CACHE = 'actions/cache@5a3ec84eff668545956fd18022155c47e93e2684';
export const NODE = 'actions/setup-node@820762786026740c76f36085b0efc47a31fe5020';

/** The Node major the generated CI installs gspot with. */
export const NODE_VERSION = '22';
export const RUNNERS: Record<string, string> = { ubuntu: 'ubuntu-24.04', macos: 'macos-15', windows: 'windows-2025' };

/** The days a release must be public before Bun installs it when the policy names no age. */
export const DEFAULT_RELEASE_AGE_DAYS = 7;

/** The seconds in one day, for the age Bun reads. */
export const SECONDS_PER_DAY = 86_400;
export const PACKAGE_JSON_INDENT = 4;
export const LEADING_NEWLINES = /^\n+/u;

export const STYLE_ASSETS = 'kits/general/prose/styles/gspot/';
export const MAX_LINE = /^max: \d+$/mu;
export const LONGER_THAN = /longer than \d+/u;

export const GENERATED_JSON_KEY = '_gspot';
export const TARGET_PLACEHOLDER = /\{target(?:_json)?\}/gu;

/** What a hook prints when the command that runs gspot is missing. */
export const HOOK_UNAVAILABLE = 'The command that runs gspot is not installed. Install gspot, then run: gspot install';

// Every file gspot writes keeps LF, so a CRLF checkout does not mark the generated files and hooks as changed.
export const GIT_ATTRIBUTES_BLOCK = [
    `${DOT_GSPOT}/** linguist-generated`,
    `${DOT_GSPOT}/** text eol=lf`,
    '.gitignore text eol=lf',
    '.gitattributes text eol=lf',
].join('\n');
export const HOOK_ARGS: Record<HookName, string> = {
    'pre-commit': 'check --staged',
    'pre-push': 'check --push -- "$@"',
    'commit-msg': 'check --message-file "$1"',
};
export const RUNNER_EXEC: Record<string, string> = {
    mise: 'mise exec -- gspot',
    bun: 'bun run --no-install gspot',
    npm: 'npm exec --no -- gspot',
    pnpm: 'pnpm exec gspot',
    yarn: 'yarn exec gspot',
};

/** The Vale input mode, source grammar, and comment format for each file extension. */
// Known source grammars parse Markdown inside comments. Module extensions without a native grammar use stdin
// with the corresponding language extension. Other comment-compatible formats are mapped through [formats].
export const PROSE_GRAMMARS: Record<string, { mode: 'path' | 'stdin'; extension: string; format?: string }> = {
    '.md': { mode: 'path', extension: '.md' },
    '.mdx': { mode: 'path', extension: '.md' },
    '.ts': { mode: 'path', extension: '.ts', format: 'md' },
    '.tsx': { mode: 'path', extension: '.ts', format: 'md' },
    '.mts': { mode: 'stdin', extension: '.ts' },
    '.cts': { mode: 'stdin', extension: '.ts' },
    '.js': { mode: 'path', extension: '.js', format: 'md' },
    '.mjs': { mode: 'stdin', extension: '.js' },
    '.cjs': { mode: 'stdin', extension: '.js' },
    '.jsx': { mode: 'path', extension: '.js', format: 'md' },
    '.swift': { mode: 'path', extension: '.swift', format: 'md' },
    '.py': { mode: 'path', extension: '.py', format: 'md' },
    '.css': { mode: 'path', extension: '.css', format: 'md' },
    '.sh': { mode: 'path', extension: '.sh', format: 'py' },
    '.bash': { mode: 'path', extension: '.bash', format: 'py' },
    '.zsh': { mode: 'path', extension: '.zsh', format: 'py' },
    '.sql': { mode: 'path', extension: '.sql', format: 'lua' },
    '.pgsql': { mode: 'path', extension: '.pgsql', format: 'lua' },
    '.psql': { mode: 'path', extension: '.psql', format: 'lua' },
};

/** URLs and documentation-tag syntax are code. Tag descriptions and suppression reasons remain prose. */
export const TOKEN_IGNORES = [
    String.raw`(https?://[^\s)]+)`,
    String.raw`(@(?:param|template|typedef)\s+(?:\{[^}\n]*\}\s+)?(?:\[[^\]\n]*\]|\S+))`,
    String.raw`(@(?:returns?|throws|type|see|example|deprecated)\b(?:\s+\{[^}\n]*\})?)`,
];

/** Front matter is not prose. */
export const BLOCK_IGNORES = [String.raw`(?s)^---\n.*?\n---\n`];

export const GSPOT_STYLE = 'gspot';

/** Maps the three documentation length rules to their limit keys. */
export const LENGTH_RULES: Record<string, string> = {
    'sentence-length': 'docs.sentence_words',
    'item-length': 'docs.list_item_words',
    'paragraph-length': 'docs.paragraph_sentences',
};

export const MANAGED_BLOCK_START = '<!-- >>> gspot managed >>> -->';
export const MANAGED_BLOCK_END = '<!-- <<< gspot managed <<< -->';
export const HASH_BLOCK_START = '# >>> gspot managed >>>';
export const HASH_BLOCK_END = '# <<< gspot managed <<<';

export const HOOK_FILES = ['pre-commit', 'pre-push', 'commit-msg'] as const;

export const MISE_CONFIG_PATH = '.mise/conf.d/gspot-tools.toml';
export const MISE_MIN_VERSION = '2026.8.8';
