export const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);

export const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);

export const HTML_EXTENSIONS = new Set(['.md', '.html']);

export const GENERATED_HEADER_LINES = ['Generated by gspot {{version}} from gspot.toml. Regenerate: gspot apply.'];
