// Generated by gspot 0.1.0 from gspot.toml. Regenerate: gspot apply.
export default {
    config: JSON.parse("{\"default\":true,\"MD007\":{\"indent\":4},\"MD013\":false,\"MD024\":{\"siblings_only\":true},\"MD025\":{\"front_matter_title\":\"\"},\"MD033\":false,\"MD041\":true,\"MD046\":{\"style\":\"fenced\"},\"MD048\":{\"style\":\"backtick\"},\"MD049\":{\"style\":\"underscore\"},\"MD050\":{\"style\":\"asterisk\"},\"MD060\":false}"),
    noBanner: true,
    noProgress: true,
    outputFormatters: [[({ results, logMessage }) => logMessage(JSON.stringify(results))]],
};
