// Planted repository for the rust preset: hand-made layout, an unwrap, a crate with no license, and an advisory.
import { join } from 'node:path';
import { createFixture } from 'fs-fixture';
import type { PlantedCase } from '#types/run.ts';
import { describe, expect, test } from 'bun:test';
import { chmodSync, mkdirSync, rmSync } from 'node:fs';
import { commitAll, install, PLANTED_TIMEOUT_MS, run, runPlanted, toolsPath } from '#tests/harness/planted.ts';

const INIT = [
    'init',
    '--yes',
    '--presets',
    'rust',
    '--without',
    'naming,spelling',
    '--runner',
    'none',
    '--ci',
    'none',
    '--hooks',
    'none',
    '--no-rules',
    '--no-install',
];
const RUNS = 0o755;
const crate = (license: string): string =>
    `[package]\nname = "planted"\nversion = "1.0.0"\nedition = "2021"\n${license}\n[dependencies]\n`;
const LOCK = '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "planted"\nversion = "1.0.0"\n';
const CLEAN = '//! Arithmetic the planted tests call.\n\n/// Doubles a number.\n#[must_use]\npub fn double(value: i32) -> i32 {\n    value * 2\n}\n';
const UNWRAPPED = `${CLEAN}\n/// Reads a number and gives up loudly.\n///\n/// # Panics\n///\n/// When the text is no number.\n#[must_use]\npub fn parsed(text: &str) -> i32 {\n    text.parse().unwrap()\n}\n`;
// What cargo audit --json prints for one advisory, cut down to the keys the check reads.
const ADVISORY = JSON.stringify({
    vulnerabilities: {
        found: true,
        count: 1,
        list: [
            {
                advisory: { id: 'RUSTSEC-2020-0071', title: 'Potential segfault in the time crate' },
                package: { name: 'time', version: '0.1.43' },
                versions: { patched: ['>=0.2.23'] },
            },
        ],
    },
});
const SCANNER = `#!/bin/sh\ncat <<'REPORT'\n${ADVISORY}\nREPORT\nexit 1\n`;

const CASES: PlantedCase[] = [
    {
        id: 'rust/rustfmt',
        files: { 'src/lib.rs': `${CLEAN}\nmod wide;\n`, 'src/wide.rs': 'pub fn wide( value:i32 )->i32 { value }\n' },
        expected: 'not formatted the way rustfmt formats it',
    },
    { id: 'rust/clippy', files: { 'src/lib.rs': UNWRAPPED }, expected: 'clippy::unwrap_used' },
    { id: 'rust/cargo-deny', files: { 'Cargo.toml': crate('') }, expected: 'unlicensed' },
];

describe('the rust preset', () => {
    test(
        'rustfmt, Clippy and cargo-deny fire on their planted defects',
        async () => {
            await using fixture = await createFixture({
                '.gitignore': 'target\n',
                'Cargo.toml': crate('license = "MIT"\n'),
                'Cargo.lock': LOCK,
                'src/lib.rs': CLEAN,
            });
            commitAll(fixture.path);
            const environment = { PATH: toolsPath(['cargo-audit', 'cargo-deny', 'typos', 'ec']) };
            await install(fixture.path, INIT, environment);
            for (const planted of CASES) {
                const clean = run(fixture.path, ['check', planted.id, '--no-cache'], environment);
                expect(clean.code, `${planted.id}: ${clean.stdout}${clean.stderr}`).toBe(0);
                const outcome = await runPlanted(fixture.path, planted, environment);
                expect(outcome.code, `${planted.id}: ${outcome.stdout}${outcome.stderr}`).toBe(1);
                expect(outcome.stdout + outcome.stderr, planted.id).toContain(planted.expected);
            }
        },
        PLANTED_TIMEOUT_MS * 10,
    );

    test(
        'an advisory that names a crate in Cargo.lock is a finding with the patched version',
        async () => {
            await using fixture = await createFixture({
                '.gitignore': 'target\n',
                'Cargo.toml': crate('license = "MIT"\n'),
                'Cargo.lock': LOCK,
                'src/lib.rs': CLEAN,
            });
            // The real scanner needs the network and a vulnerable crate, so a script prints what it prints.
            await using tools = await createFixture({});
            const bin = join(tools.path, 'bin');
            mkdirSync(bin);
            await Bun.write(join(bin, 'cargo-audit'), SCANNER);
            chmodSync(join(bin, 'cargo-audit'), RUNS);
            commitAll(fixture.path);
            const environment = { PATH: `${bin}:${toolsPath(['cargo-deny', 'typos', 'ec'])}` };
            await install(fixture.path, INIT, environment);
            // The scanner reports on every run, so init holds the finding; without its baseline it is a finding again.
            rmSync(join(fixture.path, '.gspot/baselines/rust.cargo-audit.RUSTSEC-2020-0071.json'));
            const outcome = run(fixture.path, ['check', 'rust/cargo-audit', '--no-cache'], environment);
            expect(outcome.code, outcome.stdout + outcome.stderr).toBe(1);
            expect(outcome.stdout).toContain('time 0.1.43: Potential segfault in the time crate. Patched in >=0.2.23.');
        },
        PLANTED_TIMEOUT_MS * 5,
    );
});
