// uninstall removes what gspot owns, restores originals, and preserves everything else, including after interruption.
import { join } from 'node:path';
import { expect, test } from 'bun:test';
import { createFileTree, testdir } from 'testdirs';
import { emitAll } from '#cli/generation/render.ts';
import { commitAll } from '#tests/support/cli/git.ts';
import { initArgs } from '#tests/support/cli/init.ts';
import { openSession } from '#cli/execution/session.ts';
import { ownershipSchema } from '#cli/lifecycle/journal.ts';
import { applyBlock } from '#cli/lifecycle/managed-blocks.ts';
import { run, runProcess as spawn } from '#tests/support/cli/command.ts';
import { existsSync, readFileSync, statSync, unlinkSync, writeFileSync } from 'node:fs';

const INIT = initArgs(['bash']);

test('uninstall preview does not create ownership or recovery state', async () => {
    await using directory = await testdir();
    const policy = 'version = 1\nconfigurations = []\n[rules]\ninstall = false\n';
    await createFileTree(directory.path, { 'gspot.toml': policy });
    const preview = await run(directory.path, ['uninstall', '--dry-run']);
    expect(preview.code, preview.stdout + preview.stderr).toBe(0);
    expect(readFileSync(join(directory.path, 'gspot.toml'), 'utf8')).toBe(policy);
    expect(existsSync(join(directory.path, '.gspot'))).toBe(false);
});

test('a fresh Git clone adopts exact generated bytes without changing checkout permissions and preserves authored files on uninstall', async () => {
    await using original = await testdir();
    await using clone = await testdir();
    await createFileTree(original.path, { 'entry.sh': 'echo example\n', '.gspot/authored.txt': 'authored sentinel\n' });
    commitAll(original.path);
    const initialized = await run(original.path, INIT);
    expect(initialized.code, initialized.stdout + initialized.stderr).toBe(0);
    commitAll(original.path);
    const cloned = await spawn(['git', 'clone', '--quiet', '--no-local', original.path, clone.path], {
        cwd: original.path,
    });
    expect(cloned.code, cloned.stderr).toBe(0);
    const config = join(clone.path, '.gspot/config/shellcheckrc');
    const bytes = readFileSync(config);
    expect(statSync(config).mode & 0o777).toBe(0o644);
    const preview = await run(clone.path, ['uninstall', '--dry-run', '--json']);
    expect(preview.code, preview.stdout + preview.stderr).toBe(0);
    expect((JSON.parse(preview.stdout) as { plan: { remove: string[] } }).plan.remove).not.toContain(
        '.gspot/config/shellcheckrc',
    );
    const applied = await run(clone.path, ['apply', '--json']);
    expect(applied.code, applied.stdout + applied.stderr).toBe(0);
    expect(
        (JSON.parse(applied.stdout) as { notes: string[] }).notes.filter((note) => note.includes('shellcheckrc')),
    ).toStrictEqual([]);
    expect(readFileSync(config)).toStrictEqual(bytes);
    expect(statSync(config).mode & 0o777).toBe(0o644);
    const repeated = await run(clone.path, ['apply', '--json']);
    expect(repeated.code, repeated.stdout + repeated.stderr).toBe(0);
    expect((JSON.parse(repeated.stdout) as { written: string[] }).written).toStrictEqual([]);
    const unchanged = await spawn(['git', 'diff', '--exit-code'], { cwd: clone.path });
    expect(unchanged.code, unchanged.stdout + unchanged.stderr).toBe(0);
    const removed = await run(clone.path, ['uninstall', '--yes']);
    expect(removed.code, removed.stdout + removed.stderr).toBe(0);
    expect(readFileSync(config)).toStrictEqual(bytes);
    expect(statSync(config).mode & 0o777).toBe(0o644);
    expect(readFileSync(join(clone.path, '.gspot/authored.txt'), 'utf8')).toBe('authored sentinel\n');
});

test('untracked exact generated content survives uninstall and later apply adoption', async () => {
    await using directory = await testdir();
    await createFileTree(directory.path, { 'entry.sh': 'echo example\n' });
    const initialized = await run(directory.path, INIT);
    expect(initialized.code, initialized.stdout + initialized.stderr).toBe(0);
    const config = join(directory.path, '.gspot/config/shellcheckrc');
    const bytes = readFileSync(config);
    const mode = statSync(config).mode & 0o777;
    unlinkSync(join(directory.path, '.gspot/state/ownership.json'));
    const preview = await run(directory.path, ['uninstall', '--dry-run', '--json']);
    expect(preview.code, preview.stdout + preview.stderr).toBe(0);
    expect((JSON.parse(preview.stdout) as { plan: { remove: string[] } }).plan.remove).not.toContain(
        '.gspot/config/shellcheckrc',
    );
    const removed = await run(directory.path, ['uninstall', '--yes']);
    expect(removed.code, removed.stdout + removed.stderr).toBe(0);
    expect(readFileSync(config)).toStrictEqual(bytes);
    const applied = await run(directory.path, ['apply']);
    expect(applied.code, applied.stdout + applied.stderr).toBe(0);
    const restored = await run(directory.path, ['uninstall', '--yes']);
    expect(restored.code, restored.stdout + restored.stderr).toBe(0);
    expect(readFileSync(config)).toStrictEqual(bytes);
    expect(statSync(config).mode & 0o777).toBe(mode);
});

test.each([false, true])(
    'uninstall preserves tracked template copies without local ownership (apply first: %s)',
    async (applyFirst) => {
        await using directory = await testdir();
        await createFileTree(directory.path, {
            'gspot.toml': 'version = 1\nconfigurations = ["bash"]\n',
            'entry.sh': 'echo example\n',
        });
        const session = await openSession(directory.path);
        const generated = emitAll(session.policyFiles.policy, session.repository, session.scopes, {
            version: session.version,
            packageManager: session.packageManager,
        });
        const config = generated.files.find((file) => file.path === '.gspot/config/shellcheckrc')!;
        const instructions = generated.blocks.find((block) => block.path === 'AGENTS.md')!;
        const originals = {
            [config.path]: config.content,
            [instructions.path]: applyBlock('Authored instructions.\n', instructions.block, instructions.style),
            '.gspot/version': session.version + '\n',
        };
        await createFileTree(directory.path, originals);
        for (const args of [['init'], ['add', '--force', '.']]) {
            const git = await spawn(['git', ...args], { cwd: directory.path });
            expect(git.code, git.stderr).toBe(0);
        }
        if (applyFirst) {
            const applied = await run(directory.path, ['apply']);
            expect(applied.code, applied.stdout + applied.stderr).toBe(0);
        }
        const removed = await run(directory.path, ['uninstall', '--yes']);
        expect(removed.code, removed.stdout + removed.stderr).toBe(0);
        for (const [path, content] of Object.entries(originals)) {
            expect(readFileSync(join(directory.path, path), 'utf8')).toBe(content);
            expect(statSync(join(directory.path, path)).mode & 0o777).toBe(0o644);
        }
    },
);

test.each(['before', 'after'] as const)(
    'uninstall recovers an interrupted publication %s replacement and removes its recorded output',
    async (point) => {
        await using directory = await testdir();
        await createFileTree(directory.path, { 'entry.sh': 'echo example\n' });
        const initialized = await run(directory.path, INIT);
        expect(initialized.code, initialized.stdout + initialized.stderr).toBe(0);
        const recordPath = join(directory.path, '.gspot/state/ownership.json');
        const state = ownershipSchema.parse(JSON.parse(readFileSync(recordPath, 'utf8')));
        const path = '.gspot/config/shellcheckrc';
        const entry = state.files.find((file) => file.path === path)!;
        state.files = state.files.filter((file) => file.path !== path);
        state.pending = [{ path, after: entry.installed, entry }];
        writeFileSync(recordPath, JSON.stringify(state));
        if (point === 'before') unlinkSync(join(directory.path, path));
        const preview = await run(directory.path, ['uninstall', '--dry-run', '--json']);
        expect(preview.code, preview.stdout + preview.stderr).toBe(0);
        expect((JSON.parse(preview.stdout) as { plan: { remove: string[] } }).plan.remove).toContain(path);
        expect(ownershipSchema.parse(JSON.parse(readFileSync(recordPath, 'utf8'))).pending).toStrictEqual(
            state.pending,
        );
        const removed = await run(directory.path, ['uninstall', '--yes']);
        expect(removed.code, removed.stdout + removed.stderr).toBe(0);
        expect(existsSync(join(directory.path, path))).toBe(false);
        const recovered = ownershipSchema.parse(JSON.parse(readFileSync(recordPath, 'utf8')));
        expect(recovered.pending).toBeUndefined();
        expect(recovered.files.map((file) => file.path)).not.toContain(path);
    },
);
