import { z } from 'zod';

export const HOOK_FILES = ['pre-commit', 'pre-push', 'commit-msg'] as const;

export const LEFTHOOK_MIN_VERSION = '2.0.13';

export const NATIVE_HOOK_MARKERS: Record<string, string> = {
    lefthook: 'call_lefthook run ',
    husky: '. "$(dirname "$0")/h"',
    'simple-git-hooks': 'if [ "$SKIP_SIMPLE_GIT_HOOKS" = "1" ]; then',
    'pre-commit': '# File generated by pre-commit: https://pre-commit.com',
};

export const hooksSchema = z.strictObject({
    tool: z
        .enum(['gspot', 'lefthook', 'husky', 'simple-git-hooks', 'pre-commit'])
        .describe('The tool that owns repository hooks.'),
    push: z
        .enum(['changed', 'all'])
        .default('changed')
        .describe('Check affected paths or the full tree of each pushed revision.'),
});
