export const SHEBANG_INTERPRETERS: Record<string, string> = {
    bash: 'shell',
    bats: 'shell',
    sh: 'shell',
    zsh: 'shell',
    dash: 'shell',
    ksh: 'shell',
    python: 'python',
    python3: 'python',
    node: 'node',
    bun: 'node',
    deno: 'node',
    tsx: 'node',
};

export const GENERATED_BANNERS: RegExp[] = [
    /^\/\/ Generated by gspot/,
    /^# Generated by gspot/,
    /^\{\s*"_gspot":/,
    /@generated\b/,
    /^\/\/ Code generated by .* DO NOT EDIT\./,
    /^\/\*\s*eslint-disable\s*\*\/\s*\n\/\/ This file is auto-generated/,
    /^\/\/ This file was automatically generated/,
    /^\/\/ This file is automatically generated/,
    /^# This file is automatically @generated by/,
    /^# This file was autogenerated by uv/,
    /^\/\/\/ <reference types="@cloudflare\/workers-types/,
    /^\/\/\/ <reference types="next"/,
];

export const LOCKFILE_NAMES = [
    'bun.lock',
    'bun.lockb',
    'package-lock.json',
    'pnpm-lock.yaml',
    'yarn.lock',
    'uv.lock',
    'poetry.lock',
    'Cargo.lock',
    'go.sum',
    'Gemfile.lock',
    'Package.resolved',
    'Podfile.lock',
];

export const BINARY_EXTENSIONS = [
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.webp',
    '.ico',
    '.bmp',
    '.tiff',
    '.heic',
    '.avif',
    '.mp3',
    '.mp4',
    '.mov',
    '.wav',
    '.m4a',
    '.aac',
    '.ogg',
    '.webm',
    '.flac',
    '.ttf',
    '.otf',
    '.woff',
    '.woff2',
    '.eot',
    '.zip',
    '.gz',
    '.tar',
    '.tgz',
    '.bz2',
    '.xz',
    '.7z',
    '.jar',
    '.pdf',
    '.wasm',
    '.so',
    '.dylib',
    '.dll',
    '.exe',
    '.a',
    '.o',
    '.bin',
    '.dat',
    '.db',
    '.sqlite',
    '.pyc',
    '.pyo',
    '.class',
    '.car',
    '.mlmodel',
    '.mlmodelc',
    '.p8',
    '.p12',
    '.cer',
    '.der',
    '.mobileprovision',
];

export const VENDORED_DIRECTORIES = [
    'vendor',
    'third_party',
    'third-party',
    'node_modules',
    'Pods',
    'Carthage',
    '.build',
];

export const HOOK_DIRECTORIES = ['.githooks', '.husky', '.git-hooks'];

export const LINT_FOLDER_NAMES = ['quality', 'lint', 'linting', '.qlty', 'code-quality'];

export const LINT_TOOL_PACKAGE_PREFIXES = [
    'eslint',
    '@eslint',
    '@eslint-community',
    'typescript-eslint',
    '@typescript-eslint',
    'prettier',
    'knip',
    'markdownlint',
    '@commitlint',
    'commitlint',
    'stylelint',
    'syncpack',
    'sort-package-json',
    'license-checker',
    'jscpd',
    'lizard',
    'madge',
    'html-validate',
    'linkinator',
    'purgecss',
    'svgo',
    'squawk-cli',
    'type-coverage',
    'lint-staged',
    'husky',
    'lefthook',
    '@vitest/eslint-plugin',
    'globals',
    'depcheck',
    'cspell',
    'typos',
    'concurrently',
    'supabase',
    'sqlfluff',
];

export const AGENT_FILE_NAMES = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.cursorrules', 'CONVENTIONS.md'];

export const RULES_DIRECTORY_NAMES = ['rules', '.rules', '.cursor/rules', 'docs/rules', '.claude/rules'];

/** License and notice files are another party's text, kept as written. */
export const LICENSE_FILE = /^(?:LICENSE|LICENCE|COPYING|NOTICE)(?:$|[.-])/iu;

/** Files gspot or a tool it drives writes; nobody edits them, so they are generated. */
export const INSTALLED_PREFIXES = [
    '.gspot/rules/',
    '.gspot/config/vale/styles/gspot/',
    '.gspot/config/vale/styles/config/vocabularies/gspot/',
];

/** Where Vale packages land; everything there except the gspot style and vocabulary is vendored. */
export const VALE_STYLES_PREFIX = '.gspot/config/vale/styles/';
export const VALE_OWN_PREFIXES = ['.gspot/config/vale/styles/gspot/', '.gspot/config/vale/styles/config/vocabularies/gspot/'];

/** Recovery and ownership metadata never enter repository checks or generated proposals. */
export const LIFECYCLE_PRIVATE_PATH = /(?:^|\/)\.gspot\/(?:state(?:\/|$)|ownership\.json$|writer\.lock$|recovery(?:\/|$))/iu;
