export const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;

export const GENERATED_HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;

export const HEADER_LINES_CHECKED = 3;

export const GENERATED_JSON_KEY = '_gspot';
