/** Lockfile clients, runner priority, tool projects, and native verification. */
export const LOCKFILES = [
    {
        file: 'bun.lock',
        configuration: 'javascript',
        client: 'bun',
        runner: true,
        toolProject: true,
        parsed: true,
        snapshot: true,
        frozen: ['bun', 'install', '--frozen-lockfile', '--dry-run'],
    },
    { file: 'bun.lockb', configuration: 'javascript', client: 'bun', runner: true },
    {
        file: 'pnpm-lock.yaml',
        configuration: 'javascript',
        client: 'pnpm',
        runner: true,
        toolProject: true,
        parsed: true,
        snapshot: true,
        frozen: ['pnpm', 'install', '--frozen-lockfile', '--lockfile-only'],
    },
    {
        file: 'yarn.lock',
        configuration: 'javascript',
        client: 'yarn',
        runner: true,
        toolProject: true,
        parsed: true,
        snapshot: true,
        frozen: ['yarn', 'install', '--frozen-lockfile', '--ignore-scripts', '--non-interactive'],
    },
    {
        file: 'package-lock.json',
        configuration: 'javascript',
        client: 'npm',
        runner: true,
        toolProject: true,
        parsed: true,
        snapshot: true,
        frozen: ['npm', 'ci', '--dry-run', '--ignore-scripts'],
    },
    { file: 'npm-shrinkwrap.json', configuration: 'javascript', client: 'npm' },
    {
        file: 'uv.lock',
        configuration: 'python',
        client: 'uv',
        parsed: true,
        snapshot: true,
        frozen: ['uv', 'lock', '--check'],
    },
    { file: 'poetry.lock', configuration: 'python', client: 'poetry', parsed: true },
    { file: 'pdm.lock', configuration: 'python', client: 'pdm', parsed: true },
    { file: 'Cargo.lock', client: 'cargo' },
    { file: 'go.sum', client: 'go' },
    { file: 'Gemfile.lock', client: 'bundler' },
    { file: 'Package.resolved', configuration: 'swift', client: 'swift', snapshot: true },
    { file: 'Podfile.lock', client: 'cocoapods' },
] as const;
