import type { FindingCase } from '#tests/types/harness/check-case.ts';
import type { RepositoryScenario } from '#tests/types/harness/repository.ts';

export const WRANGLER =
    '{\n    // The worker of the test site.\n    "name": "example",\n    "compatibility_date": "2026-01-15"\n}\n';

export const TYPES = '// Generated by wrangler.\ninterface Env {}\n';

export const FAKE_WRANGLER = `#!${process.execPath}\nif (process.argv.includes('--version')) console.log('4.0.0');\nelse await Bun.write(process.argv[process.argv.indexOf('types') + 1], "// Generated by wrangler.\\ninterface Env {}\\n");\n`;

/** Authored inputs and configuration selection for this scenario. */
export const REPOSITORY: RepositoryScenario = {
    configurations: ['cloudflare'],
    modules: false,
    installs: false,
    files: {
        'package.json':
            '{\n    "name": "example",\n    "private": true,\n    "devDependencies": { "wrangler": "4.0.0" }\n}\n',
        'node_modules/.bin/wrangler': FAKE_WRANGLER,
        'node_modules/wrangler/package.json': '{\n    "name": "wrangler",\n    "version": "4.0.0"\n}\n',
        'wrangler.jsonc': WRANGLER,
        _headers: '/*\n    X-Frame-Options: DENY\n',
        _redirects: '# Old addresses.\n/old /new 301\n/docs/* https://docs.example.test/:splat 302!\n',
        'functions/hello.js':
            '// Says hello.\n\n/**\n * Answers every request.\n * @returns {Response} the greeting\n */\nexport function onRequest() {\n    return new Response("hello");\n}\n',
    },
};

/** Defects, expected findings, and explicit corrections. */
export const CASES: FindingCase[] = [
    {
        check: 'cloudflare/wrangler',
        files: { 'wrangler.jsonc': '{\n    "name": "example"\n}\n' },
        expected: { file: 'wrangler.jsonc', rule: 'compatibility-date', line: 1 },
    },
    {
        check: 'cloudflare/headers',
        files: { _headers: '    X-Frame-Options: DENY\n/*\n    Referrer-Policy no-referrer\n' },
        expected: { file: '_headers', rule: 'syntax', line: 1 },
    },
    {
        check: 'cloudflare/redirects',
        files: { _redirects: '/old /new 999\n' },
        expected: { file: '_redirects', rule: 'syntax', line: 1 },
    },
    // A tracked types file that differs from what wrangler writes is stale. The test wrangler is a shebang script.
    {
        check: 'cloudflare/types-fresh',
        files: { 'worker-configuration.d.ts': '// Written by hand.\ninterface Env {}\n' },
        expected: { file: 'worker-configuration.d.ts', rule: 'stale', line: 1 },
        platforms: ['darwin', 'linux'],
        corrected: { files: { 'worker-configuration.d.ts': TYPES } },
    },
];
