// The literal values generation reads: names, patterns, limits, and tables.
import type { HookName } from '#cli/types/generation.ts';

export const TRAILING_STAR = /\*$/u;
export const JSON_EXTENSIONS = new Set(['.json', '.webmanifest']);
export const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);
export const HTML_EXTENSIONS = new Set(['.md', '.html']);
export const JSON_HEADER = /^\s*\{\s*"_gspot"\s*:/u;
export const GENERATED_HEADER_LINE = /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/u;
export const HEADER_LINES_CHECKED = 3;
export const GENERATED_HEADER_LINES = ['Generated by gspot {{version}} from gspot.toml. Regenerate: gspot apply.'];
export const CHECKOUT = 'actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5';
export const MISE = 'jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566';
export const CACHE = 'actions/cache@5a3ec84eff668545956fd18022155c47e93e2684';
export const NODE = 'actions/setup-node@820762786026740c76f36085b0efc47a31fe5020';
/** The Node major the generated CI installs gspot with. */
export const NODE_VERSION = '22';
export const RUNNERS: Record<string, string> = { ubuntu: 'ubuntu-24.04', macos: 'macos-15', windows: 'windows-2025' };
/** The days a release must be public before Bun installs it when the policy names no age. */
export const DEFAULT_RELEASE_AGE_DAYS = 7;
/** The seconds in one day, for the age Bun reads. */
export const SECONDS_PER_DAY = 86_400;
export const PACKAGE_JSON_INDENT = 4;
export const LEADING_NEWLINES = /^\n+/u;
export const BARE_KEY = /^[\w-]+$/u;
export const STYLE_ASSETS = 'kits/general/prose/styles/gspot/';
export const MAX_LINE = /^max: \d+$/mu;
export const LONGER_THAN = /longer than \d+/u;
// Line breaks and extglob groups, which EditorConfig sections cannot express.
export const UNREPRESENTABLE_SELECTOR = /[\r\n]|[!+?*@]\(/u;
export const LEADING_GLOBSTARS = /^(?:\*\*\/)+/u;
export const GLOB_GROUPING = /[{}()]/u;
export const GENERATED_JSON_KEY = '_gspot';
export const TARGET_PLACEHOLDER = /\{target(?:_json)?\}/gu;
/** What a hook prints when the command that runs gspot is missing. */
export const HOOK_UNAVAILABLE = 'The command that runs gspot is not installed. Install gspot, then run: gspot install';
// Every file gspot writes keeps LF, so a CRLF checkout does not mark the generated files and hooks as changed.
export const GIT_ATTRIBUTES_BLOCK = [
    '.gspot/** linguist-generated',
    '.gspot/** text eol=lf',
    '.gitignore text eol=lf',
    '.gitattributes text eol=lf',
].join('\n');
export const HOOK_ARGS: Record<HookName, string> = {
    'pre-commit': 'check --staged',
    'pre-push': 'check --push -- "$@"',
    'commit-msg': 'check --stage message --message-file "$1"',
};
export const RUNNER_EXEC: Record<string, string> = {
    mise: 'mise exec -- gspot',
    bun: 'bun run --no-install gspot',
    npm: 'npm exec --no -- gspot',
    pnpm: 'pnpm exec gspot',
    yarn: 'yarn exec gspot',
};
// The files the generated ESLint configuration treats as code, before framework component files join them.
export const ESLINT_CODE_FILES = '**/*.{js,mjs,cjs,jsx,ts,tsx,mts,cts}';
// The Node.js range the Node rules assume when the policy names none.
export const DEFAULT_NODE_VERSION = '>=22.0.0';
// The limits the generated ESLint configuration reads, by the name it gives each one.
export const ESLINT_LIMITS: Record<string, string> = {
    fileLines: 'file_lines',
    functionLines: 'function_lines',
    parameters: 'function_parameters',
    cyclomatic: 'cyclomatic_complexity',
    cognitive: 'cognitive_complexity',
    depth: 'nested_blocks',
    statements: 'statements',
    nestedCallbacks: 'nested_callbacks',
    identicalFunctions: 'identical_functions',
    barrelReexports: 'barrel_reexports',
    trivialStatements: 'trivial_statements',
};
// The limits JavaScript files read on their own, over the TypeScript ones.
export const ESLINT_JAVASCRIPT_LIMITS: Record<string, string> = {
    parameters: 'function_parameters',
    trivialStatements: 'trivial_statements',
};
// The roles import-direction reads from architecture.roles; the types and harness roles also have their own settings.
export const DIRECTION_ROLES = ['tests', 'config', 'env', 'runtime'];
// The files registry-instance-only accepts a registry in, before the configuration folder joins them.
export const REGISTRY_FILES = ['**/registry.ts', '**/registry.tsx', '**/registry.js'];
