// Planted repositories for the hosting platforms: a Cloudflare site and a Supabase project, each broken one way per check.
import { join } from 'node:path';
import { chmodSync } from 'node:fs';
import { plantedCases } from '#tests/harness/planted/cases.ts';
import { GREET, WRANGLER, MIGRATION, SUPABASE_CONFIG } from '#tests/inputs/acceptance/source/kits/kits.ts';

const TYPES = '// Generated by wrangler.\ninterface Env {}\n';
const KEY = ['SUPABASE_SERVICE', 'ROLE_KEY'].join('_');
// A wrangler that answers its version and writes one fixed types file; the real one needs a Cloudflare account.
const FAKE_WRANGLER = `#!${process.execPath}\nif (process.argv.includes('--version')) console.log('4.0.0');\nelse await Bun.write(process.argv.at(-1), ${JSON.stringify(TYPES)});\n`;

plantedCases(
    'the cloudflare configuration',
    {
        kits: ['cloudflare'],
        modules: false,
        without: ['spelling', 'naming', 'security', 'files'],
        files: {
            'package.json':
                '{\n    "name": "planted",\n    "private": true,\n    "devDependencies": { "wrangler": "4.0.0" }\n}\n',
            'node_modules/.bin/wrangler': FAKE_WRANGLER,
            'node_modules/wrangler/package.json': '{\n    "name": "wrangler",\n    "version": "4.0.0"\n}\n',
            'wrangler.jsonc': WRANGLER,
            _headers: '/*\n    X-Frame-Options: DENY\n',
            _redirects: '# Old addresses.\n/old /new 301\n/docs/* https://docs.planted.test/:splat 302!\n',
            'functions/hello.js':
                '// Says hello.\n\n/**\n * Answers every request.\n * @returns {Response} the greeting\n */\nexport function onRequest() {\n    return new Response("hello");\n}\n',
        },
        before: (root) => {
            chmodSync(join(root, 'node_modules/.bin/wrangler'), 0o755);
        },
    },
    [
        {
            check: 'cloudflare/wrangler-config',
            files: { 'wrangler.jsonc': '{\n    "name": "planted"\n}\n' },
            expected: { file: 'wrangler.jsonc', rule: 'compatibility-date', line: 1 },
        },
        {
            check: 'cloudflare/headers-syntax',
            files: { _headers: '    X-Frame-Options: DENY\n/*\n    Referrer-Policy no-referrer\n' },
            expected: { file: '_headers', rule: 'headers-syntax', line: 1 },
        },
        {
            check: 'cloudflare/redirects-syntax',
            files: { _redirects: '/old /new 999\n' },
            expected: { file: '_redirects', rule: 'redirects-syntax', line: 1 },
        },
        // A tracked types file that differs from what wrangler writes is stale. The planted wrangler is a shebang script.
        {
            check: 'cloudflare/env-types-fresh',
            files: { 'cloudflare-env.d.ts': '// Written by hand.\ninterface Env {}\n' },
            expected: { file: 'cloudflare-env.d.ts', rule: 'stale-types', line: 1 },
            platforms: ['darwin', 'linux'],
            corrected: { files: { 'cloudflare-env.d.ts': TYPES } },
        },
    ],
);

plantedCases(
    'the supabase configuration',
    {
        kits: ['supabase'],
        modules: false,
        without: ['naming', 'spelling', 'typescript', 'security'],
        tools: ['deno', 'squawk', 'sqlfluff'],
        files: {
            'supabase/config.toml': SUPABASE_CONFIG,
            'supabase/migrations/20240101000000_create_avatars.sql': MIGRATION,
            'supabase/functions/greet/index.ts': GREET,
        },
    },
    [
        {
            check: 'supabase/config',
            files: { 'supabase/config.toml': `${SUPABASE_CONFIG}\n[functions.missing]\nverify_jwt = true\n` },
            expected: { file: 'supabase/config.toml', rule: 'function', line: 1 },
        },
        {
            check: 'supabase/config',
            files: { 'supabase/config.toml': 'project_id = \n' },
            expected: { file: 'supabase/config.toml', rule: 'parse', line: 1 },
        },
        {
            check: 'supabase/storage-policies',
            files: { 'supabase/config.toml': `${SUPABASE_CONFIG}\n[storage.buckets.receipts]\npublic = false\n` },
            expected: { file: 'supabase/config.toml', rule: 'bucket-policy', line: 1 },
        },
        {
            check: 'supabase/migration-names',
            files: { 'supabase/migrations/002-AddThing.sql': 'SELECT 1;\n' },
            expected: { file: 'supabase/migrations/002-AddThing.sql', rule: 'migration-name', line: 1 },
        },
        {
            check: 'supabase/admin-key-containment',
            files: { 'app/client.ts': `export const key = process.env.${KEY};\n` },
            expected: { file: 'app/client.ts', rule: 'admin-key', line: 1 },
        },
        {
            check: 'supabase/deno-lint',
            files: {
                'supabase/functions/greet/index.ts':
                    'var greeting = "hello";\nDeno.serve(() => new Response(greeting));\n',
            },
            expected: { file: 'supabase/functions/greet/index.ts', rule: 'no-var', line: 1 },
        },
        {
            check: 'supabase/deno-check',
            files: {
                'supabase/functions/greet/index.ts':
                    'const count: number = "one";\nDeno.serve(() => new Response(String(count)));\n',
            },
            expected: { file: 'supabase/functions/greet/index.ts', rule: 'deno-check', line: 1 },
        },
    ],
);
