export const INVOCATION_TIMEOUT_MILLISECONDS = 600_000

export const DAEMON_PROBE_TIMEOUT_MILLISECONDS = 10_000

export const OUTPUT_LIMIT_BYTES = 64 * 1024 * 1024

export const SHEBANG_READ_BYTES = 256

export const BINARY_SNIFF_BYTES = 8000

export const BANNER_SEARCH_LINES = 6

export const COVERAGE_DELTA_SAMPLE = 10
