// Render a preset template with the merged settings; prepend the generated-file header.
import { Eta } from 'eta';

import { GENERATED_HEADER_LINES, GENERATED_JSON_KEY } from '#config/markers.ts';
import { readAsset } from '#cli/platform/assets.ts';
import { baseName, extensionOf } from '#cli/platform/paths.ts';
import type { MergedView } from '#cli/policy/merge.ts';
import type { ScopeSelection, Session } from '#cli/run/session.ts';
import type { Policy } from '#types/config.ts';

const eta = new Eta({ autoEscape: false, autoTrim: false, useWith: true, rmWhitespace: false, varName: 'it' });

const HASH_COMMENT_NAMES = new Set([
    '.editorconfig',
    '.prettierignore',
    '.shellcheckrc',
    'shellcheckrc',
    '.swiftformat',
    'swiftformat',
    '.sqlfluff',
    'sqlfluff.cfg',
    '.gitignore',
    'Dockerfile',
]);
const HASH_COMMENT_EXTENSIONS = new Set([
    '.toml',
    '.yml',
    '.yaml',
    '.ini',
    '.cfg',
    '.txt',
    '.conf',
    '.sh',
    '.py',
    '.rc',
]);
const SLASH_COMMENT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsonc', '.json5']);

export type TemplateData = {
    version: string;
    scope: string;
    scopes: { path: string; presets: string[] }[];
    presets: string[];
    policy: Policy;
    view: MergedView;
    format: MergedView['format'];
    settings: Record<string, unknown>;
    fragments: string;
    tool: (name: string) => Record<string, unknown>;
    toolEnabled: (name: string) => boolean;
    limit: (key: string, language?: string) => number | undefined;
    rulesOff: (check: string) => string[];
    ignoresFor: MergedView['ignoresFor'];
    extra: (name: string) => Record<string, unknown> | undefined;
    json: (value: unknown, indent?: number) => string;
    tomlString: (value: string) => string;
    has: (preset: string) => boolean;
    files: (extension: string) => string[];
    header: string;
    headerLines: string[];
};

/** The header lines for a version. */
export function headerLines(version: string): string[] {
    return GENERATED_HEADER_LINES.map((line) => line.replace('{{version}}', version));
}

/** The header as a comment for a target path, or '' for JSON, which carries it as a key. */
export function headerFor(path: string, version: string): string {
    const base = baseName(path);
    const ext = extensionOf(path);
    const lines = headerLines(version);
    if (ext === '.json' || ext === '.webmanifest') return '';
    if (SLASH_COMMENT_EXTENSIONS.has(ext)) return `${lines.map((line) => `// ${line}`).join('\n')}\n`;
    if (ext === '.md' || ext === '.html') return `<!--\n${lines.map((line) => `  ${line}`).join('\n')}\n-->\n`;
    if (ext === '.sql') return `${lines.map((line) => `-- ${line}`).join('\n')}\n`;
    if (HASH_COMMENT_NAMES.has(base) || HASH_COMMENT_EXTENSIONS.has(ext) || ext === '' || base.startsWith('.'))
        return `${lines.map((line) => `# ${line}`).join('\n')}\n`;
    return `${lines.map((line) => `# ${line}`).join('\n')}\n`;
}

/** True when a text opens with the generated header (any version): in its first three lines, or as the first JSON key. */
export function carriesHeader(text: string): boolean {
    const lines = text.split('\n', 4).slice(0, 3);
    if (lines.some((line) => /^(?:#|\/\/|--|<!--|\s{2})\s*Generated by gspot \d/.test(line))) return true;
    return /^\{\s*"_gspot"\s*:/.test(text.replace(/^\s+/, '')) && text.includes(`"${GENERATED_JSON_KEY}"`);
}

/** Puts the header into rendered JSON as the first key. */
export function withJsonHeader(rendered: string, version: string): string {
    const data = JSON.parse(rendered) as Record<string, unknown>;
    const ordered: Record<string, unknown> = { [GENERATED_JSON_KEY]: headerLines(version).join(' ') };
    for (const [key, value] of Object.entries(data)) if (key !== GENERATED_JSON_KEY) ordered[key] = value;
    return `${JSON.stringify(ordered, null, 4)}\n`;
}

/** The data every template sees. */
export function templateData(session: Session, selection: ScopeSelection, fragments = ''): TemplateData {
    const { view } = selection;
    const files = (extension: string) =>
        session.repository.files
            .filter((file) => file.path.endsWith(extension) && file.nature === 'source')
            .map((file) => file.path);
    return {
        version: session.version,
        scope: selection.scope.path,
        scopes: session.scopes
            .filter((entry) => entry.scope.path !== '')
            .map((entry) => ({
                path: entry.scope.path,
                presets: entry.selected.map((manifest) => manifest.preset.id),
            })),
        presets: view.presets,
        policy: session.loaded.policy,
        view,
        format: view.format,
        settings: view.settings,
        fragments,
        tool: view.tool,
        toolEnabled: view.toolEnabled,
        limit: view.limit,
        rulesOff: view.rulesOff,
        ignoresFor: view.ignoresFor,
        extra: view.extra,
        json: (value, indent = 4) => JSON.stringify(value, null, indent),
        tomlString: (value) => JSON.stringify(value),
        has: (preset) => view.presets.includes(preset),
        files,
        header: headerFor('x.toml', session.version),
        headerLines: headerLines(session.version),
    };
}

/** Renders template text with data. */
export function renderText(template: string, data: TemplateData): string {
    return eta.renderString(template, data);
}

/** Renders a preset template asset to the final text of a target, header included unless the target's reader refuses unknown keys. */
export function renderTarget(templatePath: string, targetPath: string, data: TemplateData, header = true): string {
    const rendered = renderText(readAsset(templatePath), data);
    const ext = extensionOf(targetPath);
    if (ext === '.json' || ext === '.webmanifest') {
        if (!header) return `${JSON.stringify(JSON.parse(rendered), null, 4)}\n`;
        return withJsonHeader(rendered, data.version);
    }
    if (!header) return rendered.replace(/^\n+/, '');
    const body = rendered.replace(/^\n+/, '');
    return `${headerFor(targetPath, data.version)}${body.endsWith('\n') ? body : `${body}\n`}`;
}
