import { join } from 'node:path';
import * as spawn from '#cli/platform/spawn.ts';
import { createFileTree, testdir } from 'testdirs';
import { afterEach, expect, spyOn, test } from 'bun:test';
import { swiftBuild, swiftPeriphery } from '#cli/checks/swift/build.ts';
import { removeBuildFolders, swiftInput } from '#tests/support/cli/swift.ts';
import { existsSync, mkdirSync, readFileSync, statSync, symlinkSync, writeFileSync } from 'node:fs';

afterEach(() => {
    removeBuildFolders();
});

test('Swift build side effects stay in the source copy and do not become later inputs', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, {
        'gspot.toml': 'version = 1\nconfigurations = ["swift"]\n',
        'Sources/Value.swift': 'let value = 1\n',
    });
    const original = join(sandbox.path, 'Sources/Value.swift');
    const initial = await swiftInput(sandbox.path, 'swift/build');
    const next = await swiftInput(sandbox.path, 'swift/build');
    const mode = statSync(original).mode;
    let calls = 0;
    const run = spyOn(spawn, 'run').mockImplementation(async (_argv, options) => {
        const cwd = options.cwd;
        expect(cwd).not.toBe(sandbox.path);
        expect(readFileSync(join(cwd, 'Sources/Value.swift'), 'utf8')).toBe('let value = 1\n');
        expect(existsSync(join(cwd, 'Generated'))).toBe(false);
        expect(existsSync(join(cwd, 'Package.resolved'))).toBe(false);
        mkdirSync(join(cwd, 'Generated'));
        symlinkSync('Generated', join(cwd, 'generated-link'), 'dir');
        writeFileSync(join(cwd, 'Generated/side-effect'), 'generated');
        writeFileSync(join(cwd, 'Package.resolved'), 'generated resolution');
        writeFileSync(join(cwd, 'Sources/Value.swift'), 'modified by build');
        calls += 1;
        return { code: 0, stdout: '', stderr: '', missing: false, duration: 1 };
    });
    try {
        expect(await swiftBuild(initial)).toStrictEqual([]);
        expect(await swiftBuild(next)).toStrictEqual([]);
        expect(calls).toBe(2);
        expect(readFileSync(original, 'utf8')).toBe('let value = 1\n');
        expect(statSync(original).mode).toBe(mode);
        expect(existsSync(join(sandbox.path, 'Package.resolved'))).toBe(false);
        expect(existsSync(join(sandbox.path, 'Generated'))).toBe(false);
    } finally {
        run.mockRestore();
    }
});

test('Periphery build side effects stay in its source copy and findings name original source paths', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, {
        'gspot.toml': 'version = 1\nconfigurations = ["swift"]\n',
        'Main.swift': 'let unused = 1\n',
    });
    const input = await swiftInput(sandbox.path, 'swift/periphery');
    const run = spyOn(spawn, 'run').mockImplementation(async (_argv, options) => {
        const cwd = options?.cwd;
        if (cwd === undefined) throw new Error('Periphery requires a working directory.');
        expect(cwd).not.toBe(sandbox.path);
        expect(readFileSync(join(cwd, 'Main.swift'), 'utf8')).toBe('let unused = 1\n');
        writeFileSync(join(cwd, 'Package.resolved'), 'generated by the build');
        return {
            code: 1,
            stdout: `${cwd}/Main.swift:1:5: warning: Property unused is unused`,
            stderr: '',
            missing: false,
            duration: 1,
        };
    });
    try {
        expect(await swiftPeriphery(input)).toMatchObject([{ file: 'Main.swift', line: 1, column: 5, rule: 'unused' }]);
        expect(existsSync(join(sandbox.path, 'Package.resolved'))).toBe(false);
        expect(readFileSync(join(sandbox.path, 'Main.swift'), 'utf8')).toBe('let unused = 1\n');
    } finally {
        run.mockRestore();
    }
});

test('concurrent Swift compilation and Periphery retain separate source and artifact directories', async () => {
    await using sandbox = await testdir();
    await createFileTree(sandbox.path, { 'gspot.toml': 'version = 1\nconfigurations = ["swift"]\n' });
    const compile = await swiftInput(sandbox.path, 'swift/build');
    const periphery = await swiftInput(sandbox.path, 'swift/periphery');
    const started = Promise.withResolvers<void>();
    const directories: string[] = [];
    const run = spyOn(spawn, 'run').mockImplementation(async (_argv, options) => {
        const cwd = options?.cwd;
        if (cwd === undefined) throw new Error('The build requires a working directory.');
        directories.push(cwd);
        if (directories.length === 2) started.resolve();
        await started.promise;
        return { code: 0, stdout: '', stderr: '', missing: false, duration: 1 };
    });
    try {
        expect(await Promise.all([swiftBuild(compile), swiftPeriphery(periphery)])).toStrictEqual([[], []]);
        expect(new Set(directories).size).toBe(2);
    } finally {
        started.resolve();
        run.mockRestore();
    }
});

test.each(['../External.xcodeproj', '/External.xcodeproj', 'C:External.xcodeproj', String.raw`..\External.xcodeproj`])(
    'Xcode project %s cannot redirect an isolated build outside the scope',
    async (project) => {
        await using sandbox = await testdir();
        await createFileTree(sandbox.path, {
            'gspot.toml': `version = 1\nconfigurations = ["swift", "xcode"]\n[tools.xcode]\nproject = ${JSON.stringify(project)}\nscheme = "Example"\n`,
        });
        const input = await swiftInput(sandbox.path, 'swift/build');
        writeFileSync(
            join(sandbox.path, 'gspot.toml'),
            'version = 1\nconfigurations = ["swift", "xcode"]\n[tools.xcode]\nproject = "Example.xcodeproj"\nscheme = "Example"\n',
        );
        const corrected = await swiftInput(sandbox.path, 'swift/build');
        const run = spyOn(spawn, 'run').mockResolvedValue({
            code: 0,
            stdout: '',
            stderr: '',
            missing: false,
            duration: 1,
        });
        try {
            await expect(swiftBuild(input)).rejects.toThrow('Unsafe lifecycle path');
            expect(run).not.toHaveBeenCalled();
            expect(await swiftBuild(corrected)).toStrictEqual([]);
        } finally {
            run.mockRestore();
        }
    },
);
