import { realpathSync } from 'node:fs';
import { AsyncLocalStorage } from 'node:async_hooks';
import { openRoot } from '#cli/platform/filesystem.ts';
import { ownershipSchema } from '#cli/lifecycle/log.ts';
import { openLog } from '#cli/lifecycle/ownership/log.ts';
import type { FileObservation } from '#cli/types/platform.ts';
import { fileMode, mutationTarget } from '#cli/platform/safe-paths.ts';
import { proposeRestoration } from '#cli/lifecycle/ownership/restoration.ts';
import { applyProposal, applyProposals } from '#cli/lifecycle/ownership/apply.ts';
import type { Log, Owner, OwnershipState } from '#cli/types/lifecycle/lifecycle.ts';
import { READ_ONLY_FILE, STATE_DIRECTORY, OWNER_WRITABLE_FILE } from '#cli/config/platform.ts';

import {
    proposeBlock,
    proposeRetirement,
    proposeReplacement,
    proposeConfiguration,
} from '#cli/lifecycle/ownership/proposals.ts';

const activeMutation = new AsyncLocalStorage<Map<string, Owner>>();
// The owner's operations over an open log.
function lifecycleOwner(log: Log): Owner {
    const { state, files } = log;
    return {
        beginInstallation(kind) {
            state.installations = [...new Set([...(state.installations ?? []), kind])];
            log.save();
        },
        finishInstallation(kind) {
            if (state.installations?.includes(kind) !== true)
                throw new Error('Installation recovery state changed. Retry gspot install.');
            state.installations = state.installations.filter((entry) => entry !== kind);
            if (state.installations.length === 0) delete state.installations;
            log.save();
        },
        proposeConfiguration: (path, format, changes, replace) =>
            proposeConfiguration(log, path, format, changes, replace),
        applyProposal: (proposal) => applyProposal(log, proposal),
        applyProposals: (proposals) => applyProposals(log, proposals),
        proposeBlock: (path, body, style) => proposeBlock(log, path, body, style),
        replaceBlock: (path, body, style) => applyProposal(log, proposeBlock(log, path, body, style)),
        read(path) {
            mutationTarget(path);
            return files.read(path);
        },
        paths: () => state.files.map((entry) => entry.path),
        proposeReplacement: (path, next, kind, replace, expected, proposed) =>
            proposeReplacement(log, { path, next, kind, replace, expected, proposed }),
        replace: (path, next, kind, replace, expected) =>
            applyProposal(log, proposeReplacement(log, { path, next, kind, replace, expected })),
        installedPaths: () => state.files.filter((entry) => entry.installed !== undefined).map((entry) => entry.path),
        proposeRetirement: (path, expected) => proposeRetirement(log, path, expected),
        proposeRestoration: (path, original) => proposeRestoration(log, path, original),
        restore(path, original) {
            const proposal = proposeRestoration(log, path, original);
            if (proposal.status === 'preserved') return 'preserved';
            applyProposals(log, [proposal]);
            return 'changed';
        },
        close: () => {
            files.close();
        },
    };
}

/**
 * Preserve Git's writable checkout mode when exact generated bytes reproduce a read-only proposal.
 * @param proposed the generated file
 * @param current the file as it is now, or undefined when it does not exist
 * @returns the snapshot to write
 */
export function written(proposed: FileObservation, current: FileObservation | undefined): FileObservation {
    const { bytes } = proposed;
    const mode = fileMode(proposed);
    const checkout =
        mode === READ_ONLY_FILE &&
        current?.mode === fileMode({ mode: OWNER_WRITABLE_FILE }) &&
        current.isLink !== true &&
        current.bytes.equals(bytes);
    return { bytes, mode: checkout ? current.mode : mode };
}

/**
 * Serialize local lifecycle writers and recover their durable ownership log before mutation.
 * @param root the root the owner bounds its writes to
 * @param stateDirectory the directory under the root that holds the log and lock
 * @returns the owner, which the caller closes
 */
export function openOwner(root: string, stateDirectory = STATE_DIRECTORY): Owner {
    const files = openRoot(root);
    try {
        files.lock(`${stateDirectory}/writer.lock`);
        return lifecycleOwner(openLog(files, stateDirectory));
    } catch (error) {
        files.close();
        throw error;
    }
}

/**
 * Reuse active mutation owners and serialize each repository or Git-resolved root.
 * @param root the root the owner bounds its writes to.
 * @param action the work to do with the owner open.
 * @param stateDirectory the directory under the root that holds the log and lock.
 * @returns what the action returns.
 */
export function runOwnedLifecycle<Result>(
    root: string,
    action: (owner: Owner) => Result,
    stateDirectory = STATE_DIRECTORY,
): Result {
    const canonical = realpathSync(root);
    const key = `${canonical}\0${stateDirectory}`;
    const active = activeMutation.getStore();
    const existing = active?.get(key);
    if (existing !== undefined) return action(existing);
    const owner = openOwner(canonical, stateDirectory);
    try {
        const result = activeMutation.run(new Map([...(active ?? []), [key, owner]]), () => action(owner));
        if (result instanceof Promise)
            return result.finally(() => {
                owner.close();
            }) as Result;
        owner.close();
        return result;
    } catch (error) {
        owner.close();
        throw error;
    }
}

/**
 * Read ownership for a preview without creating a lock, directory, or log.
 * @param root the root the ownership belongs to
 * @param stateDirectory the directory under the root that holds the log
 * @returns the recorded ownership, empty when nothing was recorded
 */
export function readOwnership(root: string, stateDirectory = STATE_DIRECTORY): OwnershipState {
    const files = openRoot(root);
    try {
        const record = files.read(`${stateDirectory}/ownership.json`);
        return record === undefined
            ? { version: 1, files: [] }
            : ownershipSchema.parse(JSON.parse(record.bytes.toString('utf8')));
    } finally {
        files.close();
    }
}
