import { realpathSync } from 'node:fs';
import type { Read } from '#cli/types/platform.ts';
import { AsyncLocalStorage } from 'node:async_hooks';
import { openRoot } from '#cli/platform/filesystem.ts';
import { openLog } from '#cli/lifecycle/ownership/log.ts';
import { ownershipSchema } from '#cli/lifecycle/ownership/schema.ts';
import { fileMode, mutationTarget } from '#cli/platform/safe-paths.ts';
import { applyPlan, applyPlans } from '#cli/lifecycle/ownership/apply.ts';
import { proposeClaudeMove } from '#cli/lifecycle/ownership/claude-file.ts';
import { proposeRestoration } from '#cli/lifecycle/ownership/restoration.ts';
import type { Log, Owner, OwnershipState } from '#cli/types/lifecycle/lifecycle.ts';
import { READ_ONLY_FILE, STATE_DIRECTORY, OWNER_WRITABLE_FILE } from '#cli/config/platform.ts';
import { installTree, removeInstallation, recoverInstallations } from '#cli/lifecycle/ownership/installations.ts';

import {
    proposeBlock,
    proposeRetirement,
    proposeReplacement,
    proposeConfiguration,
} from '#cli/lifecycle/ownership/plans.ts';

const activeMutation = new AsyncLocalStorage<Map<string, Owner>>();
// The owner's operations over an open log.
function lifecycleOwner(log: Log): Owner {
    const { state, files } = log;
    return {
        beginInstallation(kind) {
            state.installations = [...new Set([...(state.installations ?? []), kind])];
            log.save();
        },
        finishInstallation(kind) {
            if (state.installations?.includes(kind) !== true)
                throw new Error('Installation recovery state changed. Retry gspot install.');
            state.installations = state.installations.filter((entry) => entry !== kind);
            if (state.installations.length === 0) delete state.installations;
            log.save();
        },
        installTree: (kind, outputs) => {
            installTree(log, kind, outputs);
        },
        removeInstallation: (kind) => {
            removeInstallation(log, kind);
        },
        proposeConfiguration: (path, format, changes, replace) =>
            proposeConfiguration(log, path, format, changes, replace),
        applyPlan: (plan) => applyPlan(log, plan),
        applyPlans: (plans) => applyPlans(log, plans),
        proposeBlock: (path, body, style) => proposeBlock(log, path, body, style),
        replaceBlock: (path, body, style) => applyPlan(log, proposeBlock(log, path, body, style)),
        read(path) {
            mutationTarget(path);
            return files.read(path);
        },
        paths: () => state.files.map((entry) => entry.path),
        proposeReplacement: (path, next, kind, replace, expected, proposed) =>
            proposeReplacement(log, { path, next, kind, replace, expected, proposed }),
        replace: (path, next, kind, replace, expected) =>
            applyPlan(log, proposeReplacement(log, { path, next, kind, replace, expected })),
        installedPaths: () => state.files.filter((entry) => entry.installed !== undefined).map((entry) => entry.path),
        proposeRetirement: (path, expected) => proposeRetirement(log, path, expected),
        proposeRestoration: (path) => proposeRestoration(log, path),
        proposeClaudeMove: () => proposeClaudeMove(log),
        close: () => {
            files.close();
        },
    };
}

/**
 * Preserve Git's writable checkout mode when exact generated bytes reproduce a read-only plan.
 * @param proposed the generated file
 * @param current the file as it is now, or undefined when it does not exist
 * @returns the snapshot to write
 */
export function written(proposed: Read, current: Read | undefined): Read {
    const { bytes } = proposed;
    const mode = fileMode(proposed);
    const checkout =
        mode === READ_ONLY_FILE &&
        current?.mode === fileMode({ mode: OWNER_WRITABLE_FILE }) &&
        current.isLink !== true &&
        current.bytes.equals(bytes);
    return { bytes, mode: checkout ? current.mode : mode };
}

/**
 * Serialize local lifecycle writers and recover their durable ownership log before mutation.
 * @param root the root the owner bounds its writes to
 * @returns the owner, which the caller closes
 */
export function openOwner(root: string): Owner {
    const files = openRoot(root);
    try {
        files.lock(`${STATE_DIRECTORY}/writer.lock`);
        const log = openLog(files, STATE_DIRECTORY);
        recoverInstallations(log);
        return lifecycleOwner(log);
    } catch (error) {
        files.close();
        throw error;
    }
}

/**
 * Reuse active mutation owners and serialize the writers of each repository root.
 * @param root the root the owner bounds its writes to.
 * @param action the work to do with the owner open.
 * @returns what the action returns.
 */
export function runOwnedLifecycle<Result>(root: string, action: (owner: Owner) => Result): Result {
    const canonical = realpathSync(root);
    const active = activeMutation.getStore();
    const existing = active?.get(canonical);
    if (existing !== undefined) return action(existing);
    const owner = openOwner(canonical);
    try {
        const result = activeMutation.run(new Map([...(active ?? []), [canonical, owner]]), () => action(owner));
        if (result instanceof Promise)
            return result.finally(() => {
                owner.close();
            }) as Result;
        owner.close();
        return result;
    } catch (error) {
        owner.close();
        throw error;
    }
}

/**
 * Read ownership for a preview without creating a lock, directory, or log.
 * @param root the root the ownership belongs to
 * @param stateDirectory the directory under the root that holds the log
 * @returns the recorded ownership, empty when nothing was recorded
 */
export function readOwnership(root: string, stateDirectory = STATE_DIRECTORY): OwnershipState {
    const files = openRoot(root);
    try {
        const record = files.read(`${stateDirectory}/ownership.json`);
        return record === undefined
            ? { version: 1, files: [] }
            : ownershipSchema.parse(JSON.parse(record.bytes.toString('utf8')));
    } finally {
        files.close();
    }
}
