import { describe, expect, test } from 'bun:test';
import { hasHeader, headerFor, jsonHeaderAdded, SHIPPED_JSON_FORMAT } from '#cli/emit/templates.ts';

describe('generated-file headers', () => {
    test('use the comment style of the target', () => {
        expect(headerFor('.gspot/eslint.config.js', '0.1.0')).toStartWith(
            '// Generated by gspot 0.1.0 from gspot.toml. Do not edit.',
        );
        expect(headerFor('.gspot/typos.toml', '0.1.0')).toStartWith('# Generated by gspot 0.1.0');
        expect(headerFor('.gspot/prettier.json', '0.1.0')).toBe('');
        expect(jsonHeaderAdded('{"a":1}', '0.1.0', SHIPPED_JSON_FORMAT)).toStartWith(
            '{\n    "_gspot": "Generated by gspot 0.1.0',
        );
    });

    test('hasHeader finds both forms', () => {
        expect(hasHeader('# Generated by gspot 0.1.0 from gspot.toml.\n')).toBe(true);
        expect(hasHeader('{\n  "_gspot": "x"\n}')).toBe(true);
        expect(hasHeader('plain\n')).toBe(false);
    });
});
