// The hook scripts: one per stage, each a shell script that enters the gspot root and runs one check.
import { join } from 'node:path';
import { test, expect } from 'bun:test';
import { gitOutput } from '#tests/harness/git.ts';
import { testdir, createFileTree } from 'testdirs';
import { hookFiles } from '#cli/generation/hooks.ts';
import { buildPolicy } from '#tests/harness/policy.ts';
import { parseStrictPolicy } from '#cli/policy/read.ts';
import { runTestCommand } from '#tests/harness/command.ts';
import { isPosix } from '#tests/config/harness/platforms.ts';
import { RUNNER_CASES } from '#tests/config/cli/generation/hooks.ts';

test.each(RUNNER_CASES)(
    'the hook scripts under the %s runner parse and select one check each',
    async (_label, runner) => {
        await using sandbox = await testdir();
        await createFileTree(sandbox.path, { "app's dir/gspot.toml": 'configurations = []\n' });
        gitOutput(sandbox.path, ['init', '-q']);
        const tables =
            runner === undefined ? '[hooks]\nenabled = true\n' : `runner = "${runner}"\n[hooks]\nenabled = true\n`;
        const policy = parseStrictPolicy(buildPolicy([], { tables: tables }));
        const files = hookFiles(join(sandbox.path, "app's dir"), policy, '1.2.3');
        expect(files.map((file) => file.path)).toStrictEqual([
            '.gspot/hooks/pre-commit',
            '.gspot/hooks/pre-push',
            '.gspot/hooks/commit-msg',
        ]);
        const commands: Record<string, string> = { npm: 'npm exec --no -- gspot', mise: 'mise exec -- gspot' };
        const command = commands[runner ?? ''] ?? 'gspot';
        for (const file of files) {
            expect(file).toMatchObject({ executable: true, kind: 'hook' });
            expect(file.content).toStartWith(
                '#!/bin/sh\n# Generated by gspot 1.2.3 from gspot.toml. Regenerate: gspot apply.\n',
            );
            expect(file.content).toContain(String.raw`cd 'app'\''s dir/' || exit 2`);
            const name = file.path.slice(file.path.lastIndexOf('/') + 1);
            expect(file.content).toContain(`GSPOT_HOOK=${name} exec ${command} check`);
            const path = join(sandbox.path, name);
            await Bun.write(path, file.content);
            const parsed = await runTestCommand(['sh', '-n', path], { cwd: sandbox.path });
            expect(parsed.code, parsed.stderr).toBe(0);
        }
        const commitHook = files.find((file) => file.path.endsWith('commit-msg'))!.content;
        expect(commitHook).toContain('cygpath -w');
        expect(commitHook).toContain('--message-file "$1"');
        expect(files.find((file) => file.path.endsWith('pre-push'))!.content).toContain(
            'check --hook pre-push -- "$@"',
        );
    },
);

test('a repository at the Git top level enters no folder', async () => {
    await using sandbox = await testdir();
    gitOutput(sandbox.path, ['init', '-q']);
    const policy = parseStrictPolicy(buildPolicy([], { tables: '[hooks]\nenabled = true\n' }));
    const files = hookFiles(sandbox.path, policy, '1.2.3');
    expect(files).toHaveLength(3);
    for (const file of files) expect(file.content).not.toContain('\ncd ');
});

test.skipIf(!isPosix)('a hook explains how to acquire a missing Mise runner', async () => {
    await using sandbox = await testdir();
    const policy = parseStrictPolicy(buildPolicy([], { tables: 'runner = "mise"\n[hooks]\nenabled = true\n' }));
    const hook = hookFiles(sandbox.path, policy, '1.2.3').find((file) => file.path.endsWith('pre-push'))!;
    const path = join(sandbox.path, 'pre-push');
    await Bun.write(path, hook.content);
    const result = await runTestCommand(['/bin/sh', path, 'origin', 'https://example.com/repository.git'], {
        cwd: sandbox.path,
        env: { PATH: '' },
        stdin: 'refs/heads/main 123 refs/heads/main 456\n',
    });
    expect(result.code, result.stdout + result.stderr).toBe(2);
    expect(result.stderr).toContain('mise is not installed. Install mise, then run: mise install.');
});
