// Generated by gspot 0.1.0 from gspot.toml. Regenerate: gspot apply.
import { fileURLToPath } from 'node:url';

export default {
    config: { extends: fileURLToPath(new URL('./markdownlint.jsonc', import.meta.url)) },
    noBanner: true,
    noProgress: true,
    outputFormatters: [[({ results, logMessage }) => logMessage(JSON.stringify(results))]],
};
