import { tester } from '#tests/support/plugin/tester.ts';
import { noTrivialFunctions } from '#plugin/rules/no-trivial-functions.ts';

tester().run('no-trivial-functions', noTrivialFunctions, {
    valid: [
        'const base = "root"; const path = file => join(base, file); path("first"); path("second");',
        'function setup(scope) { const path = file => join(scope, file); first(path("a")); second(path("b")); }',
        'const kind = "background"; function worker(value) { return new Worker(value, kind); } worker(first); worker(second);',

        'consume({ onValue: value => write(value) });',
        'const options = { onValue: value => write(value) }; options.onValue(1); consume(options);',
        'const options = { onValue: value => write(value) }; const alias = options; consume(alias);',
        'const options = { onValue: value => write(value) }; consume([options]);',
        'const options = { onValue: value => write(value) }; consume({ ...options });',
        'const options = { onValue: value => write(value) }; const copied = { ...options }; consume(copied);',
        'const options = { nested: { onValue(value) { write(value); } } }; consume(options);',
        'function create() { prepare(); configure(); return { onValue: value => write(value) }; }',

        'function render(template, file) { return template.replaceAll("{{file}}", () => file); } render(first, path); render(second, path);',
        'function readJson(value) { return read(value, "json"); } readJson(first); readJson(second);',
        'function worker(value) { return new Worker(value, "background"); } worker(first); worker(second);',
        'const checks = [value => value.active]; checks.some(check => check(item));',
        '[value => value.active].some(check => check(item));',
        'const checks = [((value) => value.active) as (value: Item) => boolean]; checks.some(check => check(item));',
        'function area(width, height) { return width * height; } area(2, 3); area(4, 5);',
        'const area = (width, height) => width * height; area(2, 3); area(4, 5);',
        'function normalize(path) { return separator === "/" ? path : path.split(separator).join("/"); } normalize(first); normalize(second);',
        'function heading(title) { return `# ${title}`; } heading(first); heading(second);',
        'function schema(properties) { return { type: "object", properties }; } schema(first); schema(second);',
        'function prepare(value) { return store(parse(value)); } prepare(first); prepare(second);',
        'function sort(items) { return items.toSorted((left, right) => left.rank - right.rank); } sort(first); sort(second);',
        '(function count(n) { return n === 0 ? 0 : count(n - 1); })(2);',
        'function count(n) { return n === 0 ? 0 : count(n - 1); } count(2);',
        'const count = (n) => n === 0 ? 0 : count(n - 1); count(2);',
        'const count = function recurse(n) { return n === 0 ? 0 : recurse(n - 1); }; count(2);',
        'function work() { first(); second(); third(); }',
        'function work() { if (ready) { first(); second(); } }',
        { code: 'function work() { first(); second(); }', options: [{ maxStatements: 1 }] },
        'declare function required(): void;',
        'function isText(value: unknown): value is string { return typeof value === "string"; }',
        'function assertText(value: unknown): asserts value is string { if (typeof value !== "string") throw new Error(); }',
        'items.map((item) => item.value);',
        'function process(items) { return items.map(item => { inspect(item); validate(item); return item; }); }',
        'function process(groups) { return groups.map(items => items.map(item => { inspect(item); validate(item); return item; })); }',
        'function process(items) { function visit(item) { inspect(item); validate(item); return item; } return items.map(visit); }',
        'items.filter(function (item) { return item.active; });',
        'items.map(((item) => item.value) as (item: Item) => unknown);',
        'items.map(((item) => item.value)!);',
        'items.map(((item) => item.value) satisfies (item: Item) => unknown);',
        'function callback(value) { return value.active; } items.filter(callback);',
        'const callback = (value) => value.active; items.filter(callback);',
        'function callback() { update(); } on(callback); off(callback);',
        'function callback() { update(); } on(callback); callback();',
        'function callback(a, b) { return a; } consume(callback.length);',
        'class A { constructor(public value: number) {} }',
        'class A { constructor(value: number) { this.value = value; } }',
        'class Failure extends Error { constructor(message: string) { super(message); this.name = "Failure"; } }',
        'class A { get value() { return 1; } }',
        'class A { set value(value) { store(value); } }',
        'class A { @decorate method() { return 1; } }',
        'class A extends B { override method() { return 1; } }',
        'const object = { get value() { return 1; }, set value(value) { store(value); } };',
        'function factory() { setup(); configure(); return () => release(); }',
        'const element = <Button onClick={() => submit()} />;',
        '// eslint-disable-next-line @rule-tester/no-trivial-functions -- reason: External callback requires this signature.\nconst callback = () => 1;',
    ],
    invalid: [
        {
            code: 'const options = { onValue: value => write(value) }; consume({ ...options });\nconst local = { onValue: value => write(value) }; local.onValue(1);',
            errors: [{ messageId: 'trivial', line: 2, column: 26 }],
        },
        ...[
            'const unused = { onValue: value => write(value) };',
            'consume({ [() => write(1)]: 1 });',
            'const { other } = { other: 1, onValue: value => write(value) }; consume(other);',
            'const options = { onValue: value => write(value) }; const alias = options; alias.onValue(1);',
            '({ onValue: value => write(value) }).onValue(1);',
            'const options = { onValue: value => write(value) }; const copied = { ...options }; copied.onValue(1);',
        ].map((code) => ({ code, errors: [{ messageId: 'trivial' as const }] })),

        {
            code: 'const checks = [value => value.active]; checks.some(check => check(item));\nconst local = value => value; local(item);',
            errors: [{ messageId: 'trivial', line: 2, column: 15 }],
        },
        {
            code: 'function count(n) { const count = value => value; return count(n); }',
            errors: [{ messageId: 'trivial' }, { messageId: 'trivial' }],
        },
        {
            code: 'function local() { type Signature = typeof local; return 1; }',
            errors: [{ messageId: 'trivial' }],
        },
        {
            code: 'function count(n) { return n === 0 ? 0 : count(n - 1); }\nfunction local() { return 1; }',
            errors: [{ messageId: 'trivial', line: 2, column: 1 }],
        },
        {
            code: 'items.map((item) => item.value); function local() { return 1; }',
            errors: [{ messageId: 'trivial', line: 1, column: 34, endLine: 1, endColumn: 64 }],
        },
        {
            code: 'function isText(value: unknown): value is string { return typeof value === "string"; } function local() { return 1; }',
            errors: [{ messageId: 'trivial', column: 88 }],
        },
        ...[
            'function empty() {}',
            'function identity(value) { return value; } identity(1);',
            '(() => work())();',
            '[() => work()][0]();',
            '([() => work()] as (() => void)[])[0]();',
            '(function () { return items.map(item => { inspect(item); validate(item); return item; }); })();',
            '((() => items.map(item => { inspect(item); validate(item); return item; })) as () => unknown)();',
            '(function () { work(); })();',
            'const local = () => work(); local();',
            'function local() { return 1; } (local as () => number)();',
            'function local() { return 1; } local!();',
            'function local() { return 1; } (local satisfies () => number)();',
            'export function local() { return 1; }',
            'function local() { return 1; } export { local };',
            'function local() { return 1; } type Signature = typeof local;',
            'const unused = (value) => value;',
            '@decorate class A { method() { return 1; } }',
            'function one() { return 1; }',
            'function process(items) { return items.map(item => item); }',
            'function two() { first(); second(); }',
            'function comments() { /* one */\n\nreturn 1; /* two */ }',
            'const multiline = () => (\n first +\n second\n);',
            'class A { constructor() {} }',
            'class A extends B { constructor() { super(); } }',
            'function manyCallers() { return 1; } manyCallers(); manyCallers();',
            'function forward(value) { return owner(value); } forward(first); forward(second);',
            'function path(base, file) { return join(base, file); } path(first, value); path(second, value);',
            'const base = "root"; function path(base, file) { return join(base, file); } path(first, value); path(second, value);',
            'const base = "root"; const path = file => join(base, file); path("first");',
            'const base = "root"; function read() { return base; } read(); read();',
            'function local(value) { return read(value, "json"); } local(first);',
            '(() => read(value, "json"))();',

            'function identity(value) { return value; } identity(first); identity(second);',
            'function field(value) { return value.field; } field(first); field(second);',
            'function area(width, height) { return width * height; } area(2, 3);',
            'function forward(items) { return items.map(item => item); } forward(first); forward(second);',
            'function typed() { type Value = number; return 1; }',
        ].map((code) => ({ code, errors: [{ messageId: 'trivial' as const }] })),
        {
            code: 'function outer() { function inner() { first(); second(); third(); } }',
            errors: [{ messageId: 'trivial' }],
        },
        {
            code: 'function outer() { function inner() {} }',
            errors: [{ messageId: 'trivial' }, { messageId: 'trivial' }],
        },
        {
            code: 'function three() { first(); second(); third(); }',
            options: [{ maxStatements: 3 }],
            errors: [{ messageId: 'trivial' }],
        },
    ],
});
