// The identify-style tag table: extension to tag, shebang to tag. Literals only.

export const EXTENSION_TAGS: Record<string, string[]> = {
    '.sh': ['shell', 'bash', 'text'],
    '.bash': ['shell', 'bash', 'text'],
    '.zsh': ['shell', 'zsh', 'text'],
    '.bats': ['shell', 'bats', 'text'],
    '.py': ['python', 'text'],
    '.pyi': ['python', 'pyi', 'text'],
    '.js': ['javascript', 'text'],
    '.mjs': ['javascript', 'text'],
    '.cjs': ['javascript', 'text'],
    '.jsx': ['javascript', 'jsx', 'text'],
    '.ts': ['typescript', 'text'],
    '.mts': ['typescript', 'text'],
    '.cts': ['typescript', 'text'],
    '.tsx': ['typescript', 'tsx', 'text'],
    '.swift': ['swift', 'text'],
    '.sql': ['sql', 'text'],
    '.pgsql': ['sql', 'text'],
    '.psql': ['sql', 'text'],
    '.md': ['markdown', 'text'],
    '.mdx': ['markdown', 'text'],
    '.json': ['json', 'text'],
    '.jsonc': ['json', 'jsonc', 'text'],
    '.json5': ['json', 'text'],
    '.yml': ['yaml', 'text'],
    '.yaml': ['yaml', 'text'],
    '.toml': ['toml', 'text'],
    '.ini': ['ini', 'text'],
    '.cfg': ['ini', 'text'],
    '.css': ['css', 'text'],
    '.scss': ['scss', 'text'],
    '.html': ['html', 'text'],
    '.htm': ['html', 'text'],
    '.xml': ['xml', 'text'],
    '.plist': ['plist', 'xml', 'text'],
    '.entitlements': ['plist', 'xml', 'text'],
    '.xcconfig': ['xcconfig', 'text'],
    '.xcstrings': ['json', 'xcstrings', 'text'],
    '.storyboard': ['xml', 'text'],
    '.xib': ['xml', 'text'],
    '.svg': ['svg', 'xml', 'text'],
    '.txt': ['text'],
    '.env': ['dotenv', 'text'],
    '.conf': ['text'],
    '.webmanifest': ['json', 'text'],
};

export const FILENAME_TAGS: Record<string, string[]> = {
    Dockerfile: ['dockerfile', 'text'],
    Makefile: ['makefile', 'text'],
    '.gitignore': ['text'],
    '.gitattributes': ['text'],
    '.editorconfig': ['ini', 'text'],
    '.nvmrc': ['text'],
    '.node-version': ['text'],
    '.python-version': ['text'],
    _headers: ['text'],
    _redirects: ['text'],
    LICENSE: ['text'],
    'LICENSE.md': ['markdown', 'text'],
    CODEOWNERS: ['text'],
};

export const SHEBANG_TAGS: Record<string, string[]> = {
    shell: ['shell', 'executable', 'text'],
    python: ['python', 'executable', 'text'],
    node: ['javascript', 'node', 'executable', 'text'],
};

export const BINARY_SNIFF_BYTES = 8000;
