// Marker strings and header templates gspot writes. Literals only.

export const MANAGED_BLOCK_START = '<!-- >>> gspot managed >>> -->';
export const MANAGED_BLOCK_END = '<!-- <<< gspot managed <<< -->';

export const HASH_BLOCK_START = '# >>> gspot managed >>>';
export const HASH_BLOCK_END = '# <<< gspot managed <<<';

export const GENERATED_HEADER_LINES = [
    'Generated by gspot {{version}} from gspot.toml. Do not edit.',
    'Change policy: gspot set / allow / ignore, or edit gspot.toml, then run: gspot sync',
];

export const GENERATED_JSON_KEY = '_gspot';

export const VERSION_FILE_LINE = '{{version}}\n';

export const SCHEMA_LINE = '#:schema https://gspot.dev/schema/gspot.schema.json';

export const HOOK_HEADER = '# Written by gspot. Run `gspot uninstall` to remove.';

export const INLINE_IGNORE: Record<string, RegExp> = {
    slash: /\/\/\s*gspot-ignore\s+([a-z0-9/-]+)(?:\s+--\s*(.*))?$/,
    hash: /#\s*gspot-ignore\s+([a-z0-9/-]+)(?:\s+--\s*(.*))?$/,
    dash: /--\s*gspot-ignore\s+([a-z0-9/-]+)(?:\s+--\s*(.*))?$/,
    html: /<!--\s*gspot-ignore\s+([a-z0-9/-]+)(?:\s+--\s*(.*?))?\s*-->/,
};

export const COMMENT_STYLE_BY_EXTENSION: Record<string, keyof typeof INLINE_IGNORE> = {
    '.ts': 'slash',
    '.tsx': 'slash',
    '.js': 'slash',
    '.mjs': 'slash',
    '.cjs': 'slash',
    '.jsx': 'slash',
    '.swift': 'slash',
    '.css': 'slash',
    '.scss': 'slash',
    '.py': 'hash',
    '.sh': 'hash',
    '.bash': 'hash',
    '.zsh': 'hash',
    '.toml': 'hash',
    '.yml': 'hash',
    '.yaml': 'hash',
    '.rb': 'hash',
    '.sql': 'dash',
    '.pgsql': 'dash',
    '.psql': 'dash',
    '.md': 'html',
    '.html': 'html',
    '.htm': 'html',
};

export const SUPPRESSION_FORMS: Record<string, RegExp> = {
    'eslint-disable': /eslint-disable(?:-next-line|-line)?\b(?:\s+[\w@/,\s-]+)?(?:\s*--\s*(.+))?/,
    'ts-expect-error': /@ts-expect-error(?::?\s*(.+))?/,
    'ts-ignore': /@ts-ignore(?::?\s*(.+))?/,
    noqa: /#\s*noqa(?::\s*[\w,\s]+)?(?:\s+#?\s*(.+))?/,
    nosec: /#\s*nosec\b(?:\s*[\w,\s]*)?(?:\s+#?\s*(.+))?/,
    'type-ignore': /#\s*type:\s*ignore(?:\[[\w,\s-]+\])?(?:\s+#?\s*(.+))?/,
    'pyright-ignore': /#\s*pyright:\s*ignore(?:\[[\w,\s-]+\])?(?:\s+#?\s*(.+))?/,
    'pragma-no-cover': /#\s*pragma:\s*no cover(?:\s+#?\s*(.+))?/,
    nosemgrep: /nosemgrep(?::\s*[\w.,\s-]+)?(?:\s+(.+))?/,
    'shellcheck-disable': /#\s*shellcheck\s+disable=[\w,]+(?:\s+#?\s*(.+))?/,
    'swiftlint-disable': /swiftlint:disable(?::next|:this|:previous)?\s+[\w\s]+(?:\s*-\s*(.+))?/,
    'lint-justify': /lint:justify\s+(?:reason:\s*)?(.+)/,
    'gspot-ignore': /gspot-ignore\s+[a-z0-9/-]+(?:\s+--\s*(.+))?/,
};
