// What the prose engine sends to Vale and how: the grammars, the packages, the upstream rules gspot turns off, and the shipped vocabulary.

/** File extension to how Vale reads it: by path with its own grammar, or through stdin under a grammar with the same comment marker. */
export const PROSE_GRAMMARS: Record<string, { mode: 'path' | 'stdin'; extension: string }> = {
    '.md': { mode: 'path', extension: '.md' },
    '.mdx': { mode: 'path', extension: '.md' },
    '.ts': { mode: 'path', extension: '.ts' },
    '.tsx': { mode: 'path', extension: '.ts' },
    '.mts': { mode: 'path', extension: '.ts' },
    '.cts': { mode: 'path', extension: '.ts' },
    '.js': { mode: 'path', extension: '.js' },
    '.mjs': { mode: 'path', extension: '.js' },
    '.cjs': { mode: 'path', extension: '.js' },
    '.jsx': { mode: 'path', extension: '.js' },
    '.swift': { mode: 'path', extension: '.swift' },
    '.sh': { mode: 'stdin', extension: '.rb' },
    '.bash': { mode: 'stdin', extension: '.rb' },
    '.zsh': { mode: 'stdin', extension: '.rb' },
    '.py': { mode: 'stdin', extension: '.rb' },
    '.sql': { mode: 'stdin', extension: '.lua' },
    '.pgsql': { mode: 'stdin', extension: '.lua' },
    '.psql': { mode: 'stdin', extension: '.lua' },
};

/** A file with no extension and a shell shebang reads as shell. */
export const SHELL_TAG = 'shell';

/** The upstream style packages, in the order Vale syncs them. */
export const VALE_PACKAGES = ['Google', 'Microsoft', 'write-good', 'proselint', 'alex', 'RedHat', 'Harper'];

/** Upstream rules gspot turns off, each with the reason the template prints. */
export const DISABLED_UPSTREAM_RULES: [string, string][] = [
    ['Vale.Spelling', 'typos owns spelling'],
    ['Google.Spelling', 'typos owns spelling'],
    ['Microsoft.Spelling', 'typos owns spelling'],
    ['RedHat.Spelling', 'typos owns spelling'],
    ['Harper.Spelling', 'typos owns spelling'],
    ['Google.Contractions', 'the rule files ban contractions; this rule asks for them'],
    ['Microsoft.Contractions', 'the rule files ban contractions; this rule asks for them'],
    ['Google.Parens', 'the rule files allow parentheses'],
    ['Google.Passive', 'the rule files allow the passive when the result matters more than the actor'],
    ['Microsoft.Passive', 'the rule files allow the passive when the result matters more than the actor'],
    ['RedHat.PassiveVoice', 'the rule files allow the passive when the result matters more than the actor'],
    ['write-good.Passive', 'the rule files allow the passive when the result matters more than the actor'],
    ['write-good.E-Prime', 'the rule files have no rule against forms of to be'],
    ['Google.Headings', 'gspot.headings owns heading case'],
    ['Microsoft.Headings', 'gspot.headings owns heading case'],
    ['RedHat.Headings', 'gspot.headings owns heading case'],
    ['Microsoft.SentenceLength', 'gspot.sentence-length owns sentence length, from limits.docs.sentence_words'],
    ['RedHat.SentenceLength', 'gspot.sentence-length owns sentence length, from limits.docs.sentence_words'],
    ['Google.Acronyms', 'gspot.acronyms owns acronyms'],
    ['Microsoft.Acronyms', 'gspot.acronyms owns acronyms'],
    ['RedHat.PascalCamelCase', 'identifiers are quoted in code spans, which Vale ignores; the rest are words'],
    ['RedHat.Definitions', 'gspot.acronyms owns the first use of an acronym'],
    ['alex.ProfanityUnlikely', 'it flags execute, kill and abort, which are the words for those actions'],
    ['Harper.ExpandConfiguration', 'config is a reserved word in the naming policy and a path in every repository'],
    ['Google.Semicolons', 'the rule files join clauses with semicolons'],
    ['Microsoft.Semicolon', 'the rule files join clauses with semicolons'],
    [
        'Vale.Terms',
        'the vocabulary accepts spellings; it does not fix case, because preset ids are the lowercase tool names',
    ],
    ['write-good.TooWordy', 'it flags validate, multiple and it is, which are plain words'],
    ['write-good.Weasel', 'gspot.hedging owns hedges; this flags several and tiny'],
    ['RedHat.TermsSuggestions', 'Red Hat product terminology: shell prompt for shell, after for once'],
    ['RedHat.TermsWarnings', 'Red Hat product terminology: might for may, tool for tooling'],
    ['RedHat.TermsErrors', 'Red Hat product terminology: typographical error for typo'],
    ['RedHat.SimpleWords', 'Red Hat word list: many for multiple, has for contains'],
    ['RedHat.CaseSensitiveTerms', 'preset ids are the lowercase tool names: postgres, ssh'],
    ['RedHat.DoNotUseTerms', 'Red Hat word list: it bans overhead and colors'],
    ['RedHat.Hyphens', 'Red Hat spellings: nonzero, noninteractive'],
    ['RedHat.Slash', 'check ids are written check/name'],
    ['RedHat.GitLinks', 'links to GitHub are how tools are cited'],
    ['RedHat.NoGerundsInTitles', 'gspot.headings owns headings; the rule files title sections with gerunds'],
    ['RedHat.ReadabilityGrade', 'text about tools scores as hard reading; the length rules own readability'],
    ['RedHat.UserReplacedValues', 'placeholders are written <kebab-case>'],
    ['RedHat.Using', 'a Red Hat grammar preference'],
    ['RedHat.EmDash', 'gspot.dashes owns dashes'],
    ['RedHat.Symbols', 'an exclamation mark is a character, not a symbol to avoid'],
    ['RedHat.OxfordComma', 'Google.OxfordComma reports the same comma'],
    ['RedHat.RepeatedWords', 'Vale.Repetition reports the same repetition'],
    ['RedHat.Spacing', 'Google.Spacing reports the same spacing'],
    ['RedHat.Ellipses', 'Google.Ellipses reports the same ellipsis'],
    ['Microsoft.Vocab', 'it asks the writer to verify a word against a list instead of stating a rule'],
    ['Microsoft.Terms', 'Microsoft product terminology: personal digital assistant for agent'],
    ['Microsoft.GeneralURL', 'URL is the word'],
    ['Microsoft.QuestionMarks', 'the rule files ask questions in review checklists'],
    ['Microsoft.Adverbs', 'the rule files use adverbs to mark intent: deliberately, silently'],
    ['Microsoft.Accessibility', 'it flags disabled, as in a disabled rule'],
    ['Microsoft.HeadingAcronyms', 'headings name tools by their acronyms'],
    ['Microsoft.HeadingColons', 'gspot.headings owns heading case'],
    ['Microsoft.Uppercase', 'constant and file names appear in prose'],
    ['Microsoft.Wordiness', 'it rewrites extract as remove'],
    ['Microsoft.OxfordComma', 'Google.OxfordComma reports the same comma'],
    ['Microsoft.Ellipses', 'Google.Ellipses reports the same ellipsis'],
    ['Microsoft.Hyphens', 'Google.LyHyphens reports the same hyphen'],
    ['Microsoft.Quotes', 'Google.Quotes reports the same punctuation'],
    ['Microsoft.Plurals', 'Google.OptionalPlurals reports the same plural'],
    ['Microsoft.FirstPerson', 'Google.FirstPerson reports the same pronoun'],
    ['Microsoft.We', 'Google.We reports the same pronoun'],
    ['Microsoft.Foreign', 'Google.Latin reports the same abbreviation'],
    ['Microsoft.Spacing', 'Google.Spacing reports the same spacing'],
    ['Microsoft.Avoid', 'Microsoft word list: it bans backend'],
    ['Microsoft.UIVerbs', 'click and swipe are the verbs for a touch screen and a mouse'],
    ['Microsoft.Auto', 'auto-mocks and auto-retry are the names of the features'],
    ['Google.WordListCase', 'Google product terminology: app for application, preceding for above'],
    ['Google.WordList', 'Google product terminology: command-line tool for CLI'],
    ['Google.Colons', 'it lowercases acronyms after a colon'],
    ['Google.Anthropomorphism', 'a check sees, a tool tells; the rule files describe tools as actors'],
    ['Google.ExcessiveClaims', 'guarantee is a technical word for what a check makes certain'],
    ['Google.Will', 'gspot.future owns the future tense'],
    ['Google.Timeless', 'gspot.present-state owns time words'],
    ['Google.Jargon', 'camel case is the name of the case'],
    ['alex.Condescending', 'obvious, simple and clearly are words the rule files use to state that something is'],
    ['alex.Ablist', 'it flags disabled, as in a disabled rule'],
    ['alex.ProfanityMaybe', 'swallow, trap and abuse are what code does to errors, signals and inputs'],
    ['alex.ProfanityLikely', 'looser is a comparative'],
    ['alex.Race', 'primitive is a type'],
    ['alex.Suicide', 'a process hangs'],
    ['proselint.Typography', 'three dots stay ASCII'],
    ['proselint.Needless', 'oversized and extensible are the words'],
    ['Harper.RoadMap', 'roadmap is one word here'],
    ['Harper.ExpandMemoryShorthands', 'MB and GB are the units'],
    ['Harper.ExpandPerformance', 'perf and min name flags and files'],
    ['Harper.ExpandMinimum', 'perf and min name flags and files'],
    ['Harper.OkToOkay', 'ok is the check status'],
    ['Harper.MoreAdjective2', 'it reports that an inflected form exists, which is not an error'],
    ['Harper.MoreAdjective4', 'it reports that an inflected form exists, which is not an error'],
];

/** What Vale never reads: URLs, tool directives and doc tags. Code spans and fences are the Markdown parser's job; a backtick pattern here swallowed whole fenced blocks. */
export const TOKEN_IGNORES = [
    String.raw`(https?://[^\s)]+)`,
    String.raw`(eslint-disable[^\n]*)`,
    String.raw`(@ts-expect-error[^\n]*)`,
    String.raw`(@ts-ignore[^\n]*)`,
    String.raw`(swiftlint:[^\n]*)`,
    String.raw`(shellcheck [^\n]*)`,
    String.raw`(nosemgrep[^\n]*)`,
    String.raw`(MARK: -[^\n]*)`,
    String.raw`(@(?:param|returns|throws|template|typedef|type|see|example|deprecated)\b[^\n]*)`,
];

/** Front matter is not prose. */
export const BLOCK_IGNORES = [String.raw`(?s)^---\n.*?\n---\n`];

/** Tool and product names Vale accepts as written. */
export const SHIPPED_VOCABULARY = [
    'gspot',
    'ESLint',
    'Prettier',
    'TypeScript',
    'JavaScript',
    'Bun',
    'Node',
    'npm',
    'pnpm',
    'mise',
    'Vale',
    'ShellCheck',
    'shfmt',
    'typos',
    'knip',
    'Semgrep',
    'CodeQL',
    'gitleaks',
    'osv-scanner',
    'Trivy',
    'hadolint',
    'SwiftLint',
    'SwiftFormat',
    'Periphery',
    'Ruff',
    'basedpyright',
    'sqlfluff',
    'Supabase',
    'Cloudflare',
    'GitHub',
    'Xcode',
    'Homebrew',
    'commitlint',
    'markdownlint',
    'lychee',
    'taplo',
    'yamllint',
    'actionlint',
    'zizmor',
    'ast-grep',
    'tree-sitter',
    'Vitest',
    'Zod',
    'Drizzle',
    'tRPC',
    'TanStack',
    'Zustand',
    'Next.js',
    'React',
    'Docker',
    'nginx',
    'PostgreSQL',
    'Postgres',
    'SQL',
    'Bash',
    'Swift',
    'Python',
    'CSS',
    'HTML',
    'JSON',
    'TOML',
    'YAML',
    'Markdown',
    'SARIF',
    'CI',
    'macOS',
    'Linux',
    'Windows',
];

/** One Vale alert on the line output: file, line, column, check, message. */
export const VALE_LINE = /^(?<file>.+?):(?<line>\d+):(?<column>\d+):(?<check>[^:]+):(?<message>.*)$/u;

/** The name Vale gives stdin, followed by the grammar extension. */
export const VALE_STDIN = 'stdin';

/** The style directory under .gspot and the style Vale reads from it. */
export const STYLES_DIRECTORY = '.gspot/vale/styles';
export const GSPOT_STYLE = 'gspot';

/** The three length rules the docs limits set, by rule file stem and the limits key. */
export const LENGTH_RULES: Record<string, string> = {
    'sentence-length': 'docs.sentence_words',
    'step-length': 'docs.list_item_words',
    'paragraph-length': 'docs.paragraph_sentences',
};

/** The two things a source file must not say to Vale: a directive in Markdown, a block comment in SQL. */
export const VALE_DIRECTIVE = /<!--\s*vale\b/u;
export const CODE_SPAN = /`[^`]*`/gu;
export const SQL_BLOCK_COMMENT = '/*';
