// What makes a line of a corpus file a rule statement, and what the corpus lint refuses.

/** A paragraph that opens with one of these words is a rule statement. */
export const IMPERATIVE_OPENERS = [
    'Do not',
    'Never',
    'Always',
    'Use',
    'Keep',
    'Prefer',
    'Avoid',
    'Put',
    'Run',
    'Read',
    'Write',
    'Treat',
    'Validate',
    'Reject',
    'Return',
    'Raise',
    'Throw',
    'Catch',
    'Name',
    'Mark',
    'Pin',
    'Quote',
    'Check',
    'Store',
    'Pass',
    'Import',
    'Export',
    'Compare',
    'Convert',
    'Handle',
    'Group',
    'Sort',
    'Split',
    'Choose',
    'Declare',
    'Define',
    'Delete',
    'Remove',
    'Add',
    'Give',
    'Set',
    'Make',
    'Let',
    'Place',
    'Test',
    'Verify',
    'Include',
    'Exclude',
    'Follow',
    'Match',
    'Respect',
    'Bound',
    'Limit',
    'Wrap',
    'Escape',
    'Sanitize',
    'Hash',
    'Sign',
    'Log',
    'Report',
    'Print',
    'Send',
    'Fail',
    'Exit',
    'Close',
    'Release',
    'Await',
    'Cancel',
    'Retry',
    'Persist',
    'Reset',
    'Restore',
    'Enable',
    'Disable',
    'Configure',
    'Install',
    'Regenerate',
    'Order',
    'Annotate',
    'Document',
    'Explain',
    'State',
    'Describe',
    'Restate',
    'Provide',
    'Expose',
    'Hide',
    'Ban',
    'Refuse',
    'Require',
    'Emit',
    'Format',
    'Trim',
    'Normalize',
    'Translate',
    'Map',
    'Derive',
    'Compute',
    'Cache',
    'Invalidate',
    'Load',
    'Fetch',
    'Select',
    'Insert',
    'Update',
    'Extract',
    'Inline',
    'Promote',
    'Move',
    'Colocate',
    'Separate',
    'Wait',
    'Block',
    'Allow',
    'Skip',
    'Ignore',
    'Commit',
    'Push',
    'Rebase',
    'Branch',
    'Squash',
    'Every',
    'Each',
    'One',
    'No',
    'Nothing',
];

/** A line that is only one of these labels introduces an example and is not a statement. */
export const EXAMPLE_LABELS = ['Bad', 'Good', 'Avoid', 'Use', 'Rules', 'Example', 'Examples'];

/** The layers a corpus file can declare. */
export const RULE_LAYERS = [
    'agent',
    'code',
    'prose',
    'language',
    'runtime',
    'framework',
    'library',
    'tool',
    'platform',
    'database',
    'shared',
    'repository',
    'template',
];

/** The layers that name no repository, product, layout path or deployment target. */
export const BOUNDARY_LAYERS = ['agent', 'code', 'prose', 'language'];

/** Words a boundary layer must not carry outside inline code. */
export const BOUNDARY_TERMS = [
    /\bsrc\/app\b/u,
    /\bsrc\/modules\b/u,
    /\bplatform\/(?:db|providers)\b/u,
    /\bsupabase\/(?:migrations|functions)\b/u,
    /\bVirtua\b/u,
    /\bPino\b/u,
    /\byap\b/iu,
    /\bslopshop\b/iu,
    /\bHugging Face\b/u,
    /\bTensorRT\b/u,
    /\bvLLM\b/u,
    /\bCloudflare Pages\b/u,
    /\bHetzner\b/u,
    /\bVercel\b/u,
];

/** Residue of the corruption the repair pass fixed; none may return. */
export const CORRUPTION_TERMS = [
    /z\.item\(/u,
    /\bitem literal/u,
    /\bsource item\b/u,
    /\bitem keys\b/u,
    /package[- ]coordinator/u,
    /secret coordinator/u,
    /service-coordinator/u,
    /\baccess command\b/u,
    /\bplatform command\b/u,
    /\bsource command\b/u,
    /\bprocess command\b/u,
    /access-command/u,
    /\bproject operators\b/u,
    /\bproject controls\b/u,
    /\bproject regex\b/u,
    /\bproject Bash harnesses\b/u,
    /encodedBytes/u,
    /code: 'project'/u,
];

/** The language tags a fenced block may carry. */
export const FENCE_LANGUAGES = [
    'ts',
    'tsx',
    'js',
    'jsx',
    'mjs',
    'cjs',
    'python',
    'py',
    'swift',
    'bash',
    'sh',
    'shell',
    'sql',
    'toml',
    'json',
    'jsonc',
    'yaml',
    'yml',
    'text',
    'plaintext',
    'markdown',
    'md',
    'html',
    'css',
    'dockerfile',
    'diff',
    'dotenv',
    'mermaid',
    'http',
    'xml',
    'plist',
    'ini',
    'nginx',
    'makefile',
    'console',
];

/** No corpus file exceeds this many lines. */
export const RULE_FILE_LINE_CEILING = 800;
