// Write the mise pins of every kit tool from the manifests, so the test harness has one pin owner.
import { misePins } from '#cli/tools/mise.ts';
import { kitManifests } from '#cli/kits/manifests.ts';
import { readFileSync, writeFileSync } from 'node:fs';
import { miseToolLine } from '#cli/generation/tools/mise.ts';
import { MISE_CONFIG_PATH, MISE_MIN_VERSION } from '#cli/config/generation/generation.ts';

const TEST_TOOLS_PATH = '.mise/conf.d/test-tools.toml';

// gspot already pins the tools of this repository's own kits, and mise loads both files, so only the rest are listed.
const pinned = new Set(readFileSync(MISE_CONFIG_PATH, 'utf8').split('\n'));
const lines = [
    '# Generated by mise run repo:tools from the kit manifests, for the tools gspot-tools.toml does not pin. Edit the manifests, then run it again.',
    '',
    `min_version = "${MISE_MIN_VERSION}"`,
    '',
    '[tools]',
    ...misePins([...kitManifests().values()], true)
        .map((pin) => miseToolLine(pin))
        .filter((line) => !pinned.has(line)),
];
writeFileSync(TEST_TOOLS_PATH, `${lines.join('\n')}\n`);
console.log(`wrote ${TEST_TOOLS_PATH}`);
