import type { Verdict } from '#cli/types/repository/inventory.ts';
import { STYLES_DIRECTORY } from '#cli/config/platform/locations.ts';

export const DEPENDENCY_FOLDERS = [
    'node_modules',
    'bower_components',
    '.venv',
    'venv',
    'Pods',
    'DerivedData',
    '.build',
];

export const FILE_PREFIX_BYTES = 4096;

/** Root scope metadata; each repository owns its configuration list. */
export const ROOT_SCOPE = { name: 'root', path: '', source: 'root' } as const;

export const GENERATED_BANNERS: RegExp[] = [
    // A comment line that carries the marker, so a source file that only names it stays source.
    /^[ \t]*(?:\/\/|#|\/?\*|<!--|--).*@generated\b/mu,
    /^\/\/ Code generated by .* DO NOT EDIT\./,
    /^\/\*\s*eslint-disable\s*\*\/\s*\n\/\/ This file is auto-generated/,
    /^\/\/ This file was automatically generated/,
    /^\/\/ This file is automatically generated/,
    /^# This file is automatically @generated by/,
    /^# This file was autogenerated by uv/,
    /^\/\/\/ <reference types="@cloudflare\/workers-types/,
    /^\/\/\/ <reference types="next"/,
];

export const VENDORED_DIRECTORIES = [
    'vendor',
    'third_party',
    'third-party',
    'node_modules',
    'Pods',
    'Carthage',
    '.build',
];

/** License filenames accepted by the repository inventory and README checks. */
export const LICENSE_FILE = /^(?:LICEN[CS]E|COPYING)(?:$|[.-])/iu;

/** Notice filenames identify legal text but do not satisfy the license requirement. */
export const NOTICE_FILE = /^NOTICE(?:$|[.-])/iu;

/** The tags of an extension a license text may carry; one a code language claims makes the file source. */
export const LICENSE_TAGS = new Set(['text', 'markdown']);

/** Everything under the style directory except the gspot style and vocabulary is a vendored Vale package. */
export const VALE_OWN_PREFIXES = [`${STYLES_DIRECTORY}/gspot/`, `${STYLES_DIRECTORY}/config/vocabularies/gspot/`];

export const BANNER_BYTES = 1024;

export const ENV_FILE_PATTERNS = ['.env', '.env.*', '.dev.vars', '.dev.vars.*'];

export const ENV_TEMPLATE_NAMES = ['.env.example', '.env.template', '.env.sample', '.dev.vars.example'];

export const EXTENSION_TAGS: Record<string, string[]> = {
    '.sh': ['shell', 'bash', 'text'],
    '.bash': ['shell', 'bash', 'text'],
    '.zsh': ['shell', 'zsh', 'text'],
    '.bats': ['shell', 'bats', 'text'],
    '.py': ['python', 'text'],
    '.pyi': ['python', 'pyi', 'text'],
    '.js': ['javascript', 'text'],
    '.mjs': ['javascript', 'text'],
    '.cjs': ['javascript', 'text'],
    '.jsx': ['javascript', 'jsx', 'text'],
    '.ts': ['typescript', 'text'],
    '.mts': ['typescript', 'text'],
    '.cts': ['typescript', 'text'],
    '.tsx': ['typescript', 'tsx', 'text'],
    '.vue': ['vue', 'source', 'text'],
    '.svelte': ['svelte', 'source', 'text'],
    '.astro': ['astro', 'source', 'text'],
    '.swift': ['swift', 'text'],
    '.sql': ['sql', 'text'],
    '.pgsql': ['sql', 'text'],
    '.psql': ['sql', 'text'],
    '.md': ['markdown', 'text'],
    '.mdx': ['markdown', 'text'],
    '.json': ['json', 'text'],
    '.jsonc': ['json', 'jsonc', 'text'],
    '.json5': ['json', 'text'],
    '.yml': ['yaml', 'text'],
    '.yaml': ['yaml', 'text'],
    '.toml': ['toml', 'text'],
    '.ini': ['ini', 'text'],
    '.cfg': ['ini', 'text'],
    '.css': ['css', 'text'],
    '.scss': ['scss', 'text'],
    '.html': ['html', 'text'],
    '.htm': ['html', 'text'],
    '.xml': ['xml', 'text'],
    '.plist': ['plist', 'xml', 'text'],
    '.entitlements': ['plist', 'xml', 'text'],
    '.xcconfig': ['xcconfig', 'text'],
    '.xcstrings': ['json', 'xcstrings', 'text'],
    '.storyboard': ['xml', 'text'],
    '.xib': ['xml', 'text'],
    '.svg': ['svg', 'xml', 'text'],
    '.txt': ['text'],
    '.env': ['dotenv', 'text'],
    '.conf': ['text'],
    '.webmanifest': ['json', 'text'],
};

export const SHEBANG_INTERPRETERS: Record<string, string> = {
    bash: 'shell',
    bats: 'shell',
    sh: 'shell',
    zsh: 'shell',
    dash: 'shell',
    ksh: 'shell',
    python: 'python',
    python3: 'python',
    node: 'node',
    bun: 'node',
    deno: 'node',
    tsx: 'node',
};

export const BINARY_EXTENSIONS = [
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.webp',
    '.ico',
    '.bmp',
    '.tiff',
    '.heic',
    '.avif',
    '.mp3',
    '.mp4',
    '.mov',
    '.wav',
    '.m4a',
    '.aac',
    '.ogg',
    '.webm',
    '.flac',
    '.ttf',
    '.otf',
    '.woff',
    '.woff2',
    '.eot',
    '.zip',
    '.gz',
    '.tar',
    '.tgz',
    '.bz2',
    '.xz',
    '.7z',
    '.jar',
    '.pdf',
    '.wasm',
    '.so',
    '.dylib',
    '.dll',
    '.exe',
    '.a',
    '.o',
    '.bin',
    '.dat',
    '.db',
    '.sqlite',
    '.pyc',
    '.pyo',
    '.class',
    '.car',
    '.mlmodel',
    '.mlmodelc',
    '.p8',
    '.p12',
    '.cer',
    '.der',
    '.mobileprovision',
];

export const FILENAME_TAGS: Record<string, string[]> = {
    Dockerfile: ['dockerfile', 'text'],
    Makefile: ['makefile', 'text'],
    '.gitignore': ['text'],
    '.gitattributes': ['text'],
    '.editorconfig': ['ini', 'text'],
    '.nvmrc': ['text'],
    '.node-version': ['text'],
    '.python-version': ['text'],
    _headers: ['text'],
    _redirects: ['text'],
    LICENSE: ['text'],
    'LICENSE.md': ['markdown', 'text'],
    CODEOWNERS: ['text'],
};

export const SHEBANG_TAGS: Record<string, string[]> = {
    shell: ['shell', 'executable', 'text'],
    python: ['python', 'executable', 'text'],
    node: ['javascript', 'node', 'executable', 'text'],
};

export const LINT_DIRECTORIES = ['quality', 'lint', 'linting', '.qlty', 'code-quality'];

export const AGENT_FILES = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.cursorrules', 'CONVENTIONS.md'];

export const RULES_DIRECTORIES = ['rules', '.rules', '.cursor/rules', 'docs/rules', '.claude/rules'];

// The words in a CI job name that say it lints.
export const LINT_WORDS = new Set(['lint', 'quality', 'gspot']);

// Two-word lint commands, and the package managers whose lint task counts.
export const LINT_PAIRS = new Set(['gspot check', 'biome check', 'ruff check']);

export const FOREIGN_CI_FILES = new Set([
    'Jenkinsfile',
    'bitbucket-pipelines.yml',
    '.circleci/config.yml',
    'azure-pipelines.yml',
    '.buildkite/pipeline.yml',
]);

export const MISE_FILES = [
    'mise.toml',
    '.mise.toml',
    '.mise/config.toml',
    '.tool-versions',
    'mise.local.toml',
    '.config/mise.toml',
    '.config/mise/config.toml',
    'mise/config.toml',
    '.mise.local.toml',
];

// In "<runner> run <task>", the task sits two words after the runner.
export const TASK_AFTER_RUN = 2;

/** Ordinary authored content after higher-priority inventory classifications. */
export const SOURCE_KIND: Verdict = { kind: 'source', source: 'default' };
export const SHEBANG_TAG = 'shebang:';

export const RUNTIME_TAG = 'runtime:';
