// The literal values repository reads: names, patterns, limits, and tables.
import type { Tooling } from '#cli/types/repository/repository.ts';
import { STYLES_DIRECTORY } from '#cli/config/platform/locations.ts';

/** The package-lock format that carries both the packages table and the old dependencies tree. */
const HYBRID_LOCKFILE = 2;

/** The package-lock format that carries the packages table alone. */
const PACKAGES_LOCKFILE = 3;

/** Repository-relative paths shared by generation, execution, and lifecycle storage. */

export const SHEBANG_INTERPRETERS: Record<string, string> = {
    bash: 'shell',
    bats: 'shell',
    sh: 'shell',
    zsh: 'shell',
    dash: 'shell',
    ksh: 'shell',
    python: 'python',
    python3: 'python',
    node: 'node',
    bun: 'node',
    deno: 'node',
    tsx: 'node',
};
export const GENERATED_BANNERS: RegExp[] = [
    /^\/\/ Generated by gspot/,
    /^# Generated by gspot/,
    /^\{\s*"_gspot":/,
    // A comment line that carries the marker, so a source file that only names it stays source.
    /^[ \t]*(?:\/\/|#|\/?\*|<!--|--).*@generated\b/mu,
    /^\/\/ Code generated by .* DO NOT EDIT\./,
    /^\/\*\s*eslint-disable\s*\*\/\s*\n\/\/ This file is auto-generated/,
    /^\/\/ This file was automatically generated/,
    /^\/\/ This file is automatically generated/,
    /^# This file is automatically @generated by/,
    /^# This file was autogenerated by uv/,
    /^\/\/\/ <reference types="@cloudflare\/workers-types/,
    /^\/\/\/ <reference types="next"/,
];
/** Every lockfile gspot knows, with the package client that writes it. */
export const LOCKFILE_CLIENTS: Record<string, string> = {
    'bun.lock': 'bun',
    'bun.lockb': 'bun',
    'package-lock.json': 'npm',
    'npm-shrinkwrap.json': 'npm',
    'pnpm-lock.yaml': 'pnpm',
    'yarn.lock': 'yarn',
    'uv.lock': 'uv',
    'poetry.lock': 'poetry',
    'pdm.lock': 'pdm',
    'Cargo.lock': 'cargo',
    'go.sum': 'go',
    'Gemfile.lock': 'bundler',
    'Package.resolved': 'swift',
    'Podfile.lock': 'cocoapods',
};
export const BINARY_EXTENSIONS = [
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.webp',
    '.ico',
    '.bmp',
    '.tiff',
    '.heic',
    '.avif',
    '.mp3',
    '.mp4',
    '.mov',
    '.wav',
    '.m4a',
    '.aac',
    '.ogg',
    '.webm',
    '.flac',
    '.ttf',
    '.otf',
    '.woff',
    '.woff2',
    '.eot',
    '.zip',
    '.gz',
    '.tar',
    '.tgz',
    '.bz2',
    '.xz',
    '.7z',
    '.jar',
    '.pdf',
    '.wasm',
    '.so',
    '.dylib',
    '.dll',
    '.exe',
    '.a',
    '.o',
    '.bin',
    '.dat',
    '.db',
    '.sqlite',
    '.pyc',
    '.pyo',
    '.class',
    '.car',
    '.mlmodel',
    '.mlmodelc',
    '.p8',
    '.p12',
    '.cer',
    '.der',
    '.mobileprovision',
];
export const VENDORED_DIRECTORIES = [
    'vendor',
    'third_party',
    'third-party',
    'node_modules',
    'Pods',
    'Carthage',
    '.build',
];
export const LINT_DIRECTORIES = ['quality', 'lint', 'linting', '.qlty', 'code-quality'];
export const LINT_TOOL_PACKAGE_PREFIXES = [
    'eslint',
    '@eslint',
    '@eslint-community',
    'typescript-eslint',
    '@typescript-eslint',
    'prettier',
    'knip',
    'markdownlint',
    '@commitlint',
    'commitlint',
    'stylelint',
    'syncpack',
    'sort-package-json',
    'license-checker',
    'jscpd',
    'lizard',
    'madge',
    'html-validate',
    'linkinator',
    'purgecss',
    'svgo',
    'squawk-cli',
    'type-coverage',
    'lint-staged',
    'husky',
    'lefthook',
    '@vitest/eslint-plugin',
    'globals',
    'depcheck',
    'cspell',
    'typos',
    'concurrently',
    'supabase',
    'sqlfluff',
];
export const AGENT_FILES = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.cursorrules', 'CONVENTIONS.md'];
export const RULES_DIRECTORIES = ['rules', '.rules', '.cursor/rules', 'docs/rules', '.claude/rules'];

/** License and notice files are another party's text, kept as written: the name alone or with a suffix such as -MIT. */
export const LICENSE_FILE = /^(?:LICEN[CS]E|COPYING|NOTICE)(?:$|[.-])/iu;

/** The tags of an extension a license text may carry; one a code language claims makes the file source. */
export const LICENSE_TAGS = new Set(['text', 'markdown']);

/** Everything under the style directory except the gspot style and vocabulary is a vendored Vale package. */
export const VALE_OWN_PREFIXES = [`${STYLES_DIRECTORY}/gspot/`, `${STYLES_DIRECTORY}/config/vocabularies/gspot/`];

export const FOREIGN_HOOK_DIRECTORIES = ['.githooks', '.husky', '.git-hooks'];
export const EXECUTABLE_BITS = 0o111;
export const NOT_REPOSITORY_CODE = 128;

export const LOCKFILE_VERSIONS = [HYBRID_LOCKFILE, PACKAGES_LOCKFILE] as const;

export const ENV_SUFFIX = '/env';
export const BANNER_BYTES = 1024;
export const GENERATED_ATTRIBUTES = new Set(['linguist-generated', 'linguist-generated=true']);
export const VENDORED_ATTRIBUTES = new Set(['linguist-vendored', 'linguist-vendored=true']);
export const BINARY_ATTRIBUTES = new Set(['-text', 'binary']);
export const DEPENDENCY_FOLDERS = [
    'node_modules',
    'bower_components',
    '.venv',
    'venv',
    'Pods',
    'DerivedData',
    '.build',
];

// The words in a CI job name that say it lints.
export const LINT_WORDS = new Set(['lint', 'quality', 'gspot']);

// Two-word lint commands, and the package managers whose lint task counts.
export const LINT_PAIRS = new Set(['gspot check', 'biome check', 'ruff check']);
export const TASK_RUNNERS = new Set(['npm', 'pnpm', 'yarn', 'bun', 'mise']);
export const FOREIGN_CI_FILES = new Set([
    'Jenkinsfile',
    'bitbucket-pipelines.yml',
    '.circleci/config.yml',
    'azure-pipelines.yml',
    '.buildkite/pipeline.yml',
]);
export const MISE_FILES = ['mise.toml', '.mise.toml', '.mise/config.toml', '.tool-versions', 'mise.local.toml'];
export const RUNNER_LOCKS: { file: string; runner: Tooling['runner'] }[] = [
    { file: 'bun.lock', runner: 'bun' },
    { file: 'bun.lockb', runner: 'bun' },
    { file: 'pnpm-lock.yaml', runner: 'pnpm' },
    { file: 'yarn.lock', runner: 'yarn' },
    { file: 'package-lock.json', runner: 'npm' },
    { file: 'package.json', runner: 'npm' },
    { file: 'uv.lock', runner: 'none' },
    { file: 'pyproject.toml', runner: 'none' },
];
export const REQUIREMENT_NAME_END = /[\s<>=!~;[@]/u;
export const SWIFT_PACKAGE_URL = /url:\s*"([^"]+)"/gu;

export const EMPTY_FILES = 18_002;
export const NO_INPUTS = 18_003;
export const FILE_PREFIX_BYTES = 4096;
export const ENV_FILE_PATTERNS = ['.env', '.env.*', '.dev.vars', '.dev.vars.*'];
export const ENV_TEMPLATE_NAMES = ['.env.example', '.env.template', '.env.sample', '.dev.vars.example'];

export const EXTENSION_TAGS: Record<string, string[]> = {
    '.sh': ['shell', 'bash', 'text'],
    '.bash': ['shell', 'bash', 'text'],
    '.zsh': ['shell', 'zsh', 'text'],
    '.bats': ['shell', 'bats', 'text'],
    '.py': ['python', 'text'],
    '.pyi': ['python', 'pyi', 'text'],
    '.js': ['javascript', 'text'],
    '.mjs': ['javascript', 'text'],
    '.cjs': ['javascript', 'text'],
    '.jsx': ['javascript', 'jsx', 'text'],
    '.ts': ['typescript', 'text'],
    '.mts': ['typescript', 'text'],
    '.cts': ['typescript', 'text'],
    '.tsx': ['typescript', 'tsx', 'text'],
    '.vue': ['vue', 'source', 'text'],
    '.svelte': ['svelte', 'source', 'text'],
    '.astro': ['astro', 'source', 'text'],
    '.swift': ['swift', 'text'],
    '.sql': ['sql', 'text'],
    '.pgsql': ['sql', 'text'],
    '.psql': ['sql', 'text'],
    '.md': ['markdown', 'text'],
    '.mdx': ['markdown', 'text'],
    '.json': ['json', 'text'],
    '.jsonc': ['json', 'jsonc', 'text'],
    '.json5': ['json', 'text'],
    '.yml': ['yaml', 'text'],
    '.yaml': ['yaml', 'text'],
    '.toml': ['toml', 'text'],
    '.ini': ['ini', 'text'],
    '.cfg': ['ini', 'text'],
    '.css': ['css', 'text'],
    '.scss': ['scss', 'text'],
    '.html': ['html', 'text'],
    '.htm': ['html', 'text'],
    '.xml': ['xml', 'text'],
    '.plist': ['plist', 'xml', 'text'],
    '.entitlements': ['plist', 'xml', 'text'],
    '.xcconfig': ['xcconfig', 'text'],
    '.xcstrings': ['json', 'xcstrings', 'text'],
    '.storyboard': ['xml', 'text'],
    '.xib': ['xml', 'text'],
    '.svg': ['svg', 'xml', 'text'],
    '.txt': ['text'],
    '.env': ['dotenv', 'text'],
    '.conf': ['text'],
    '.webmanifest': ['json', 'text'],
};
export const FILENAME_TAGS: Record<string, string[]> = {
    Dockerfile: ['dockerfile', 'text'],
    Makefile: ['makefile', 'text'],
    '.gitignore': ['text'],
    '.gitattributes': ['text'],
    '.editorconfig': ['ini', 'text'],
    '.nvmrc': ['text'],
    '.node-version': ['text'],
    '.python-version': ['text'],
    _headers: ['text'],
    _redirects: ['text'],
    LICENSE: ['text'],
    'LICENSE.md': ['markdown', 'text'],
    CODEOWNERS: ['text'],
};
export const SHEBANG_TAGS: Record<string, string[]> = {
    shell: ['shell', 'executable', 'text'],
    python: ['python', 'executable', 'text'],
    node: ['javascript', 'node', 'executable', 'text'],
};

/** Where a test file lives: in a test folder, or named for a test runner. */
export const TEST_FILE_GLOBS = [
    '**/test/**',
    '**/tests/**',
    '**/__tests__/**',
    '**/*.test.*',
    '**/*.spec.*',
    '**/test_*.py',
    '**/*_test.py',
    '**/conftest.py',
];
