// Compares generated outputs with the files on disk.
import { createTwoFilesPatch } from 'diff';
import { toPosix } from '#cli/platform/paths.ts';
import { openRoot } from '#cli/platform/root/open.ts';
import { outputPaths } from '#cli/generation/outputs.ts';
import { compareRules } from '#cli/lifecycle/rule-diff.ts';
import type { Drift } from '#cli/types/lifecycle/output.ts';
import type { Policy } from '#cli/types/policy/settings.ts';
import { hasFields } from '#cli/lifecycle/merge/document.ts';
import { packageLockDrift } from '#cli/tools/npm/project.ts';
import { CONFLICT_MARKERS } from '#cli/config/parsers/git.ts';
import { currentBlock } from '#cli/platform/managed-blocks.ts';
import { getOwnership } from '#cli/lifecycle/ownership/log.ts';
import { pythonLockDrift } from '#cli/tools/python/project.ts';
import type { Generated } from '#cli/types/generation/output.ts';
import type { Ownership } from '#cli/types/lifecycle/ownership.ts';
import { HOOKS_DIRECTORY } from '#cli/config/platform/locations.ts';
import { DRIFT_DIFF_CONTEXT } from '#cli/config/lifecycle/output.ts';
import { RETAINED_KINDS, RETAINED_PATHS } from '#cli/config/lifecycle/ownership.ts';

function isStrayCandidate(path: string, policy: Policy): boolean {
    if (path.startsWith(`${policy.agentRules.folder}/`) && !policy.agentRules.enabled) return false;
    if (path.startsWith(`${HOOKS_DIRECTORY}/`) && policy.hooks === undefined) return false;
    return !RETAINED_PATHS.has(path);
}

function patch(path: string, before: string, after: string, beforeName: string): string {
    return createTwoFilesPatch(`a/${toPosix(path)}`, `b/${toPosix(path)}`, before, after, beforeName, 'generated', {
        context: DRIFT_DIFF_CONTEXT,
    });
}

function fileDrift(root: string, generated: Generated, ownership: Ownership): Drift[] {
    const { rules: previous = {} } = ownership;
    using files = openRoot(root);
    return generated.files.flatMap((file): Drift[] => {
        const baseline = previous[file.path];
        // A clone or revision snapshot has no private apply history; its generated bytes still establish freshness.
        const rules =
            baseline === undefined || file.ruleData === undefined ? [] : compareRules(baseline, file.ruleData);
        const changedRules = rules.length === 0 ? {} : { rules };
        const current = files.read(file.path);
        if (current === undefined) return [{ path: file.path, kind: 'missing', ...changedRules }];
        const disk = current.bytes.toString('utf8');
        // A merge left its markers in the file: regeneration repairs the unreadable configuration.
        if (CONFLICT_MARKERS.test(disk)) return [{ path: file.path, kind: 'conflict' }];
        if (disk !== file.content)
            return [
                {
                    path: file.path,
                    kind: 'changed',
                    diff: patch(file.path, disk, file.content, 'on disk'),
                    ...changedRules,
                },
            ];
        return rules.length === 0 ? [] : [{ path: file.path, kind: 'changed', rules }];
    });
}

function blockDrift(root: string, generated: Generated): Drift[] {
    const entries: Drift[] = [];
    using files = openRoot(root);
    for (const block of generated.blocks) {
        const text = files.read(block.path)?.bytes.toString('utf8') ?? '';
        const current = currentBlock(text, { path: block.path, style: block.style });
        const wanted = block.block.trim();
        if (current === undefined) entries.push({ path: block.path, kind: 'missing' });
        else if (current !== wanted)
            entries.push({
                path: block.path,
                kind: 'changed',
                diff: patch(block.path, current, wanted, 'managed block on disk'),
            });
    }
    return entries;
}

// The merged and configuration outputs whose fields are gone: missing when the file is gone, changed otherwise.
function keyDrift(root: string, generated: Generated): Drift[] {
    using files = openRoot(root);
    return [...generated.configurations]
        .filter((output) => !hasFields(root, output))
        .map((output) => ({ path: output.path, kind: files.read(output.path) === undefined ? 'missing' : 'changed' }));
}

/**
 * Every generated file that differs from its render, is missing, or is a stray gspot file. Managed blocks and authored config-file edits count too.
 * @param root the repository root
 * @param policy the repository policy
 * @param generated the generated files as generated now
 * @returns the drift entries in path order
 */
export function computeDrift(root: string, policy: Policy, generated: Generated): Drift[] {
    const ownership = getOwnership(root);
    const known = outputPaths(generated);
    const lock = packageLockDrift(root, generated.files);
    const python = pythonLockDrift(root, generated.files);
    const strays = ownership.files
        .filter(
            (entry) =>
                !RETAINED_KINDS.has(entry.kind) &&
                entry.installed !== undefined &&
                !known.has(entry.path) &&
                isStrayCandidate(entry.path, policy),
        )
        .map((entry): Drift => ({ path: entry.path, kind: 'stray' }));
    return [
        ...(python?.kind === undefined ? [] : [{ path: python.path, kind: python.kind }]),
        ...(lock?.kind === undefined ? [] : [{ path: lock.path, kind: lock.kind }]),
        ...fileDrift(root, generated, ownership),
        ...blockDrift(root, generated),
        ...keyDrift(root, generated),
        ...strays,
    ].toSorted((a, b) => a.path.localeCompare(b.path));
}
