import { realpathSync } from 'node:fs';
import { AsyncLocalStorage } from 'node:async_hooks';
import { STATE_DIRECTORY } from '#cli/platform/paths.ts';
import { ownershipSchema } from '#cli/lifecycle/journal.ts';
import { openConfinedRoot } from '#cli/platform/filesystem.ts';
import type { FileSnapshot } from '#cli/platform/safe-paths.ts';
import type { BlockStyle } from '#cli/lifecycle/managed-blocks.ts';
import { fileMode, mutationTarget } from '#cli/platform/safe-paths.ts';
import { proposeRestoration } from '#cli/lifecycle/ownership-restoration.ts';
import type { OwnershipEntry, OwnershipState } from '#cli/lifecycle/journal.ts';
import { READ_ONLY_FILE, OWNER_WRITABLE_FILE } from '#cli/platform/file-modes.ts';
import { applyProposal, applyProposals } from '#cli/lifecycle/ownership-apply.ts';
import type { ConfigurationFormat } from '#cli/lifecycle/configuration-document.ts';
import { type FileProposal, type Journal, openJournal } from '#cli/lifecycle/ownership-journal.ts';

import {
    proposeBlock,
    proposeConfiguration,
    proposeReplacement,
    proposeRetirement,
} from '#cli/lifecycle/ownership-proposals.ts';

type Outcome = 'changed' | 'unchanged' | 'preserved';

const activeMutation = new AsyncLocalStorage<Map<string, LifecycleOwner>>();
// The owner's operations over an open journal.
function lifecycleOwner(journal: Journal): LifecycleOwner {
    const { state, confined } = journal;
    return {
        beginInstallation(kind) {
            state.installations = [...new Set([...(state.installations ?? []), kind])];
            journal.save();
        },
        finishInstallation(kind) {
            if (state.installations?.includes(kind) !== true)
                throw new Error('Installation recovery state changed. Retry gspot install.');
            state.installations = state.installations.filter((entry) => entry !== kind);
            if (state.installations.length === 0) delete state.installations;
            journal.save();
        },
        proposeConfiguration: (path, format, changes, takeover) =>
            proposeConfiguration(journal, path, format, changes, takeover),
        applyProposal: (proposal) => applyProposal(journal, proposal),
        applyProposals: (proposals) => applyProposals(journal, proposals),
        proposeBlock: (path, body, style) => proposeBlock(journal, path, body, style),
        replaceBlock: (path, body, style) => applyProposal(journal, proposeBlock(journal, path, body, style)),
        read(path) {
            mutationTarget(path);
            return confined.read(path);
        },
        paths: () => state.files.map((entry) => entry.path),
        proposeReplacement: (path, next, kind, takeover, expected, proposed) =>
            proposeReplacement(journal, path, next, kind, takeover, expected, proposed),
        replace: (path, next, kind, takeover, expected) =>
            applyProposal(journal, proposeReplacement(journal, path, next, kind, takeover, expected)),
        installedPaths: () => state.files.filter((entry) => entry.installed !== undefined).map((entry) => entry.path),
        proposeRetirement: (path, expected) => proposeRetirement(journal, path, expected),
        proposeRestoration: (path, original) => proposeRestoration(journal, path, original),
        restore(path, original) {
            const proposal = proposeRestoration(journal, path, original);
            if (proposal.status === 'preserved') return 'preserved';
            applyProposals(journal, [proposal]);
            return 'changed';
        },
        close: () => {
            confined.close();
        },
    };
}

/**
 * Preserve Git's writable checkout mode when exact generated bytes reproduce a read-only proposal.
 * @param proposed the generated file
 * @param current the file as it is now, or undefined when it does not exist
 * @returns the snapshot to publish
 */
export function publicationSnapshot(proposed: FileSnapshot, current: FileSnapshot | undefined): FileSnapshot {
    const { bytes } = proposed;
    const mode = fileMode(proposed);
    const checkout =
        mode === READ_ONLY_FILE &&
        current?.mode === fileMode({ mode: OWNER_WRITABLE_FILE }) &&
        current.isLink !== true &&
        current.bytes.equals(bytes);
    return { bytes, mode: checkout ? current.mode : mode };
}

/**
 * Serialize local lifecycle writers and recover their durable ownership journal before mutation.
 * @param root the root the owner confines its writes to
 * @param stateDirectory the directory under the root that holds the journal and lock
 * @returns the owner, which the caller closes
 */
export function openLifecycleOwner(root: string, stateDirectory = STATE_DIRECTORY): LifecycleOwner {
    const confined = openConfinedRoot(root);
    try {
        confined.lock(`${stateDirectory}/writer.lock`);
        return lifecycleOwner(openJournal(confined, stateDirectory));
    } catch (error) {
        confined.close();
        throw error;
    }
}

/**
 * Reuse active mutation owners and serialize each repository or Git-resolved root.
 * @param root the root the owner confines its writes to
 * @param action the work to do with the owner open
 * @param stateDirectory the directory under the root that holds the journal and lock
 * @returns what the action returns
 */
export function withLifecycleOwner<Result>(
    root: string,
    action: (owner: LifecycleOwner) => Result,
    stateDirectory = STATE_DIRECTORY,
): Result {
    const canonical = realpathSync(root);
    const key = `${canonical}\0${stateDirectory}`;
    const active = activeMutation.getStore();
    const existing = active?.get(key);
    if (existing !== undefined) return action(existing);
    const owner = openLifecycleOwner(canonical, stateDirectory);
    try {
        const result = activeMutation.run(new Map([...(active ?? []), [key, owner]]), () => action(owner));
        if (result instanceof Promise)
            return result.finally(() => {
                owner.close();
            }) as Result;
        owner.close();
        return result;
    } catch (error) {
        owner.close();
        throw error;
    }
}

/**
 * Read ownership for a preview without creating a lock, directory, or journal.
 * @param root the root the ownership belongs to
 * @param stateDirectory the directory under the root that holds the journal
 * @returns the recorded ownership, empty when nothing was recorded
 */
export function readOwnership(root: string, stateDirectory = STATE_DIRECTORY): OwnershipState {
    const files = openConfinedRoot(root);
    try {
        const record = files.read(`${stateDirectory}/ownership.json`);
        return record === undefined
            ? { version: 1, files: [] }
            : ownershipSchema.parse(JSON.parse(record.bytes.toString('utf8')));
    } finally {
        files.close();
    }
}

export type LifecycleOwner = {
    beginInstallation(kind: 'npm' | 'python'): void;
    finishInstallation(kind: 'npm' | 'python'): void;
    proposeConfiguration(
        path: string,
        format: ConfigurationFormat,
        changes: { path: (string | number)[]; value: unknown }[],
        takeover?: boolean,
    ): FileProposal;
    proposeReplacement(
        path: string,
        next: FileSnapshot,
        kind: OwnershipEntry['kind'],
        takeover?: boolean,
        expected?: FileSnapshot,
        proposed?: ReadonlyMap<string, FileSnapshot | undefined>,
    ): FileProposal;
    proposeBlock(path: string, body: string, style: BlockStyle): FileProposal;
    applyProposal(proposal: FileProposal): Outcome;
    applyProposals(proposals: FileProposal[]): Outcome[];
    replaceBlock(path: string, body: string, style: BlockStyle): Outcome;
    read(path: string): FileSnapshot | undefined;
    paths(): string[];
    installedPaths(): string[];
    proposeRetirement(path: string, expected: FileSnapshot): FileProposal;
    replace(
        path: string,
        next: FileSnapshot,
        kind: OwnershipEntry['kind'],
        takeover?: boolean,
        expected?: FileSnapshot,
    ): Outcome;
    proposeRestoration(path: string, original?: FileSnapshot): FileProposal;
    restore(path: string, original?: FileSnapshot): 'changed' | 'preserved';
    close(): void;
};
