import { GRAMMAR_NAMES, grammarPath } from '#cli/platform/assets.ts';
import { globbySync } from 'globby';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = fileURLToPath(new URL('..', import.meta.url));
const root = join(here, '..', '..');
const ASSET_FOLDERS = ['packages/cli/configurations', 'packages/cli/rules'];

export const grammarAssets = new Map(
    GRAMMAR_NAMES.map((name) => [
        name === 'swift.wasm' ? join(here, '.build', name) : grammarPath(name),
        `grammars/${name}`,
    ]),
);

function assetKey(file: string): string {
    const key =
        grammarAssets.get(file) ??
        (file === join(here, '.build/configuration-process.js')
            ? 'packages/cli/scripts/configuration-process.js'
            : relative(root, file));
    return key.replaceAll('\\', '/');
}

/**
 * Writes the entry module that embeds every asset and starts the CLI.
 * @returns the path of the written module
 */
export function writeEntry(): string {
    const assets = [
        ...globbySync(
            ASSET_FOLDERS.map((folder) => `${folder}/**/*`),
            { cwd: root, absolute: true, dot: true },
        ).toSorted((left, right) => left.localeCompare(right)),
        ...grammarAssets.keys(),
        join(here, '.build/configuration-process.js'),
    ];
    const buildDir = join(here, '.build');
    const imports = assets.map((file, index) => {
        const path = relative(buildDir, file);
        const source = JSON.stringify(path.startsWith('.') ? path : `./${path}`);
        return `import asset${String(index)} from ${source} with { type: 'file' };`;
    });
    const entries = assets.map((file, index) => `    ${JSON.stringify(assetKey(file))}: asset${String(index)},`);
    const lines = [
        '// Generated by bun packages/cli/scripts/command.ts. Do not edit.',
        ...imports,
        "import { main } from '../src/commands/program.ts';",
        '',
        '(globalThis as { gspotEmbedded?: Record<string, string> }).gspotEmbedded = {',
        ...entries,
        '};',
        '',
        'process.exitCode = await main(process.argv.slice(2));',
        '',
    ];
    mkdirSync(buildDir, { recursive: true });
    const entry = join(buildDir, 'entry.ts');
    writeFileSync(entry, lines.join('\n'));
    return entry;
}
