// Builds one executable per target with grammars, configurations, prose and rules embedded.
import { execaSync } from 'execa';
import { globbySync } from 'globby';
import { familySync } from 'detect-libc';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { grammarPath } from '#cli/platform/assets.ts';
import { GRAMMAR_SOURCES } from '#cli/parsers/grammars.ts';
import packageManifest from '#package' with { type: 'json' };
import { binaryNotices, dependencyNotices } from './notices.ts';
import { releaseTargets } from '#cli/platform/release-targets.ts';
import { Command, CommanderError, InvalidArgumentError } from 'commander';
import { existsSync, mkdirSync, rmSync, writeFileSync, copyFileSync } from 'node:fs';

const here = join(dirname(fileURLToPath(new URL(import.meta.url))), '..');
const root = join(here, '..', '..');

const TARGETS = Object.fromEntries(releaseTargets.map((target) => [target.target, target.binary]));

const ASSET_FOLDERS = ['packages/cli/configurations', 'packages/cli/rules'];

const grammarAssets = new Map(
    [...Object.keys(GRAMMAR_SOURCES), 'swift.wasm'].map((name) => [grammarPath(name), `grammars/${name}`]),
);

function assetKey(file: string): string {
    const key = grammarAssets.get(file) ?? relative(root, file);
    return key.replaceAll('\\', '/');
}

// Writes the entry module that embeds every asset and starts the CLI.
function writeEntry(): string {
    const assets = [
        ...globbySync(
            ASSET_FOLDERS.map((folder) => `${folder}/**/*`),
            { cwd: root, absolute: true, dot: true },
        ).toSorted((left, right) => left.localeCompare(right)),
        ...grammarAssets.keys(),
        join(here, 'build/configuration-process.js'),
    ];
    const buildDir = join(here, 'build');
    const imports = assets.map((file, index) => {
        const path = relative(buildDir, file);
        const source = JSON.stringify(path.startsWith('.') ? path : `./${path}`);
        return `import asset${String(index)} from ${source} with { type: 'file' };`;
    });
    const entries = assets.map((file, index) => `    ${JSON.stringify(assetKey(file))}: asset${String(index)},`);
    const lines = [
        '// Generated by build.ts. Do not edit.',
        ...imports,
        "import { main } from '../src/program.ts';",
        '',
        '(globalThis as { gspotEmbedded?: Record<string, string> }).gspotEmbedded = {',
        ...entries,
        '};',
        '',
        'process.exitCode = await main(process.argv.slice(2));',
        '',
    ];
    mkdirSync(buildDir, { recursive: true });
    const entry = join(buildDir, 'entry.ts');
    writeFileSync(entry, lines.join('\n'));
    return entry;
}

function build(targets: string[], out: string): void {
    const grammarSources = [...grammarAssets.keys()].filter((path) => path !== join(here, 'grammars/swift.wasm'));
    if (!existsSync(join(here, 'grammars/swift.wasm'))) throw new Error('Missing required grammar: swift.wasm.');
    binaryNotices('', join(here, 'grammars'));
    mkdirSync(join(here, 'build'), { recursive: true });
    const evaluatorMetadata = join(here, 'build/configuration-process.meta.json');
    const metadata = [{ path: evaluatorMetadata, cwd: here }];
    execaSync(
        'bun',
        [
            'build',
            '--target=bun',
            '--minify-syntax',
            `--metafile=${evaluatorMetadata}`,
            join(here, 'src/evaluation/process.ts'),
            '--outfile',
            join(here, 'build/configuration-process.js'),
        ],
        { cwd: here, stdout: 'inherit', stderr: 'inherit' },
    );
    const entry = writeEntry();
    mkdirSync(out, { recursive: true });
    for (const target of targets) {
        const name = TARGETS[target];
        if (name === undefined) throw new Error(`Unknown target ${target}; known: ${Object.keys(TARGETS).join(', ')}`);
        const outfile = join(out, name);
        rmSync(outfile, { force: true });
        const targetMetadata = join(here, 'build', `${target}.meta.json`);
        metadata.push({ path: targetMetadata, cwd: here });
        execaSync(
            'bun',
            [
                join(here, 'scripts/compile.ts'),
                `--target=${target}`,
                entry,
                '--outfile',
                outfile,
                `--metafile=${targetMetadata}`,
            ],
            { cwd: here, stdout: 'inherit', stderr: 'inherit' },
        );
        if (process.platform === 'darwin' && target.startsWith('bun-darwin-')) {
            execaSync('codesign', ['--force', '--sign', '-', outfile], {
                stdout: 'inherit',
                stderr: 'inherit',
            });
        }
        console.log(`built ${relative(root, outfile)}`);
    }
    const dependencies = dependencyNotices(metadata, grammarSources);
    const notice = binaryNotices(dependencies, join(here, 'grammars'));
    writeFileSync(join(out, 'NOTICE.md'), notice);
    copyFileSync(join(root, 'LICENSE.md'), join(out, 'LICENSE.md'));
}

function collectTargets(value: string, previous: string[]): string[] {
    if (TARGETS[value] === undefined)
        throw new InvalidArgumentError(`Unknown target ${value}. Choose ${Object.keys(TARGETS).join(', ')}.`);
    return [...previous, value];
}

function outputDirectory(value: string): string {
    if (value.trim() === '') throw new InvalidArgumentError('The output directory must not be empty.');
    return value;
}

try {
    const script = new Command('bun packages/cli/scripts/build.ts')
        .description('Build the gspot executable for selected platforms')
        .version(packageManifest.version)
        .option('--target <targets...>', 'Bun compile targets', collectTargets, [])
        .option('--out <directory>', 'Directory for the executables', outputDirectory, join(root, 'dist'))
        .allowExcessArguments(false)
        .showHelpAfterError()
        .addHelpText('after', '\nExample: bun packages/cli/scripts/build.ts --target bun-linux-arm64 --out dist')
        .exitOverride()
        .parse();
    const options = script.opts<{ target: string[]; out: string }>();
    const libc = process.platform === 'linux' ? familySync() : null;
    const current = releaseTargets.find(
        (target) => target.os === process.platform && target.cpu === process.arch && target.libc === libc,
    );
    if (options.target.length === 0) {
        if (current === undefined)
            throw new InvalidArgumentError(
                `Unsupported build host: ${process.platform} ${process.arch} ${String(libc)}.`,
            );
        options.target.push(current.target);
    }
    build(options.target, options.out);
} catch (error) {
    if (!(error instanceof CommanderError)) throw error;
    process.exitCode = error.exitCode === 0 ? 0 : 2;
}
