// Build the CLI as a Node module beside its configurations, rules, and grammars.
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import { EXECUTABLE_FILE } from '#cli/config/platform/modes.ts';
import packageManifest from '#cli-package' with { type: 'json' };
import { configurationManifests } from '#cli/configurations/public.ts';
import { validateEslintPresets } from '#cli/generation/eslint/public.ts';
import { assertManifests } from '#cli/configurations/errors/contracts.ts';
import { rm, chmod, rename, copyFile, readFile, writeFile } from 'node:fs/promises';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const distribution = join(root, 'dist');

const schemaCheck = Bun.spawn([process.execPath, join(root, '../../scripts/setting-values.ts'), '--check'], {
    cwd: join(root, '../..'),
    stdout: 'inherit',
    stderr: 'inherit',
});
if ((await schemaCheck.exited) !== 0)
    throw new Error('The compiled policy schema is stale. Run bun scripts/setting-values.ts.');

// A package never ships configurations that contradict each other; the CLI does not check them again at start.
assertManifests(configurationManifests());
validateEslintPresets(configurationManifests());
await rm(distribution, { recursive: true, force: true });
const result = await Bun.build({
    entrypoints: [join(root, 'src/main.ts'), join(root, 'src/checks/general/site/linkinator.ts')],
    outdir: distribution,
    naming: '[name].js',
    format: 'esm',
    target: 'node',
    external: Object.keys(packageManifest.dependencies),
    banner: '#!/usr/bin/env node',
    minify: false,
    sourcemap: 'none',
});
if (!result.success) throw new Error(result.logs.map((log) => log.message).join('\n'));
await rename(join(distribution, 'main.js'), join(distribution, 'gspot.js'));
await chmod(join(distribution, 'gspot.js'), EXECUTABLE_FILE);
await copyFile(join(root, '../..', 'LICENSE.md'), join(distribution, 'LICENSE.md'));
const readme = await readFile(join(root, '../..', 'README.md'), 'utf8');
const sections = readme.slice(readme.indexOf('\ngspot ')).trim().split('\n## ');
const packageReadme = sections
    .filter((section, index) => index === 0 || /^(?:Requirements|Install|Documentation)\n/u.test(section))
    .map((section, index) => (index === 0 ? section : `## ${section}`))
    .join('\n')
    .trimEnd();
await writeFile(
    join(root, 'README.md'),
    `<!-- Generated by mise run build:cli from README.md. -->\n\n# gspot\n\n${packageReadme.replaceAll(/docs\/src\/content\/docs\/(.+?)\.md/gu, 'https://generativespotting.com/$1/')}\n`,
);
console.log('built packages/cli/dist/gspot.js');
