// Write the mise pins of every kit tool from the manifests, so the test harness has one pin owner.
import { writeFileSync } from 'node:fs';
import { misePins } from '#cli/tools/mise.ts';
import { kitManifests } from '#cli/kits/manifests.ts';
import { miseToolLine } from '#cli/generation/tools/mise.ts';
import { MISE_MIN_VERSION } from '#cli/config/tools/tools.ts';

const TEST_TOOLS_PATH = '.mise/conf.d/test-tools.toml';

// npm and Python tools stay in their own projects, so only the native pins of every kit are listed.
const lines = [
    '# Generated by mise run repo:tools from the kit manifests. Edit the manifests, then run it again.',
    '',
    `min_version = "${MISE_MIN_VERSION}"`,
    '',
    '[tools]',
    ...misePins([...kitManifests().values()], true).map((pin) => miseToolLine(pin)),
];
writeFileSync(TEST_TOOLS_PATH, `${lines.join('\n')}\n`);
console.log(`wrote ${TEST_TOOLS_PATH}`);
