extends: capitalization
message: "The document title uses title case: '%s'."
level: error
scope: heading.h1
match: $title
exceptions:
    - nginx
    - tRPC
    - iOS
    - "\\x41BC"
    - "\\x41CME"
    - "\\x41ES"
    - "\\x41NN"
    - "\\x41NSI"
    - "\\x41OT"
    - "\\x41RG"
    - "\\x41RIA"
    - "\\x41SCII"
    - "\\x41SD"
    - "\\x41ST"
    - "\\x41TS"
    - "\\x41WQ"
    - "\\x61xe"
    - "\\x42ash"
    - "\\x42ASH"
    - "\\x42CP"
    - "\\x42EM"
    - "\\x42OM"
    - "\\x42SD"
    - "\\x42SL"
    - "\\x63apitalisation"
    - "\\x43DN"
    - "\\x43DPATH"
    - "\\x43JS"
    - "\\x43ORS"
    - "\\x43PU"
    - "\\x43RLF"
    - "\\x43RUD"
    - "\\x43SP"
    - "\\x43SRF"
    - "\\x43SV"
    - "\\x43TE"
    - "\\x43UDA"
    - "\\x44DL"
    - "\\x44EBUG"
    - "\\x44ELETE"
    - "\\x44NS"
    - "\\x44OM"
    - "\\x44TO"
    - "\\x45NV"
    - "\\x45OF"
    - "\\x45OL"
    - "\\x45RR"
    - "\\x45SM"
    - "\\x46acter"
    - "\\x46AST"
    - "\\x47ET"
    - "\\x47IF"
    - "\\x47NU"
    - "\\x47PU"
    - "\\x47RDB"
    - "\\x47UID"
    - "\\x48EAD"
    - "\\x48MAC"
    - "\\x48OME"
    - "\\x48STS"
    - "\\x48TTPS"
    - "\\x48usky"
    - "\\x49CU"
    - "\\x49DE"
    - "\\x49FS"
    - "\\x49IFEs"
    - "\\x49ME"
    - "\\x49NI"
    - "\\x49NT"
    - "\\x49SC"
    - "\\x49SO"
    - "\\x4aIT"
    - "\\x4aPEG"
    - "\\x4aSONB"
    - "\\x4aSONC"
    - "\\x4aSONL"
    - "\\x4aSPB"
    - "\\x4aSX"
    - "\\x4aWT"
    - "\\x4cefthook"
    - "\\x4cFS"
    - "\\x4cICENCE"
    - "\\x4cLM"
    - "\\x4cTS"
    - "\\x4dARK"
    - "\\x4dIME"
    - "\\x4dIT"
    - "\\x4dVC"
    - "\\x4dVP"
    - "\\x4dVVM"
    - "\\x4eAME"
    - "\\x6eext\\x2dintl"
    - "\\x4eOTE"
    - "\\x4ePM"
    - "\\x4eUL"
    - "\\x4eVIDIA"
    - "\\x4fCSP"
    - "\\x4fDF"
    - "\\x4fIDC"
    - "\\x6fptin"
    - "\\x4fRM"
    - "\\x4fTP"
    - "\\x4fWASP"
    - "\\x50ATCH"
    - "\\x50ATH"
    - "\\x50EP"
    - "\\x50ID"
    - "\\x50II"
    - "\\x50LR"
    - "\\x50NG"
    - "\\x50OSIX"
    - "\\x50OST"
    - "\\x50UT"
    - "\\x50WA"
    - "\\x50WD"
    - "\\x50YPI"
    - "\\x52AM"
    - "\\x52EADME"
    - "\\x52ETURN"
    - "\\x52FC"
    - "\\x52GB"
    - "\\x52LS"
    - "\\x52PC"
    - "\\x52SA"
    - "\\x52SC"
    - "\\x52TL"
    - "\\x53AST"
    - "\\x53CSS"
    - "\\x53DK"
    - "\\x53EO"
    - "\\x53GID"
    - "\\x53HA"
    - "\\x53IM"
    - "\\x53PDX"
    - "\\x53SE"
    - "\\x53SH"
    - "\\x53SR"
    - "\\x53SRF"
    - "\\x53TDERR"
    - "\\x53TDIN"
    - "\\x53TDOUT"
    - "\\x53UID"
    - "\\x53VG"
    - "\\x53WC"
    - "\\x54CA"
    - "\\x54CP"
    - "\\x54ERM"
    - "\\x54IP"
    - "\\x54LS"
    - "\\x54ODO"
    - "\\x54RT"
    - "\\x54RY"
    - "\\x54SX"
    - "\\x54TY"
    - "\\x54urborepo"
    - "\\x75did"
    - "\\x55DP"
    - "\\x55TC"
    - "\\x55TF"
    - "\\x55UID"
    - "\\x56IP"
    - "\\x56IPER"
    - "\\x57ASM"
    - "\\x57CAG"
    - "\\x57SL"
    - "\\x58ML"
