// Builds one executable per target with grammars, presets, prose, rules and schema embedded.
// Usage: bun packages/cli/build.ts [--target <bun-target>]... [--out dist]
import { dirname, join, relative } from 'node:path';
import { GRAMMAR_SOURCES } from '#config/grammars.ts';
import { policyJsonSchemaText } from '#cli/policy/json-schema.ts';
import { existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync, copyFileSync } from 'node:fs';

const here = dirname(new URL(import.meta.url).pathname);
const root = join(here, '..', '..');

const TARGETS: Record<string, string> = {
    'bun-darwin-arm64': 'gspot-darwin-arm64',
    'bun-darwin-x64': 'gspot-darwin-x64',
    'bun-linux-x64': 'gspot-linux-x64',
    'bun-linux-arm64': 'gspot-linux-arm64',
    'bun-windows-x64': 'gspot-windows-x64.exe',
};

const ASSET_FOLDERS = ['presets', 'rules', 'prose', 'schema'];

function walk(dir: string, out: string[] = []): string[] {
    if (!existsSync(dir)) return out;
    const entries = readdirSync(dir).toSorted((a, b) => a.localeCompare(b));
    for (const entry of entries) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) walk(full, out);
        else out.push(full);
    }
    return out;
}

function packageFile(relativePath: string): string | undefined {
    const candidates = [join(here, 'node_modules', relativePath), join(root, 'node_modules', relativePath)];
    return candidates.find((candidate) => existsSync(candidate));
}

// Writes schema/gspot.schema.json from the zod schema, so the published file never drifts from the reader.
function writeSchema(): void {
    mkdirSync(join(root, 'schema'), { recursive: true });
    writeFileSync(join(root, 'schema', 'gspot.schema.json'), policyJsonSchemaText());
}

// Copies the grammar WASM files from their packages into grammars/. The Swift grammar is vendored by hand.
function collectGrammars(): string[] {
    const dir = join(here, 'grammars');
    mkdirSync(dir, { recursive: true });
    const missing: string[] = [];
    for (const [name, source] of Object.entries(GRAMMAR_SOURCES)) {
        const found = packageFile(source);
        if (found === undefined) missing.push(name);
        else copyFileSync(found, join(dir, name));
    }
    return missing;
}

function assetKey(file: string): string {
    const key = file.startsWith(here) ? `grammars/${relative(join(here, 'grammars'), file)}` : relative(root, file);
    return key.replaceAll('\\', '/');
}

// Writes the entry module that embeds every asset and starts the CLI.
function writeEntry(): string {
    const assets = [...ASSET_FOLDERS.flatMap((folder) => walk(join(root, folder))), ...walk(join(here, 'grammars'))];
    const buildDir = join(here, 'build');
    const imports = assets.map((file, index) => {
        const source = JSON.stringify(relative(buildDir, file));
        return `import asset${String(index)} from ${source} with { type: 'file' };`;
    });
    const entries = assets.map((file, index) => `    ${JSON.stringify(assetKey(file))}: asset${String(index)},`);
    const lines = [
        '// Generated by build.ts. Do not edit.',
        ...imports,
        "import { main } from '../src/program.ts';",
        '',
        '(globalThis as { gspotEmbedded?: Record<string, string> }).gspotEmbedded = {',
        ...entries,
        '};',
        '',
        'process.exitCode = await main(process.argv.slice(2));',
        '',
    ];
    mkdirSync(buildDir, { recursive: true });
    const entry = join(buildDir, 'entry.ts');
    writeFileSync(entry, lines.join('\n'));
    return entry;
}

function build(targets: string[], out: string): void {
    writeSchema();
    const missing = collectGrammars();
    if (missing.length > 0)
        console.error('Grammars without a prebuilt file (vendor them by hand):', missing.join(', '));
    const entry = writeEntry();
    mkdirSync(out, { recursive: true });
    for (const target of targets) {
        const name = TARGETS[target];
        if (name === undefined) throw new Error(`Unknown target ${target}; known: ${Object.keys(TARGETS).join(', ')}`);
        const outfile = join(out, name);
        rmSync(outfile, { force: true });
        const result = Bun.spawnSync(
            ['bun', 'build', '--compile', `--target=${target}`, '--minify-syntax', entry, '--outfile', outfile],
            { cwd: here, stdout: 'inherit', stderr: 'inherit' },
        );
        if (result.exitCode !== 0) throw new Error(`Build failed for ${target}`);
        console.log(`built ${relative(root, outfile)}`);
    }
}

function parseArguments(argv: string[]): { targets: string[]; out: string } {
    const targets: string[] = [];
    let out = join(root, 'dist');
    for (const [index, argument] of argv.entries()) {
        const value = argv[index + 1];
        if (value === undefined) continue;
        if (argument === '--target') targets.push(value);
        else if (argument === '--out') out = value;
    }
    return { targets, out };
}

const { targets, out } = parseArguments(process.argv.slice(2));
const platform = process.platform === 'win32' ? 'windows' : process.platform;
const current = `bun-${platform}-${process.arch === 'arm64' ? 'arm64' : 'x64'}`;
build(targets.length > 0 ? targets : [current], out);
