// Builds one executable per target with grammars, presets, prose, rules and schema embedded.
// Usage: bun packages/cli/build.ts [--target <bun-target>]... [--out dist]
import { existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync, copyFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const here = dirname(new URL(import.meta.url).pathname);
const root = join(here, '..', '..');
const TARGETS: Record<string, string> = {
    'bun-darwin-arm64': 'gspot-darwin-arm64',
    'bun-darwin-x64': 'gspot-darwin-x64',
    'bun-linux-x64': 'gspot-linux-x64',
    'bun-linux-arm64': 'gspot-linux-arm64',
    'bun-windows-x64': 'gspot-windows-x64.exe',
};
const GRAMMARS: Record<string, string> = {
    'bash.wasm': 'tree-sitter-bash/tree-sitter-bash.wasm',
    'css.wasm': 'tree-sitter-css/tree-sitter-css.wasm',
    'html.wasm': 'tree-sitter-html/tree-sitter-html.wasm',
    'javascript.wasm': 'tree-sitter-javascript/tree-sitter-javascript.wasm',
    'python.wasm': 'tree-sitter-python/tree-sitter-python.wasm',
    'tsx.wasm': 'tree-sitter-typescript/tree-sitter-tsx.wasm',
    'typescript.wasm': 'tree-sitter-typescript/tree-sitter-typescript.wasm',
    'web-tree-sitter.wasm': 'web-tree-sitter/web-tree-sitter.wasm',
};

function walk(dir: string, out: string[] = []): string[] {
    if (!existsSync(dir)) return out;
    for (const entry of readdirSync(dir).sort()) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) walk(full, out);
        else out.push(full);
    }
    return out;
}

function resolvePackageFile(relativePath: string): string | undefined {
    const candidates = [join(here, 'node_modules', relativePath), join(root, 'node_modules', relativePath)];
    return candidates.find((candidate) => existsSync(candidate));
}

/** Copies the grammar WASM files from their packages into grammars/. The Swift grammar is vendored by hand. */
export function collectGrammars(): string[] {
    const dir = join(here, 'grammars');
    mkdirSync(dir, { recursive: true });
    const missing: string[] = [];
    for (const [name, source] of Object.entries(GRAMMARS)) {
        const found = resolvePackageFile(source);
        if (!found) {
            missing.push(name);
            continue;
        }
        copyFileSync(found, join(dir, name));
    }
    return missing;
}

/** Writes the entry module that embeds every asset and starts the CLI. */
export function writeEntry(): string {
    const assets = ['presets', 'rules', 'prose', 'schema']
        .flatMap((folder) => walk(join(root, folder)))
        .concat(walk(join(here, 'grammars')));
    const lines: string[] = ['// Generated by build.ts. Do not edit.'];
    const entries: string[] = [];
    assets.forEach((file, index) => {
        const key = file.startsWith(here) ? `grammars/${relative(join(here, 'grammars'), file)}` : relative(root, file);
        lines.push(
            `import asset${index} from ${JSON.stringify(relative(join(here, 'build'), file))} with { type: 'file' };`,
        );
        entries.push(`    ${JSON.stringify(key.split('\\').join('/'))}: asset${index},`);
    });
    lines.push(
        "import { main } from '../src/main.ts';",
        '',
        '(globalThis as { __gspotEmbedded?: Record<string, string> }).__gspotEmbedded = {',
        ...entries,
        '};',
        '',
        'process.exitCode = await main(process.argv.slice(2));',
        '',
    );
    const dir = join(here, 'build');
    mkdirSync(dir, { recursive: true });
    const entry = join(dir, 'entry.ts');
    writeFileSync(entry, lines.join('\n'));
    return entry;
}

async function build(targets: string[], out: string): Promise<void> {
    const missing = collectGrammars();
    if (missing.length > 0)
        console.error(`grammars without a prebuilt file (vendor them by hand): ${missing.join(', ')}`);
    const entry = writeEntry();
    mkdirSync(out, { recursive: true });
    for (const target of targets) {
        const name = TARGETS[target];
        if (!name) throw new Error(`unknown target ${target}; known: ${Object.keys(TARGETS).join(', ')}`);
        const outfile = join(out, name);
        rmSync(outfile, { force: true });
        const result = Bun.spawnSync(
            ['bun', 'build', '--compile', `--target=${target}`, '--minify-syntax', entry, '--outfile', outfile],
            { cwd: here, stdout: 'inherit', stderr: 'inherit' },
        );
        if (result.exitCode !== 0) throw new Error(`build failed for ${target}`);
        console.log(`built ${relative(root, outfile)}`);
    }
}

if (import.meta.main) {
    const args = process.argv.slice(2);
    const targets: string[] = [];
    let out = join(root, 'dist');
    for (let i = 0; i < args.length; i += 1) {
        if (args[i] === '--target') targets.push(args[++i]!);
        else if (args[i] === '--out') out = args[++i]!;
    }
    const current = `bun-${process.platform === 'win32' ? 'windows' : process.platform}-${process.arch === 'arm64' ? 'arm64' : 'x64'}`;
    await build(targets.length > 0 ? targets : [current], out);
}
