export const OVERLAP_SOURCES = {
    literal: 'export const pattern = /[]/;\n',
    constructor: "export const pattern = new RegExp('[]');\n",
    template: 'export const pattern = new RegExp(`[]`);\n',
    intersection: "export const pattern = new RegExp('[a&&b]', 'v');\n",
    negated: 'export const pattern = /[^]/;\n',
    escaped: 'export const pattern = /\\[\\]/;\n',
    rethrow: "export function run() { try { console.log('ready'); } catch (error) { throw error; } }\n",
    finalizer:
        "export function run() { try { console.log('ready'); } catch (error) { throw error; } finally { console.log('done'); } }\n",
    transformed: "export function run() { try { console.log('ready'); } catch ({ message }) { throw { message }; } }\n",
    handled:
        "export function run() { try { console.log('ready'); } catch (error) { console.log(error); throw error; } }\n",
    nested: "export function run() { if (Date.now()) { if (Math.random()) { console.log('ready'); } } }\n",
    blockless: "export function run() { if (Date.now()) if (Math.random()) console.log('ready'); }\n",
    alternate:
        "export function run() { if (Date.now()) { if (Math.random()) { console.log('ready'); } else { console.log('waiting'); } } }\n",
};

export const OVERLAP_PROJECT = {
    'package.json': '{"private":true,"type":"module"}\n',
    'tsconfig.json':
        '{"compilerOptions":{"target":"ES2022","module":"NodeNext","moduleResolution":"NodeNext","types":[]},"include":["*.ts"]}\n',
    'literal.js': OVERLAP_SOURCES.literal,
    'literal.ts': OVERLAP_SOURCES.literal,
    'constructor.js': OVERLAP_SOURCES.constructor,
    'constructor.ts': OVERLAP_SOURCES.constructor,
    'template.js': OVERLAP_SOURCES.template,
    'template.ts': OVERLAP_SOURCES.template,
    'intersection.js': OVERLAP_SOURCES.intersection,
    'intersection.ts': OVERLAP_SOURCES.intersection,
    'negated.js': OVERLAP_SOURCES.negated,
    'negated.ts': OVERLAP_SOURCES.negated,
    'escaped.js': OVERLAP_SOURCES.escaped,
    'escaped.ts': OVERLAP_SOURCES.escaped,
    'rethrow.js': OVERLAP_SOURCES.rethrow,
    'rethrow.ts': OVERLAP_SOURCES.rethrow,
    'finalizer.js': OVERLAP_SOURCES.finalizer,
    'finalizer.ts': OVERLAP_SOURCES.finalizer,
    'transformed.js': OVERLAP_SOURCES.transformed,
    'transformed.ts': OVERLAP_SOURCES.transformed,
    'handled.js': OVERLAP_SOURCES.handled,
    'handled.ts': OVERLAP_SOURCES.handled,
    'nested.js': OVERLAP_SOURCES.nested,
    'nested.ts': OVERLAP_SOURCES.nested,
    'blockless.js': OVERLAP_SOURCES.blockless,
    'blockless.ts': OVERLAP_SOURCES.blockless,
    'alternate.js': OVERLAP_SOURCES.alternate,
    'alternate.ts': OVERLAP_SOURCES.alternate,
};

export const OVERLAP_CORRECTION = "export const pattern = /[a]/;\nexport function run() { console.log('ready'); }\n";

export const OVERLAP_SEVERITIES = {
    'no-empty-character-class': [0],
    'regexp/no-empty-character-class': [2],
    'sonarjs/no-empty-character-class': [0],
    'no-useless-catch': [2],
    'sonarjs/no-useless-catch': [0],
    'unicorn/no-lonely-if': [0],
    'sonarjs/no-collapsible-if': [2],
};

export const OVERLAP_FINDINGS = {
    alternate: [],
    blockless: [{ ruleId: 'sonarjs/no-collapsible-if', line: 1, column: 25, severity: 2 }],
    constructor: [{ ruleId: 'regexp/no-empty-character-class', line: 1, column: 36, severity: 2 }],
    escaped: [],
    finalizer: [{ ruleId: 'no-useless-catch', line: 1, column: 55, severity: 2 }],
    handled: [],
    intersection: [{ ruleId: 'regexp/no-empty-character-class', line: 1, column: 36, severity: 2 }],
    literal: [{ ruleId: 'regexp/no-empty-character-class', line: 1, column: 25, severity: 2 }],
    negated: [],
    nested: [{ ruleId: 'sonarjs/no-collapsible-if', line: 1, column: 25, severity: 2 }],
    rethrow: [{ ruleId: 'no-useless-catch', line: 1, column: 25, severity: 2 }],
    template: [{ ruleId: 'regexp/no-empty-character-class', line: 1, column: 35, severity: 2 }],
    transformed: [],
};

export const BINDING_SOURCES = {
    dependency: 'export class Widget {}\nexport const value = 1;\n',
    local: 'export function run() { const unused = 1; return 2; }\n',
    function: 'export function run() { function unused() { return 1; } return 2; }\n',
    ignored: 'export function run() { const _unused = 1; return 2; }\n',
    read: 'export function run() { const value = 1; return value; }\n',
    import: "import { value } from './dependency.js';\nexport const result = 2;\n",
    ignoredImport: "import { value as _unused } from './dependency.js';\nexport const result = 2;\n",
    jsdoc: "import { Widget } from './dependency.js';\n/** @type {Widget | undefined} */\nexport const result = undefined;\n",
    typed: "import { Widget } from './dependency.js';\nexport const result: Widget | undefined = undefined;\n",
};

export const BINDING_PROJECT = {
    'package.json': '{"private":true,"type":"module"}\n',
    'tsconfig.json':
        '{"compilerOptions":{"target":"ES2022","module":"NodeNext","moduleResolution":"NodeNext","types":[]},"include":["*.ts","*.cts"]}\n',
    'dependency.js': BINDING_SOURCES.dependency,
    'dependency.ts': BINDING_SOURCES.dependency,
    'local.js': BINDING_SOURCES.local,
    'local.ts': BINDING_SOURCES.local,
    'function.js': BINDING_SOURCES.function,
    'function.ts': BINDING_SOURCES.function,
    'ignored.js': BINDING_SOURCES.ignored,
    'ignored.ts': BINDING_SOURCES.ignored,
    'read.js': BINDING_SOURCES.read,
    'read.ts': BINDING_SOURCES.read,
    'import.js': BINDING_SOURCES.import,
    'import.ts': BINDING_SOURCES.import,
    'ignored-import.js': BINDING_SOURCES.ignoredImport,
    'ignored-import.ts': BINDING_SOURCES.ignoredImport,
    'types.js': BINDING_SOURCES.jsdoc,
    'types.ts': BINDING_SOURCES.typed,
};

export const EXECUTION_SOURCES = {
    eval: 'export const result = eval(process.env.SCRIPT);\n',
    static: "export const result = eval('1 + 1');\n",
    template: 'export const result = eval(`1 + 1`);\n',
    function: 'export const result = new Function(process.env.SCRIPT);\n',
    vm: "import { runInNewContext } from 'node:vm';\nexport const result = runInNewContext(process.env.SCRIPT);\n",
    url: 'export const result = `javascript:${process.env.SCRIPT}`;\n',
    buffer: 'export const result = new Buffer(process.env.DATA);\n',
    literal: 'export const result = new Buffer(8);\n',
    alias: "import { Buffer as Bytes } from 'node:buffer';\nexport const result = new Bytes(8);\n",
    safe: 'export const result = Buffer.alloc(8);\n',
    shadow: 'class Buffer { constructor(value) { this.value = value; } }\nexport const result = new Buffer(Date.now());\n',
    shadowEval: 'function run(eval) { return eval(process.env.SCRIPT); }\nmodule.exports = run;\n',
};

export const EXECUTION_PROJECT = {
    'eval.js': EXECUTION_SOURCES.eval,
    'eval.ts': EXECUTION_SOURCES.eval,
    'static.js': EXECUTION_SOURCES.static,
    'static.ts': EXECUTION_SOURCES.static,
    'static-template.js': EXECUTION_SOURCES.template,
    'static-template.ts': EXECUTION_SOURCES.template,
    'dynamic-function.js': EXECUTION_SOURCES.function,
    'dynamic-function.ts': EXECUTION_SOURCES.function,
    'vm.js': EXECUTION_SOURCES.vm,
    'vm.ts': EXECUTION_SOURCES.vm,
    'url.js': EXECUTION_SOURCES.url,
    'url.ts': EXECUTION_SOURCES.url,
    'buffer.js': EXECUTION_SOURCES.buffer,
    'buffer.ts': EXECUTION_SOURCES.buffer,
    'literal-buffer.js': EXECUTION_SOURCES.literal,
    'literal-buffer.ts': EXECUTION_SOURCES.literal,
    'alias-buffer.js': EXECUTION_SOURCES.alias,
    'alias-buffer.ts': EXECUTION_SOURCES.alias,
    'safe-buffer.js': EXECUTION_SOURCES.safe,
    'safe-buffer.ts': EXECUTION_SOURCES.safe,
    'shadow-buffer.js': EXECUTION_SOURCES.shadow,
    'shadow-buffer.ts': EXECUTION_SOURCES.shadow,
    'shadow-eval.cjs': EXECUTION_SOURCES.shadowEval,
    'shadow-eval.cts': EXECUTION_SOURCES.shadowEval,
};

export const BINDING_FINDINGS = {
    'dependency.js': [],
    'dependency.ts': [],
    'function.js': [{ ruleId: 'no-unused-vars', line: 1, column: 34, severity: 2 }],
    'function.ts': [{ ruleId: '@typescript-eslint/no-unused-vars', line: 1, column: 34, severity: 2 }],
    'ignored-import.js': [],
    'ignored-import.ts': [],
    'ignored.js': [],
    'ignored.ts': [],
    'import.js': [{ ruleId: 'no-unused-vars', line: 1, column: 10, severity: 2 }],
    'import.ts': [{ ruleId: '@typescript-eslint/no-unused-vars', line: 1, column: 10, severity: 2 }],
    'local.js': [{ ruleId: 'no-unused-vars', line: 1, column: 31, severity: 2 }],
    'local.ts': [{ ruleId: '@typescript-eslint/no-unused-vars', line: 1, column: 31, severity: 2 }],
    'read.js': [],
    'read.ts': [],
    'types.js': [],
    'types.ts': [],
};

export const EXECUTION_FINDINGS = {
    'alias-buffer.js': [{ ruleId: 'n/no-deprecated-api', line: 2, column: 23, severity: 2 }],
    'alias-buffer.ts': [{ ruleId: 'n/no-deprecated-api', line: 2, column: 23, severity: 2 }],
    'buffer.js': [{ ruleId: 'n/no-deprecated-api', line: 1, column: 23, severity: 2 }],
    'buffer.ts': [{ ruleId: 'n/no-deprecated-api', line: 1, column: 23, severity: 2 }],
    'dynamic-function.js': [{ ruleId: 'sonarjs/code-eval', line: 1, column: 27, severity: 2 }],
    'dynamic-function.ts': [{ ruleId: 'sonarjs/code-eval', line: 1, column: 27, severity: 2 }],
    'eval.js': [{ ruleId: 'sonarjs/code-eval', line: 1, column: 23, severity: 2 }],
    'eval.ts': [{ ruleId: 'sonarjs/code-eval', line: 1, column: 23, severity: 2 }],
    'literal-buffer.js': [{ ruleId: 'n/no-deprecated-api', line: 1, column: 23, severity: 2 }],
    'literal-buffer.ts': [{ ruleId: 'n/no-deprecated-api', line: 1, column: 23, severity: 2 }],
    'safe-buffer.js': [],
    'safe-buffer.ts': [],
    'shadow-buffer.js': [],
    'shadow-buffer.ts': [],
    'shadow-eval.cjs': [],
    'shadow-eval.cts': [],
    'static-template.js': [],
    'static-template.ts': [],
    'static.js': [],
    'static.ts': [],
    'url.js': [{ ruleId: 'sonarjs/code-eval', line: 1, column: 23, severity: 2 }],
    'url.ts': [{ ruleId: 'sonarjs/code-eval', line: 1, column: 23, severity: 2 }],
    'vm.js': [{ ruleId: 'sonarjs/code-eval', line: 2, column: 23, severity: 2 }],
    'vm.ts': [{ ruleId: 'sonarjs/code-eval', line: 2, column: 23, severity: 2 }],
};

export const BINDING_SEVERITIES = {
    'no-unused-vars': 2,
    '@typescript-eslint/no-unused-vars': null,
    'sonarjs/no-unused-vars': 0,
    'sonarjs/unused-import': 0,
    'security/detect-eval-with-expression': 0,
    'sonarjs/code-eval': 2,
    'security/detect-new-buffer': 0,
    'n/no-deprecated-api': 2,
};
