import packageManifest from '@gspot/cli/package.json' with { type: 'json' };
import { environmentVariables } from '@gspot/cli/src/platform/environment.ts';

const revision = environmentVariables()['GSPOT_DOCS_REVISION'];
if (revision !== undefined && !/^[a-f\d]{40}$/u.test(revision)) {
    throw new Error('GSPOT_DOCS_REVISION must be a full source commit ID.');
}

export const sourceRevision = revision ?? 'main';

export const REFERENCE_MARKER = '<!-- Generated by bun docs/reference-pages.ts. -->';

/**
 * Label generated documentation with its version, source owner, and ownership marker.
 * @param title the page title
 * @param description the page description
 * @param owner the repository-relative definition path
 * @returns Markdown front matter and source provenance
 */
export function referenceHeader(
    title: string,
    description: string,
    owner = 'packages/cli/src/policy/schema.ts',
): string {
    const source = `https://github.com/stefanionescu/gspot/blob/${sourceRevision}/${owner}`;
    return `---\ntitle: ${JSON.stringify(title)}\ndescription: ${JSON.stringify(description)}\neditUrl: ${JSON.stringify(source)}\n---\n\n${REFERENCE_MARKER}\n\ngspot ${packageManifest.version} · [Source definition](${source})\n\n`;
}
