// Native spellings exercise the public naming contracts independently of the shipped assets.
export const FRAMEWORK_CONTRACTS = [
    {
        configuration: 'nextjs',
        names: ['getStaticProps', 'getServerSideProps', 'generateMetadata', 'generateStaticParams', 'generateViewport'],
        banned: [
            'get static props',
            'get server side props',
            'generate metadata',
            'generate static params',
            'generate viewport',
        ],
    },
    {
        configuration: 'react',
        names: ['useSyncExternalStore', 'getSnapshot', 'getServerSnapshot'],
        banned: ['use sync external store', 'get snapshot', 'get server snapshot'],
    },
];

export const BASH_NAMES = [
    'IFS',
    'OPTARG',
    'OPTIND',
    'EUID',
    'UID',
    'PPID',
    'RANDOM',
    'SECONDS',
    'LINENO',
    'BASH_SOURCE',
    'BASH_REMATCH',
    'BASH_VERSION',
    'BASH_VERSINFO',
    'FUNCNAME',
    'PIPESTATUS',
    'REPLY',
    'CDPATH',
    'OLDPWD',
    'SHLVL',
    'HOSTNAME',
    'OSTYPE',
    'MACHTYPE',
    'COLUMNS',
    'LINES',
];

export const PYTHON_NAMES = [
    '__init__',
    '__main__',
    '__all__',
    '__name__',
    '__file__',
    '__dict__',
    '__slots__',
    '__repr__',
    '__str__',
    '__eq__',
    '__hash__',
    '__len__',
    '__iter__',
    '__next__',
    '__enter__',
    '__exit__',
    '__call__',
    '__getitem__',
    '__setitem__',
    '__delitem__',
    '__contains__',
    '__lt__',
    '__le__',
    '__gt__',
    '__ge__',
    '__ne__',
    '__bool__',
    '__post_init__',
    '__class_getitem__',
    '__aenter__',
    '__aexit__',
    '__await__',
    '__aiter__',
    '__anext__',
    '__new__',
    '__spec__',
    '__package__',
    '__loader__',
    '__cached__',
    '__doc__',
    '__annotations__',
    '__path__',
    '__class__',
    '__classcell__',
    '__qualname__',
    '__builtins__',
];

export const LIFECYCLE_NAMES = ['setUp', 'setUpClass', 'tearDown', 'tearDownClass'];

export const FOREIGN_NAMES = [
    'getStaticProps',
    'getServerSideProps',
    'generateMetadata',
    'generateStaticParams',
    'generateViewport',
    'useSyncExternalStore',
    'getSnapshot',
    'getServerSnapshot',
    'setUp',
    'setUpClass',
    'tearDown',
    'tearDownClass',
    'IFS',
    'OPTARG',
    'OPTIND',
    'EUID',
    'UID',
    'PPID',
    'RANDOM',
    'SECONDS',
    'LINENO',
    'BASH_SOURCE',
    'BASH_REMATCH',
    'BASH_VERSION',
    'BASH_VERSINFO',
    'FUNCNAME',
    'PIPESTATUS',
    'REPLY',
    'CDPATH',
    'OLDPWD',
    'SHLVL',
    'HOSTNAME',
    'OSTYPE',
    'MACHTYPE',
    'COLUMNS',
    'LINES',
    '__init__',
    '__main__',
    '__all__',
    '__name__',
    '__file__',
    '__dict__',
    '__slots__',
    '__repr__',
    '__str__',
    '__eq__',
    '__hash__',
    '__len__',
    '__iter__',
    '__next__',
    '__enter__',
    '__exit__',
    '__call__',
    '__getitem__',
    '__setitem__',
    '__delitem__',
    '__contains__',
    '__lt__',
    '__le__',
    '__gt__',
    '__ge__',
    '__ne__',
    '__bool__',
    '__post_init__',
    '__class_getitem__',
    '__aenter__',
    '__aexit__',
    '__await__',
    '__aiter__',
    '__anext__',
    'URLSession',
    'spawnSync',
    'ESLint',
    'HTMLDialogElement',
];
