/** The environment check follows the authored check selection and accepted findings. */
export const STAGED_CASES = [
    {
        name: 'selected',
        configurations: ['secrets'],
        check: 'repository/tracked-files',
        flags: [],
        ignore: '',
        code: 1,
        status: 'failed',
        findings: [{ file: '.env', line: 1, rule: 'tracked-file' }],
    },
    {
        name: 'absent',
        configurations: [],
        check: 'project/source',
        flags: [],
        ignore: '',
        code: 0,
        status: 'passed',
        findings: [],
    },
    {
        name: 'ignored',
        configurations: ['secrets'],
        check: 'repository/tracked-files',
        flags: [],
        ignore: '\n[[ignore]]\ncheck = "repository/tracked-files"\npaths = [".env"]\nreason = "This example contains public test values."\n',
        code: 0,
        status: 'passed',
        findings: [],
    },
    {
        name: 'skipped',
        configurations: ['secrets'],
        check: 'repository/tracked-files',
        flags: ['--skip', 'repository/tracked-files'],
        ignore: '',
        code: 0,
        status: 'skipped',
        findings: [],
    },
] as const;

/** Selected and unselected paths for the native repository index contract. */
export const TRACKED_PATTERNS = {
    indexOnly: ['.env.'],
    refused: [
        '.env',
        '.env.local',
        '.env.example.local',
        'nested/.dev.vars.production',
        'node_modules/.env.example',
        'bower_components/package/index.js',
        'python/.venv/lib/package.py',
        'python/nested/venv/lib/package.py',
        'python/deep/.venv/lib/package.py',
        'swift/Pods/Library/source.swift',
        'swift/DerivedData/output.bin',
        'swift/.build/output.bin',
        'sibling/node_modules/package/index.js',
        'sibling/.dev.vars',
    ],
    allowed: [
        '.env.example',
        '.env.template',
        '.env.sample',
        '.dev.vars.example',
        'nested/.env.example',
        'nested/.env.template',
        'nested/.env.sample',
        'nested/.dev.vars.example',
        'python/node_modules/package/index.js',
        'swift/node_modules/package/index.js',
        'sibling/.venv/lib/package.py',
        '.venv/lib/package.py',
        '.build/output.bin',
        'python/source.py',
    ],
    scopes: '[scope.python]\nconfigurations = ["python"]\nremoved_configurations = ["javascript"]\n[scope."python/deep"]\n[scope.swift]\nconfigurations = ["swift"]\nremoved_configurations = ["javascript"]\n[scope.sibling]\n',
};
