import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { stdoutOf } from '@/run/invoke'
import type { GraphNode } from 'types/run'
import type { Lock } from 'types/toolchain'
import { MISE_DEFAULT_TASK_DIRECTORY, MISE_REQUIRED_SETTINGS, MISE_TASK_SUBTREE } from '@config/tasks'
import { writeBlock } from '@/configuration/marked'
import type { EmittedTask, MiseLayout } from 'types/runner'
import type { PinConflict } from 'types/toolchain'
import { invoke } from '@/run/invoke'

export async function readLayout(root: string): Promise<MiseLayout> {
  const configs = stdoutOf(await invoke({ command: ['mise', 'config', 'ls'], cwd: root }), 'mise config ls')
    .split('\n')
    .map((line) => line.trim().split(/\s+/u)[0] ?? '')
    .filter((path) => path.length > 0 && path !== 'Path')
  const tasks = await invoke({ command: ['mise', 'tasks', 'ls', '--no-header'], cwd: root })
  return {
    configs,
    taskDirectory: MISE_DEFAULT_TASK_DIRECTORY,
    existingTasks:
      tasks.outcome === 'ran' && tasks.code === 0
        ? tasks.stdout.split('\n').map((line) => line.trim().split(/\s+/u)[0] ?? '').filter(Boolean)
        : [],
  }
}

export function pinsFor(
  lock: Lock,
  theirs: ReadonlyMap<string, string>,
): { readonly pins: ReadonlyMap<string, string>; readonly conflicts: readonly PinConflict[] } {
  const pins = new Map<string, string>()
  const conflicts: PinConflict[] = []
  for (const tool of lock.tools.values()) {
    const existing = theirs.get(tool.id)
    if (existing === undefined) {
      pins.set(tool.id, tool.version)
      continue
    }
    if (existing !== tool.version) {
      conflicts.push({ tool: tool.id, theirs: existing, ours: tool.version })
    }
  }
  return { pins, conflicts }
}

export function taskBody(node: GraphNode, version: string): string {
  const scope = node.scope === '' ? '' : ` --scope ${node.scope}`
  return [
    '#!/usr/bin/env bash',
    `# Generated by gspot ${version}. Do not edit`,
    '# Regenerate: gspot generate',
    `#MISE description="${node.description}"`,
    'set -euo pipefail',
    '',
    `exec gspot check${scope}`,
    '',
  ].join('\n')
}

export function tasksFor(
  layout: MiseLayout,
  nodes: readonly GraphNode[],
  version: string,
): readonly EmittedTask[] {
  return nodes.map((node) => ({
    path: join(layout.taskDirectory, MISE_TASK_SUBTREE, fileNameOf(node)),
    name: `${MISE_TASK_SUBTREE}:${node.name.replace(/:/gu, '-')}`,
    body: taskBody(node, version),
  }))
}

function fileNameOf(node: GraphNode): string {
  const scope = node.scope === '' ? '' : `-${node.scope.replace(/\//gu, '-')}`
  return `${node.name.replace(/:/gu, '-')}${scope}`
}

export async function writeMiseFiles(
  root: string,
  config: string,
  tasks: readonly EmittedTask[],
): Promise<void> {
  for (const task of tasks) {
    const target = join(root, task.path)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, task.body, { encoding: 'utf8', mode: 0o755 })
  }
  await writeBlock(root, config, MISE_REQUIRED_SETTINGS.join('\n'))
}

export async function existingPins(root: string, config: string): Promise<ReadonlyMap<string, string>> {
  const pins = new Map<string, string>()
  let text: string
  try {
    text = await readFile(join(root, config), 'utf8')
  } catch {
    return pins
  }
  const tools = /\[tools\]([\s\S]*?)(?:\n\[|$)/u.exec(text)?.[1] ?? ''
  for (const line of tools.split('\n')) {
    const found = /^\s*([\w.@/-]+)\s*=\s*"([^"]+)"/u.exec(line)
    if (found?.[1] !== undefined && found[2] !== undefined) pins.set(found[1], found[2])
  }
  return pins
}

export function describeConflict(conflict: PinConflict): readonly string[] {
  return [
    `pin       ${conflict.tool}`,
    `          yours  ${conflict.theirs}`,
    `          gspot  ${conflict.ours}`,
    '          gspot does not change a pin you set. Align the two, or drop yours.',
  ]
}
